### ISSUE TITLE
mossa vocalizzo

### ISSUE THREAD

**Issue by congzhouye** [fuji97/pokemon-xenoverse-tracker#1]
la mossa vocalizzo nella schermata dettagli del pokemon manca la descrizione della mossa(box descrizione completamente vuoto).non essendoci una descrizione non si puo sapere se vi sia contatto tra il pokemon che lo utilizza e quello che subisce,nel caso in cui sia una mossa in cui non c'è contatto l'abilita di sparkowl statico si attiva lo stesso paralizzando il pokemon(effettuato piu prove con trishout).

**Comment by fuji97** [comment]
Grazie per la segnalazione, sistemeremo alla prossima release
