### ISSUE TITLE
Due file Achievements con obiettivi differenti

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#1002]
Ciao a tutti, il problema sulla linea 178, che ha dato noie a molti, ha generato un fatto curioso. Come da indicazioni, ho rinominato il file Achievements in Achievements_old. Il gioco ha, prevedibilmente, creato un nuovo file Achievements vuoto. Ora, mentre stavo giocando, ho sbloccato un obiettivo che non avevo in precedenza. Così facendo, nella cartella di salvataggio, in questo momento ho due file .rxdata, ho Achievements_old, che contiene tutti gli obiettivi sbloccati prima, e Achievements, che contiene quello ottenuto dopo. I due file, quindi, contengono obiettivi diversi e, qualora io dovessi piazzare uno dei due nella cartella di salvataggio, a parte 2 uscita e problema sulla 178 risolto, gli obiettivi dell'altra si perderanno. Chiaramente, il file che userò sarà Achievements_old, opportunamente rinominato in Achievements, visto che contiene tutti gli obiettivi della storia principale. Domanda: questo vuol dire che perderò sicuramente l'obiettivo che ho sbloccato postumo? Premetto che, in questo caso, non sarebbe così importante, era un obiettivo secondario, la mia è curiosità, l'importante è che non si perdano gli obiettivi primari. In questo caso, se faccio una copia di Achievements_old cambiato di nome in Achievements nella cartella di salvataggio, dopo che l'errore 178 è risolto, può funzionare per non perdere almeno tutti gli obiettivi sbloccati finora?
La situazione è quella che potete vedere in allegato.

![0sjssa](https://user-images.githubusercontent.com/31867848/42595523-cf17f0ac-8552-11e8-9665-75d6ab841630.jpg)

**Comment by fuji97** [comment]
Ni, dipende da come sarà strutturato, comunque probabilmente si

**Comment by LeonidaXX1** [comment]
Scusa fuji97, il "sì" a cosa si riferisce? Al fatto che si perdono per forza degli obiettivi, al fatto che posso recuperarli da Achievements_old o ad entrambe le cose?
