### ISSUE TITLE
Errore

### ISSUE THREAD

**Issue by Thunderlight4** [fuji97/pokemon-xenoverse-tracker#1006]
Scusate ma la patch che dovrebbe portare la patch dalla 1.2.1 alla 1.2.2 in realtà è la 1.2.0-1.2.1.
Grazie e state creando un progetto fantastico, inoltre anche passando dalla 1.2.2 alla 1.2.3 mi segnala che devo scaricare l'installer sul sito cosa che ho fatto ma non la cambia anche se ho la patch 1.2.2

**Comment by fuji97** [comment]
Il problema è già stato risolto, basta riscaricare la patch dal sito e dovrebbe andare
