### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by Franky992** [fuji97/pokemon-xenoverse-tracker#1007]
Ho provato a scaricare il setup completo 1.2 e mi da questo 
![imm](https://user-images.githubusercontent.com/32137189/43274087-709c782e-90fe-11e8-99cf-dea2ffb28726.png)

**Comment by fuji97** [comment]
Hai per caso aperto qualche file della cartella di gioco? Semplicemente dice che il file del changelog è già aperto, comunque non è importante, se continua a dare quell'errore sul QUEL file "Changelog.txt" allora puoi fare semplicemente ignora

**Comment by Franky992** [comment]
No non ho aperto nessuna cartella di gioco...... e se faccio ignora continua a darmi altri changelog

**Comment by Franky992** [comment]
ho solo copiato i miei salvataggi magari sono quelli

**Comment by Franky992** [comment]
ho risolto grazie mille
