### ISSUE TITLE
Link patch 1.2.3 non funzionante

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#1008]
Ho provato e riprovato a cliccare sul link di download per la patch 1.2.3 ma riporta il messaggio di errore "File not found"

**Comment by alessio00** [comment]
Aggiungo che se si prova a scaricare la patch 1.2.2 si viene rimandati al download della 1.2.1.

**Comment by LeonidaXX1** [comment]
Esatto, forse stanno sistemando le varie patch nei link corretti. Ne approfitto per chiedere una cosa che ho già fatto presente, ma non ho ben capito la risposta. Ora posso spostare tranquillamente il vecchio file Achievements nella cartella di salvataggio?

**Comment by fuji97** [comment]
@LeonidaXX1 Tutte le patch incrementali sono state rimosse, ora potete scaricare direttamente il Setup completo della 1.2.3

**Comment by LeonidaXX1** [comment]
Sì, visto e scaricato, grazie e davvero complimenti per quello che è sicuramente un ottimo e faticato lavoro che avete fatto e continuate a fare 😃 Per quanto riguarda il file Achievements, io ho recuperato tutti gli obiettivi, lo scrivo qui, così che possa essere letto da chi serve: se avete spostato altrove il file Achievements per via dell'errore sulla 178, potete reinserirlo nella cartella, e se è presente un altro file Achievements naturalmente generato dal gioco perché gliel'avevate tolto, basta eliminarlo e piazzarci al suo posto il vostro Achievements.
