### ISSUE TITLE
Dislivello salterino (?) mancante

### ISSUE THREAD

**Issue by Kitsuhime** [fuji97/pokemon-xenoverse-tracker#103]
https://cdn.discordapp.com/attachments/226081866501849099/356232053252947978/Immagine3.png
Nessuno dei due tile funziona e non è quindi possibile andare in basso a prendere l'oggetto, stessa cosa succede sul successivo dello stesso percorso

**Comment by fuji97** [comment]
Grazie per la segnalazione. sistemeremo il prima possibile
