### ISSUE TITLE
FullScreen

### ISSUE THREAD

**Issue by ENDERZOMBI102** [fuji97/pokemon-xenoverse-tracker#1031]
Ho letto qui su issues che per mettere lo schermo intero bisogna premere alt + invio, non mi funziona.
nessun errore o altro, cambia da piccolo a medio a grande, ma no a fullscreen

**Comment by ENDERZOMBI102** [comment]
![image](https://user-images.githubusercontent.com/36399599/102914965-5146da80-4481-11eb-969a-c6a52865b012.png)
adesso e' entrato in fullscreen, non so come, ma e' distorto

**Comment by PietrobrunoIta** [comment]
Forse la tua è una tastiera come la mia, per entrare in fullscreen devi fare Fn+Alt+Invio

**Comment by ENDERZOMBI102** [comment]
sono io scemo, ho scaricato una versione molto vecchia
