### ISSUE TITLE
Eevolution

### ISSUE THREAD

**Issue by Kitsuhime** [fuji97/pokemon-xenoverse-tracker#104]
Scritto già sulla lista precedente di sylveon, ma almeno ora so come dovrebbero funzionare le evoluzioni secondo degli npc in game:
Sylveon -> Pokèmon verde e bianco in team (shyleon?)
Bandeon-> Pokèmon rosso e nero in team (trishout?)
Scaleon-> Pokèmon blu e azzurro in team (shulong?)
Io ho scelto shulong, quindi dovrebbe evolversi in scaleon ma resta sylveon, non posso confermare per gli altri starter e poter dire se è un errore di frase agli npc per il pokèmon necessario

**Comment by fabstarkey** [comment]
Ciao! La conversazione dei tre tipi era stata fatta prima della scelta conclusiva delle eevolutions,un po' di confusione che risolveremo in pochissimo. La scelta ufficiale è shyleon/bandeon,trishout/scaleon e shulong/sylveon
