### ISSUE TITLE
Bug pokemon non caricato seconda palestra

### ISSUE THREAD

**Issue by nemoos0** [fuji97/pokemon-xenoverse-tracker#1049]
Nella seconda palestra durante la sfida con (Netturbino) Arturo, non appena mette in campo il suo secondo pokemon, Croagunk, si apre una finestra che dice:
```
Exception: NoMethodError
Message: undefined method `setSpeed' for nil:NilClass
179_EliteBattle_Sprites.rb:196:in `setPokemonBitmap'
177_EliteBattle_Scene.rb:1184:in `pbTrainerSendOut'
177_EliteBattle_Scene.rb:1154:in `each'
177_EliteBattle_Scene.rb:1154:in `pbTrainerSendOut'
071_PokeBattle_Battle.rb:1376:in `pbSendOut'
071_PokeBattle_Battle.rb:1401:in `pbReplace_ebs'
175_EliteBattle_Battle.rb:357:in `pbReplace'
071_PokeBattle_Battle.rb:1414:in `pbRecallAndReplace_ebs'
175_EliteBattle_Battle.rb:365:in `pbRecallAndReplace'
071_PokeBattle_Battle.rb:1343:in `pbSwitch'
```

tuttavia il gioco non crusha ma mi permette di andare avanti senza la possibilità di vedere lo sprite del pokemon nemico.
Se provo ad attacarlo compare un'altro messaggio:
```
Exception: NoMethodError
Message: undefined method `bitmap' for nil:NilClass
182_EliteBattle_MoveAnimation.rb:7307:in `playGlobalMoveAnimation'
204_New_Transitions.rb:1052:in `getCenter'
182_EliteBattle_MoveAnimation.rb:2446:in `pbMoveAnimationSpecific064'
182_EliteBattle_MoveAnimation.rb:2445:in `each'
182_EliteBattle_MoveAnimation.rb:2445:in `pbMoveAnimationSpecific064'
(eval):1:in `playGlobalMoveAnimation'
182_EliteBattle_MoveAnimation.rb:71:in `eval'
182_EliteBattle_MoveAnimation.rb:7307:in `playGlobalMoveAnimation'
182_EliteBattle_MoveAnimation.rb:71:in `pbAnimation'
071_PokeBattle_Battle.rb:2350:in `pbAnimation'
```

Sto utilizzando la versione 1.2.6.

Spero possiate risolvere il problema. Vi ringrazio per il gioco che fino ad ora mi è piaciuto moltissimo. E mi complimetto per tutto il lavoro e l'impegno che mettete in questo progetto. Spero di aver contribuito nel rendere questo gioco perfetto.

**Comment by Apedemak-riss** [comment]
Anche io ho lo stesso errore

**Comment by Albe5renz** [comment]
anche io.

**Comment by Apedemak-riss** [comment]
Una soluzione momentanea, e anche quella che ho utilizzato io, é quella di comprare molte pozioni e far sprecare al suo pokemon tutti i PP delle sue mosse finché non muore da solo

**Comment by nemoos0** [comment]
Bug risolto dalla versione 1.2.7
