### ISSUE TITLE
Allenatrice Ermia [messaggio di errore]

### ISSUE THREAD

**Issue by IperDaBidda** [fuji97/pokemon-xenoverse-tracker#105]
![screenshot_20170910025024](https://user-images.githubusercontent.com/31810325/30245251-78a1933c-95d3-11e7-88b7-0694b012bc3d.png)
Dopo la fine della lotta mi appare questo messaggio di errore.
Avevo avviato Xenoverse come amministratore.
Se può essere utile, l'ho sfidata dopo aver fatto evolvere Elekid X nella Frattura Dimensionale dello stesso percorso. Grazie alla lotta Eevee ha imparato Morso e si è evoluto in Sylveon, imparando anche Comete.
L'errore è apparso una volta tornato all'overworld dopo evoluzione di Eevee e apprendimento mossa.

**Comment by fuji97** [comment]
Già segnalato, lo stiamo già risolvendo
