### ISSUE TITLE
bug sulla cattura dei pokemon

### ISSUE THREAD

**Issue by Androsnicos** [fuji97/pokemon-xenoverse-tracker#108]
dopo aver terminato la terza palestra e ricevuto la medaglia zucchero ogni volta che provo a catturare un qualsiasi pokemon al lancio della ball un messaggio mi dice che il pokemon non muò essere catturato, stesso messaggio che appare quando si prova a catturare druddigon nella prima prova della palestra sopracitata....
ora ho fermato la mia azanvata nella storia per paura di incontrare qualche pokemon x e rischiare di non poterlo catturare...
(vorrei sapere se I pokemon X che non vengono catturati perchè mandati ko si possono reincontrare più avanti nella soria, come quando si batte un leggendario negli altri giochi pokemon, dove basta ritrnare dopo un po è questo respawna)
presente pure un errore di descrizione dell mt 34 sanguisuga dove la descrzione parla di fangobomba
present un glitch grafico dove l'ombra del proprio personaggio si duplica e si spsta con noi al'interno della mappa per poi scomparire

qui sotto allego 2 immagini

![bug sulla cattura](https://user-images.githubusercontent.com/31810795/30245513-a8166558-95dc-11e7-8ce1-321484f952ec.JPG)
![mt sanguisuga](https://user-images.githubusercontent.com/31810795/30245515-adcd60be-95dc-11e7-9798-08a659f7e09b.JPG)

**Comment by Reol1000** [comment]
Accade anche a me

**Comment by LeonidaXX1** [comment]
Rilancio la questione, WEEdle. Il gioco è davvero ottimo a livello di trama, ambientazioni e tutto, i bug che ci ho trovato sono miseri e non inficiano affatto la giocabilità, ma questo sì, questo è un bug grave. Catturare i Pokémon è l'essenza stessa del gioco...

**Comment by ivanfgk** [comment]
Chiudo, è stato risolto
