### ISSUE TITLE
red screen 

### ISSUE THREAD

**Issue by microxvzla** [fuji97/pokemon-xenoverse-tracker#109]
red screen after beating 2 pawniard guys in the library, even after reset i get stuck no clue what to do 

![stuck](https://user-images.githubusercontent.com/31812271/30245861-09c5c820-95b5-11e7-914b-16784c4aa1ed.jpg)

**Comment by Evyck** [comment]
use the ring in the bag and apply to your starter to change his/her form

(next time write "question" in the title, please ^.^)

**Comment by microxvzla** [comment]
oh thanks, next time i'll do that
