### ISSUE TITLE
Trigger PokéWES

### ISSUE THREAD

**Issue by Durren-it** [fuji97/pokemon-xenoverse-tracker#11]
Lo sblocco del PokéWES mi si è buggato, facendomi partire direttamente con l'assegnazione dell'oggetto appena entrato nel laboratorio, fermo sull'uscio dell'entrata, saltando probabilmente parte del discorso. Non so se è successo perchè sono ritornato indietro solo quando ero arrivato al Campus Acero (avendo già la pietra della Grotta Ghiacciata) o, in caso non ci fossero state altre possibilità prima che io ho mancato, sia qualcosa di fisso.
Aggiungo che non sono tornato al laboratorio dopo la prima palestra.
Edit1: Noto ora che il testo dell'aumento della difesa speciale è in inglese (omnibuff da Funestovento).

**Comment by fuji97** [comment]
Grazie per la segnalazione
