### ISSUE TITLE
Settare il volume del gioco (BGM/Effetti)

### ISSUE THREAD

**Issue by Nietrem** [fuji97/pokemon-xenoverse-tracker#110]
Se possibile sarebbe una cosa molto comoda, se inserireste in future patch tra le opzioni la possibilità di settare i livelli audio della musica e degli effetti perchè a parer mio l'audio di default è troppo alto (nonostanto io setti l'audio dal mixer audio del pc a 1 è comunque alto xD)
Ps. ho notato che alcune mosse come per esempio leccata hanno il visual effect di graffio o semplicemente non corrispondente alla mossa effettuata, mi chiedevo se era un bug mio oppure per adesso è proprio così e verrà cambiato in future patch?

**Comment by Kitsuhime** [comment]
Le mosse al momento han tutte grafiche di una mossa di quel tipo speciale/fisica, per esempio fangosberla ha l'animazione di geoforza mentre una mossa terra fisica ha quella di terremoto, idem per gli altri tipi con altre mosse

**Comment by fabstarkey** [comment]
per l'audio non possiamo farci niente, non è dovuto da noi ma dal programma...
