### ISSUE TITLE
il personaggio non si muove

### ISSUE THREAD

**Issue by THEANY1703** [fuji97/pokemon-xenoverse-tracker#111]
Salve ieri dopo aver preso il "prototipo di xenoball" dall'isola ed essere andato al laboratorio di Ezio, parlando con lui si scopre che è una normalissima xenoball quindi di conseguenza dobbiamo tornare all'isola a parlare con lo scienziato mentre ero salito nella nave sono entrato nella stanza del venditore ambulante prima mi compro alcune pokeball, ed esco dalla stanza però mi accorgo di una pokeball posata accanto al venditore cerco di aprirla ma il venditore mi sfida cosi incomincio una battaglia con lui dove perdo appena perdo mi ritrovo sull'isola con tutta la squadra curata chiedo al capitano di riportarmi a Ludopoli pero mi trovo dietro al capitano che non mi lascia passare pero gli posso chiedere di andare all'isola salgo sulla nave e da li in poi non posso più muovere il personaggio però posso accedere hai vari menu posso salvare e fare tutto il resto. ho provato ha disinstallare e reinstallare il gioco sostituendo la cartella data però sono sempre al punto di prima 
![screenshot 2017-09-10 10 41 07](https://user-images.githubusercontent.com/31816621/30247425-ab603814-9614-11e7-9374-29e81d530ea8.png)

**Comment by fabstarkey** [comment]
ciao! abbiamo risolto l'errore con la patch che uscirà a breve. Non possiamo però darti la certezza che ripotrai continuare con questo save!
