### ISSUE TITLE
Crash Infermira joy

### ISSUE THREAD

**Issue by Pizdav** [fuji97/pokemon-xenoverse-tracker#113]
Sono andato a curare i pokemon ma quando Arriva la schermata nera per il curare dei pokemon ecco che mi crasha il gioco 
![image](https://user-images.githubusercontent.com/31807023/30247473-0e3137f8-9616-11e7-95ed-ecc4992ddb9d.png)

**Comment by LeoPantaniHD** [comment]
Basta che esegui il gioco come amministratore
