### ISSUE TITLE
bug montanara e doppiocolpo

### ISSUE THREAD

**Issue by Taikangino** [fuji97/pokemon-xenoverse-tracker#118]
allora dopo la seconda medaglia nel percorso dopo c'è una montanara, se ci parlo dopo la lotta mi crasha il gioco

altra cosa Doppiocolpo ha davvero una precisione del 90%? metà degli attacchi missa come se ne avesse solo 50% di questa non sono sicuro ma nel caso sappiate dirmi

**Comment by Evyck** [comment]
per la montanara dava anche a me un piccolo problema
hai provato a far partire il gioco tramite tasto destro e usa come amministratore?

**Comment by fabstarkey** [comment]
abbiamo risolto tutto, sarà disponibile nella patch.
