### ISSUE TITLE
Crash percorso 5

### ISSUE THREAD

**Issue by Durren-it** [fuji97/pokemon-xenoverse-tracker#12]
Stavo esplorando il percorso 5 e alla fine di una lotta mi esce questo errore quando cerco di riparlarci
![crash](https://user-images.githubusercontent.com/31782838/30234822-87cc027a-9501-11e7-9b86-dce7a194abb4.png)
l'allenatrice in questione
![crash2](https://user-images.githubusercontent.com/31782838/30234838-b0b731aa-9501-11e7-9a9a-572758d47994.png)

**Comment by fuji97** [comment]
Grazie per la segnalazione, sistemeremo per la prossima release
