### ISSUE TITLE
crash grotta ghiacciolo

### ISSUE THREAD

**Issue by andrix95** [fuji97/pokemon-xenoverse-tracker#120]
quando parlo con estaben dentro grotta ghiacciolo il gioco è crashato, quando lo riapro mi dice script error whitin event 2, map 16 (grotta ghiacciolo).    
Perfavore risolvete se no non posso giocare.

**Comment by andrix95** [comment]
non posso giocare perchè il gioco si è salvato automaticamente

**Comment by fabstarkey** [comment]
ciao! succede solo a te questa cosa, devi per forza ricominciarlo!
