### ISSUE TITLE
Errore caricamento Linux

### ISSUE THREAD

**Issue by Danox0** [fuji97/pokemon-xenoverse-tracker#121]
Praticamente quando arrivo alla parte che dice premi start lo premo il gioco si blocca e mi dice che deve essere chiuso per un errore

**Comment by Evyck** [comment]
su linux?
mi pare che il gioco funzioni bene solo su windows quindi, o metti una macchina virtuale (e mica detto che funzioni al 100% come con i mac) oppure non so

**Comment by fabstarkey** [comment]
su Linux non sappiamo proprio dirti se e come può funzionare, usa un windows!
