### ISSUE TITLE
animazioni

### ISSUE THREAD

**Issue by Harry11111111** [fuji97/pokemon-xenoverse-tracker#122]
le animazioni di leccata sono come quelle di graffio

**Comment by Kitsuhime** [comment]
Come già risposto le mosse hanno animazioni di una mossa del loro tipo fisica/speciale dipendente dalla mossa: per esempio le mosse terra se fisiche han tutte l'animazione di terremoto (o magnitudo) mentre se speciali di geoforza, han detto che man mano le aggiungeranno
