### ISSUE TITLE
Domanda: evoluzioni per scambio

### ISSUE THREAD

**Issue by Kitsuhime** [fuji97/pokemon-xenoverse-tracker#123]
Al momento non essendo possibile fare scambi (almeno credo) è possibile far evolvere haunter/kadabra ecc?

**Comment by varola** [comment]
Al momento non è possibile evolvere pokemon tramite scambio, col l arrivo della parte due si avrà la possibilità di usare funzioni online (tra cui lo scambio)

**Comment by Kitsuhime** [comment]
Grazie mille!
