### ISSUE TITLE
palestra

### ISSUE THREAD

**Issue by Taikangino** [fuji97/pokemon-xenoverse-tracker#125]
allora dopo la seconda medaglia nel percorso dopo c'è una montanara, se ci parlo dopo la lotta mi crasha il gioco

altra cosa Doppiocolpo ha davvero una precisione del 90%? metà degli attacchi missa come se ne avesse solo 50% di questa non sono sicuro ma nel caso sappiate dirmi

**Comment by Taikangino** [comment]
nella terza palestra mi dice che ho sconfitto druddigon anche se ho fallito

**Comment by fabstarkey** [comment]
abbiamo già corretto tutto, grazie per la segnalazione!
