### ISSUE TITLE
problemi con le scelte delle risposte.

### ISSUE THREAD

**Issue by REYBAN23** [fuji97/pokemon-xenoverse-tracker#127]
da quando ho iniziato la mia avventura su xenoverse ho questi problemi. 
non mi fa visualizzare nessuno delle scelte. e poi ho trovato questo secondo bug. ma comunque ottimo gioco.

[xenoverse errore 2](https://user-images.githubusercontent.com/31818803/30248160-f8245424-9622-11e7-8ff3-f619ab46b8e5.jpg)

![xenoverse errore 1](https://user-images.githubusercontent.com/31818803/30248130-8500804e-9622-11e7-814f-001e39a564c8.jpg)

**Comment by Kitsuhime** [comment]
Per le scelte credo devi installare i font se non lo hai già fatto (quelli nella loro cartella)

**Comment by REYBAN23** [comment]
va bene grazie
