### ISSUE TITLE
Impossibile far evolvere Elekid X

### ISSUE THREAD

**Issue by Sali3t** [fuji97/pokemon-xenoverse-tracker#128]
Dopo la seconda palestra quando Ezio ci porta ad un albero per far evolvere i Pokémon X a me non funziona. Ho provato cliccandoci sopra ma non é cambiato niente

**Comment by Kitsuhime** [comment]
Provato a fare livellare elekid in prossimità dell'albero? (l'ho subito boxxato io quindi non so dirti con certezza)

**Comment by Evyck** [comment]
se hai una caramella rara usala in prossimità dell'albero (ne puoi ricevere una sconfiggendo il mercante a sud del campo, aprendo il suo box)

**Comment by Coccio98** [comment]
Devi farl livellare elekid vicino all'albero, come se fosse un eevee e dovessi farlo evolvere in leafeon o glaceon
