### ISSUE TITLE
Battaglia in doppio nel Corridoio Roccioso

### ISSUE THREAD

**Issue by Yesupreme** [fuji97/pokemon-xenoverse-tracker#132]
Durante la battaglia contro il Team Dimension prima di ottenere uno dei due fossili nel Corridoio Roccioso ho notato un errore che si presenta solo nel caso in cui Alice mandi in campo Farrowl. Il problema si presenta ogni volta che il Pokémon dovrebbe attaccare, impedendogli di eseguire una qualunque mossa, ma non fa crashare il gioco. Al contrario, è possibile terminare la battaglia normalmente e proseguire senza alcun problema.

![immagine](https://user-images.githubusercontent.com/31799504/30248299-3e941f46-9625-11e7-8f22-2424d2a7c316.png)

**Comment by Yesupreme** [comment]
Aggiungo che credo l' errore abbia qualcosa a che fare con il bug dello scirpt follow-me.
Non mi ero accorto che cambiando il primo Pokemon in squadra Alice venisse sostituita da quest' ultimo e ho chiuso il gioco senza salvare appena ci ho fatto caso. Rifacendo la battaglia senza attivare questo bug Farrowl è stato in grado di attaccare normalmente.

**Comment by ivanfgk** [comment]
Testato e funzionante
