### ISSUE TITLE
Bug vari

### ISSUE THREAD

**Issue by Coccio98** [fuji97/pokemon-xenoverse-tracker#133]
Vorrei segnalare alcuni bug che ho trovato

Il tipo di Trumpille forma Heracross è sbagliato
![capture000](https://user-images.githubusercontent.com/31818421/30248095-dea3402e-9621-11e7-9510-03acff20ac99.jpg)

Si può entrare in alcuni alberi all'inizio del percorso 5, vicino all'albero dove si può fare evolvere elekid X
![capture003](https://user-images.githubusercontent.com/31818421/30248101-e8adbb58-9621-11e7-9ac3-eab146d9f436.jpg)

C'è una zona del percorso 5 bloccata da un giocatore di baseball che è possible raggiungere quando ti sfida perchè si sposta, ma quando ritorni nel percorso l'area risulta inaccesibile
![capture004](https://user-images.githubusercontent.com/31818421/30248129-7dc1c860-9622-11e7-8d55-fdcfec8244ec.jpg)

Gli angoli del centro pokemon del Borgo Mela sono glitchatti
![capture006](https://user-images.githubusercontent.com/31818421/30248161-030378ca-9623-11e7-9725-3ff8e58e6aac.jpg)
![capture007](https://user-images.githubusercontent.com/31818421/30248162-0659dbf4-9623-11e7-93ca-40a6520e6aba.jpg)

Quando si usa l'amo vecchio con il tasto rapido f5 parte la pesca classica dei vecchi giochi pokemon, senza però pescare nulla
![capture009](https://user-images.githubusercontent.com/31818421/30248177-44106b52-9623-11e7-8c88-a9d8926c9ac9.jpg)
![capture010](https://user-images.githubusercontent.com/31818421/30248178-45e67872-9623-11e7-86e4-52825002da0e.jpg)
![capture011](https://user-images.githubusercontent.com/31818421/30248179-491e8804-9623-11e7-8332-0fb9e2f382a8.jpg)

Quest'ultimo bug è un po' più grave presente anche nella vecchia demo, quando nel box nella sezione "sposta pokemon" hai un pokemon in mano per spostarlo e per sbaglio premi "indietro", il pc tornerà nella sezione di selezione della modalità (ritira, deposita o sposta), ma il pokemon che avevi in mano risulta scomparso
![capture013](https://user-images.githubusercontent.com/31818421/30248221-f0c6b716-9623-11e7-9283-a76204dab0e6.jpg)
![capture015](https://user-images.githubusercontent.com/31818421/30248330-e352f390-9625-11e7-817d-e374bb311d48.jpg)
![capture014](https://user-images.githubusercontent.com/31818421/30248225-fb70cb70-9623-11e7-8c47-43ad1d100809.jpg)

Poi spulciando gli achievement ho visto che quello "Fanatico" credo abbia il contatore buggato, perchè segna solo il primo Weedle catturato sui tre richiesti per completarlo; quello "Togepi" nonostante abbia fatto schiudere l'uovo della pensione non me l'ha dato (presumo perchè il nel file achievments.txt ci sia scritto di trovare l'immagine 41_togepi, ma l'icona si chiama 42_togepi); "Extra terrestre portami via" non funziona nonostante abbia catturato sia elekid che sharpedo (credo perchè non gli sia stata assegnata un'immagine nel file .txt); "pesca fortunata" non funziona nonostante abbia pescato una caramella rara.

Infine ci sono molte grafiche di achievements inutilizzate, ma credo che queste verranno introdotte in seguito

Spero di essere stato utile

**Comment by fabstarkey** [comment]
grazie per tutte le segnalazioni! correggeremo a breve!

**Comment by ivanfgk** [comment]
Corretti
