### ISSUE TITLE
Errori di traduzione

### ISSUE THREAD

**Issue by LeoPantaniHD** [fuji97/pokemon-xenoverse-tracker#134]
Invece di Uovo c'è scritto "Uova", il che non è corretto perché è singolare: https://i.imgur.com/PL4IE4D.jpg

Inoltre nella schermata di scelta per i market quando devi scegliere se acquistare o vendere, in fondo è scritto "quit" invece di "Esci"

Invece qui quando prendi l'oggetto DAL pokèmon appare scritto invece che lo riceve: https://i.imgur.com/MqOVdUS.jpg

**Comment by fabstarkey** [comment]
li correggeremo con una patch più avanti
