### ISSUE TITLE
Consigli (uno potrebbe esser spoiler per chi non vuole saper nulla)

### ISSUE THREAD

**Issue by Kitsuhime** [fuji97/pokemon-xenoverse-tracker#137]
Entrambi i consigli riguardano la forma xenoverse dello starter : 
-Shulong X come boss (non so gli altri due) può essere molto fastidioso da battere (non ho provato ad usare scaleon se c'era) per il fatto che avendo 4 vite con ripresa se ne cura due rendendolo noioso da tirare giù (alla fine un bremand portato a +5 di raggioscossa e spammando echeggiavoce con plessimetro l'ha tirato giù a lv 42)
-Le stat anche per questa forma...una forma caratterizzata dall'odio ed altro, ha bisogno di un item per ottenerla... aumenta l'atk sp di 10 e i ps di 7

**Comment by fabstarkey** [comment]
Non sarebbe un boss finale se non fosse difficile! ;)
