### ISSUE TITLE
Bug volo

### ISSUE THREAD

**Issue by Kitsuhime** [fuji97/pokemon-xenoverse-tracker#138]
https://cdn.discordapp.com/attachments/355441988364926999/356397685940420609/Immy.png
Se si usa volo per l'isola voodoo si presenta questa schermata con la scritta "lapras vuole portarti da una parte" e si sente il continuo rumore di scontro su una parete restando così

**Comment by fabstarkey** [comment]
già risolto. Per la patch disponibile a breve non ci sarà più questo errore!
