### ISSUE TITLE
mosse (non) prioritarie

### ISSUE THREAD

**Issue by Taikangino** [fuji97/pokemon-xenoverse-tracker#139]
mi capita spesso che un pkmn avversario più lento di me attacchi prima senza usare mosse prioritarie o rapidartigli

**Comment by Edo17995** [comment]
Con che mosse ti succede? A me capitava con vendetta di trishout, che però dalla 4a generazione ha priorità -4, quindi è normale

**Comment by fabstarkey** [comment]
può succedere, il gioco legge le funzioni della 5 gen
