### ISSUE TITLE
Tranpille blu e nero con la testa diversa dal normale 

### ISSUE THREAD

**Issue by mario1102** [fuji97/pokemon-xenoverse-tracker#140]
![img-20170910-wa0003](https://user-images.githubusercontent.com/31820279/30248767-9f80db4c-962e-11e7-975a-39d759d82eae.jpg)
Ho trovato questo tranpille abbastanza strano penso sia un bug

**Comment by Kitsuhime** [comment]
E' semplicemente un tranpille col manto di un heracross (ha il typing errato ma già segnalato)

**Comment by fabstarkey** [comment]
i tranpille hanno diverse forme alternative, chiudo.
