### ISSUE TITLE
IMPORTANTE: Cancellazione dei dati di Scaleon

### ISSUE THREAD

**Issue by Aster9811** [fuji97/pokemon-xenoverse-tracker#141]
Dopo aver battuto Tryshout X, con in squadra il mio Scaleon e quello di Oleandro, ho perso tutti i dati del mio Scaleon quando ho dovuto restituire ad Oleandro il suo, sto quindi cercando una qualche risposta in quanto era il mio pokemon preferito (nonchè più forte) ed ora l'unico modo rimasto per rifarne uno sarebbe ricominciare il gioco da capo, cosa che preferirei evitare dopo averci già giocato per quasi 12 ore, aspetto risposte il più presto possibile, grazie.

**Comment by fabstarkey** [comment]
ciao aster, ci dispiace per l'errore. Lo script dello scaleon di oleandro, ha eliminato anche il tuo scaleon, ora abbiamo corretto l'errore per la patch. Non si potrà riprendere questo tuo scaleon ma ne distribuiremo uno con un evento speciale per questo problema!

**Comment by Aster9811** [comment]
Ciao, grazie per la risposta, vorrei solo sapere quando farete questo evento e a che livello pensate di distribuire scaleon?

Inviato da Posta per Windows 10

Da: fabstarkey
Inviato: domenica 10 settembre 2017 23:50
A: fuji97/pokemon-xenoverse-tracker
Cc: Aster9811; Author
Oggetto: Re: [fuji97/pokemon-xenoverse-tracker] IMPORTANTE: Cancellazione deidati di Scaleon (#141)

ciao aster, ci dispiace per l'errore. Lo script dello scaleon di oleandro, ha eliminato anche il tuo scaleon, ora abbiamo corretto l'errore per la patch. Non si potrà riprendere questo tuo scaleon ma ne distribuiremo uno con un evento speciale per questo problema!
