### ISSUE TITLE
Bug dello starter che ti segue dopo percorso 7

### ISSUE THREAD

**Issue by Lampard92** [fuji97/pokemon-xenoverse-tracker#142]
Salve come ho scritto nel titolo mi si è presentato il bug dello starter che mi segue solo adesso che sono al percorso 7.
C'è qualcosa che posso fare?

**Comment by Harry11111111** [comment]
veramenta il follow del pokemon è stato disattivato, non hai visto il video

**Comment by Lampard92** [comment]
si infatti è il bug che è presente nelle faq ma a me è apperso solo ora che sono al percorso 7 e incominciare nuovamente il gioco mi da noia

**Comment by fabstarkey** [comment]
ci puoi dire esattamente quando si è attivato il follow(lo starter che ti segue)?

**Comment by Lampard92** [comment]
esattamente quando alice ci segue nella grotta e, insieme a lei dobbiamo batterr le due reclute del team diamante
