### ISSUE TITLE
Nessun modo per disabilitare l'audio del gioco

### ISSUE THREAD

**Issue by acinoroc** [fuji97/pokemon-xenoverse-tracker#145]
Questa è più una proposta che un problema, però ritengo sia una modifica semplice da aggiungere nelle opzioni nel gioco. L'unico modo per ora per disabilitare l'audio del gioco pur ascoltando altro è attraverso il mixer del volume di windows ma lo ritengo parecchio scomodo.
Grazie e buona giornata
Alessio

**Comment by fabstarkey** [comment]
in nessun gioco pokemon è possibile disattivare l'audio. Si può fare solo dalle impostazioni del pc!
