### ISSUE TITLE
Problema Promemoria errata nella pagina Stato Pokemon

### ISSUE THREAD

**Issue by Dhell96** [fuji97/pokemon-xenoverse-tracker#146]
Dopo aver ottenuto la seconda medaglia al capus , i pokemon catturati (Dal percorso 5 in poi) presentano la scritta "Probabilmente ottenuto in un occasione particolare al livello x" nella finestra Promemoria dello stato dei pokemon.
Il pokemon ottenuto prima della comparsa del problema è stato il togepi dall'uovo. Non so se possa centrare. Good Luck!

**Comment by ChiaBaka00** [comment]
Mi sa che il problema si verifica dopo che eevee si unisce alla tua squadra, non per il togepi nell'uovo

**Comment by fabstarkey** [comment]
grazie per l'errore, cercheremo di risolverlo
