### ISSUE TITLE
Il fantasma di nonna Lea

### ISSUE THREAD

**Issue by Kitsuhime** [fuji97/pokemon-xenoverse-tracker#149]
https://cdn.discordapp.com/attachments/226081866501849099/356422958853390348/Immy.png
https://cdn.discordapp.com/attachments/226081866501849099/356423140085071874/Immy.png
Gli screen giustificano il titolo, non è possibile interagirci (ovviamente) mentre quella sul ponte c'è comunque (doppia nonna yee)

**Comment by fabstarkey** [comment]
ci spieghi quando ti è successo? è la prima volta che ci avvisano di questo errore!

**Comment by fabstarkey** [comment]
corretto, grazie mille!
