### ISSUE TITLE
Pokédex Bremand

### ISSUE THREAD

**Issue by Durren-it** [fuji97/pokemon-xenoverse-tracker#15]
La cattura del pokemon Bremand nel pokédex in realtà porta ad un altro pokémon, rendendolo anche impossibile trovare normalmente nel pokédex, funzione di ricerca inclusa, in quanto occupa la posizione 752.
![bug](https://user-images.githubusercontent.com/31782838/30235594-4b02011a-950a-11e7-9dfa-d65b6febc920.png)

**Comment by xWiFi31** [comment]
Ce ne sono 4 diversi. Come Oricorio

**Comment by Durren-it** [comment]
Quello che ho catturato è Elettro/Suono nel percorso 2. Quello che mi appare è tutt'altro.

**Comment by AlberoSaggio** [comment]
È un problema legato alle forme multiple, ce l'hanno già segnalato in molti e risolveremo al più presto
