### ISSUE TITLE
Bremand con sprite sbagliato nel pokedex

### ISSUE THREAD

**Issue by acinoroc** [fuji97/pokemon-xenoverse-tracker#150]
Dopo aver catturato Bremand (versione gatto?) le info del pokemon catturato è di un altro bremand (versione uccello?). 
![image](https://user-images.githubusercontent.com/7151107/30249295-d78ada64-9639-11e7-8965-effb69a6ba8b.png)

**Comment by FireNicoDB** [comment]
idem, anche io ho questo bug, catturato bremand che era un gatto elettrico e mi si apre questa pagina sul pokedex con l'uccello XD.

**Comment by fabstarkey** [comment]
bremand ha più forme alternative, la versione canto (il gallo) è la versione base ;)
