### ISSUE TITLE
Animazione sbagliata

### ISSUE THREAD

**Issue by acinoroc** [fuji97/pokemon-xenoverse-tracker#151]
L'attacco leccata ha come animazione una specie di ombrartigli.

**Comment by Coccio98** [comment]
è normale, lo hanno già detto, moltissimi attacchi non hanno l'animazione giusta, arriveranno col tempo

**Comment by acinoroc** [comment]
Sisi avevo sentito, solo pensavo intendessero gli attacchi con animazione
di default e non quelli con animazioni diverse

Il 10 set 2017 3:30 PM, "Coccio98" <notifications@github.com> ha scritto:

**Comment by Kitsuhime** [comment]
Che poi tutti se ne accorgono su leccata eh? xD
