### ISSUE TITLE
Bug Nave

### ISSUE THREAD

**Issue by Vaanp** [fuji97/pokemon-xenoverse-tracker#153]
Ho affrontato la palestra e subito dopo sono salito sulla nave, però sono morto praticamente subito. Fino a qui tutto nella norma ma quando sono tornato sull'isola e poi ho provato a salire sulla nave il personaggio continuava a camminare verso la nave continuando a produrre il suono di errore che senti quando ti muovi verso un muro. Dopo essere entrato nella nave il personaggio era rivolto verso destra e continuava a camminare verso il muro. Non sono riuscito a farlo muovere in nessun modo e ho dovuto restartare.

**Comment by fabstarkey** [comment]
abbiamo corretto nella patch che sarà disponibile in questi giorni. Ci dispiace per l'inconveniente <3
