### ISSUE TITLE
Funestovento e Forzantica

### ISSUE THREAD

**Issue by Metalcape** [fuji97/pokemon-xenoverse-tracker#154]
Non so se sono stato solo molto sfortunato, ma su circa 30 utilizzi (sia miei che degli avversari) le mosse forzantica e funestovento non hanno mai attivato l'effetto che aumenta tutte le statistiche. Potrebbe essere che è solo un caso ma lo segnalo lo stesso, non si sa mai

**Comment by zioteto** [comment]
Credo che tu sia molto sfortunato =(.
A me, per ora, funestovento ha attivato 2 volte l'effetto, mentre forzantica non ho ancora avuto modo di provarla.

**Comment by Metalcape** [comment]
Ok meglio così, iniziavo a pensare che fossero buggate.
