### ISSUE TITLE
ingiocabile o quasi

### ISSUE THREAD

**Issue by Dade66cl** [fuji97/pokemon-xenoverse-tracker#155]
lavorone, molto bello, così bello che se la game freak lo scoprisse penso che dopo averlo cancellato ne copierebbe le idee per tirar fuori l'8° generazione, detto questo, se il tuo Pokemon è più lento di quello dell'avversario al 90% va K.o.(se non ci va è giusto perché sei 5 livelli più forte), se viene paralizzato non attacca mai, come se fosse congelato(magari sono sfigato io eh), Zubat usa morso, il mio Pokemon tentenna 4 volte su 4 e se la mossa ha qualche effetto secondario (confusione, paralisi, avvelenamento, scottatura, congelamento >.<) questo si attiva SEMPRE.

**Comment by andrix95** [comment]
son bug tuoi, a paralisi fa attacare sempre.

**Comment by KetsubanZero** [comment]
I pokemon lenti che non siano wall con mosse di recovery hanno sempre fatto schifo anche nei giochi ufficiali

**Comment by ivanfgk** [comment]
Hanno già risposto gli altri utenti, testato ma funzionante.
