### ISSUE TITLE
Tileset mancanti nel centro pokèmon di Ludopoli.

### ISSUE THREAD

**Issue by actualpunch** [fuji97/pokemon-xenoverse-tracker#157]
Quando entro nel centro Pokemon, vengono visualizzati solo gli NPC,l'Infermiera Joy e la macchina di cura dei Pokemon. Tutto risulta comunque interagibile.

**Comment by fabstarkey** [comment]
hai provato ad eseguire il gioco come amministratore o a disinstallarlo e correggerlo? Sei l'unico che ha questo problema, un altro ragazzo l'ha corretto reinstallandolo.

**Comment by actualpunch** [comment]
Grazie, appena potrò riproverò l'installazione. Già provato ad eseguire
come amministratore, dato il crash alla cura dei Pokémon che ho riportato
all'inizio (che però appunto si è risolto).

Il 11 set 2017 1:09 PM, "fabstarkey" <notifications@github.com> ha scritto:
