### ISSUE TITLE
Esperienza dei pokemon selvatici

### ISSUE THREAD

**Issue by congzhouye** [fuji97/pokemon-xenoverse-tracker#158]
Premetto che non so se sia una cosa voluta.
Sconfiggendo i pokemon selvatici si riceve una certa quantità di exp che diventa sempre minore man mano che il Pokémon utilizzato aumenta di livello

**Comment by fabstarkey** [comment]
...hai mai giocato a Pokémon?

**Comment by congzhouye** [comment]
Mai notato che calasse l'esperienza droppata dai selvatici 😂

**Comment by congzhouye** [comment]
Anche Pokémon central dice che dipende dal livello e specie del pokemon sconfitto e non quello utilizzato tecnicamente dovrebbe essere stesso pokemon di stesso livello battuti con pokemon diversi o di livelli diversi dovrebbe dare la stessa quantità
