### ISSUE TITLE
Problemi di caricamento

### ISSUE THREAD

**Issue by LexingtonFog** [fuji97/pokemon-xenoverse-tracker#16]
Ho già provato a reinstallare il gioco e ad avviarlo come amministratore ma questi problemi non si risolvono.
In caso vi servissero altre informazioni non esitate a  chiedere.

OS: Windows 10 Pro
CPU: AMD A8-6600K
Ram: 8 gb
GPU: Gtx 660 ti

Vengono caricate le ombre dei personaggi ma non i corpi.

![21533716_1662166033808278_532400836_o](https://user-images.githubusercontent.com/31784757/30236126-59aae994-9513-11e7-96b4-391ebfb55f6f.png)

Le pokèball non vengono visualizzate.

![21460255_1662135300478018_1965250191_o](https://user-images.githubusercontent.com/31784757/30236128-59af3742-9513-11e7-91b6-4da33f8dac53.png)

Quando faccio curare i miei pokèmon le sfere (che dovrebbero essere dentro al macchinario) vengono visualizzate correttamente.

![21460317_1662160887142126_101718511_o](https://user-images.githubusercontent.com/31784757/30236127-59ab983a-9513-11e7-8e15-22d04218525b.png)

**Comment by fuji97** [comment]
Grazie per la segnalazione, puoi per favore farci lo screen della cartella Tileset in Graphics?

**Comment by LexingtonFog** [comment]
Ecco qui; nonostante i bug che ho incontrato si vede che è un bel gioco, spero di poterci giocare presto ç.ç

![immagine](https://user-images.githubusercontent.com/31784757/30241069-ebf14c08-957c-11e7-87fa-b56fa008f114.png)

**Comment by fuji97** [comment]
Ok, sembrerebbe un duplicato del problema #16, prova a dirmi se riesci a risolvere seguendo il procedimento consigliato li

**Comment by LexingtonFog** [comment]
Ok, ho controllato le impostazioni e le ho aggiustate, ora il gioco funziona perfettamente; grazie.
