### ISSUE TITLE
Fonts non visibili anche dopo averli installati e domande

### ISSUE THREAD

**Issue by Maxwell0085** [fuji97/pokemon-xenoverse-tracker#163]
Scusate ma non ho capito sta cosa dei fonts pk io ho visto le altre discussioni che parlavano di questo ma non ho capito bene se per poter leggere i fonts devo aspettare la prossima release che se potete ditemi quando deve uscire pk ci ho provato già più volte ad installarmi ma nulla e poi non ho capito cosa dicevi nel faq della schermata iniziale cioè se non vedete ancora i fonts modificate le impostazioni ma impostazioni di che cosa?

**Comment by fabstarkey** [comment]
vai nella cartella di percorso di Pokemon Xenoverse. Poi clicca su fonts e scaricali tutti (tieni il gioco chiuso). Se non funziona disinstalla il gioco e riscaricalo!
