### ISSUE TITLE
Centro Pokemon iniziale 

### ISSUE THREAD

**Issue by CADORE90** [fuji97/pokemon-xenoverse-tracker#17]
Ciao, al centro Pokemon iniziale se so prova a curare il pokemon il gioco si blocca ed appare una schermata di errore. Poi un consiglio, se possibile aggiungere un tasto per poter accelerare il gioco. E quando farete più o meno uscire la versione per Android?

**Comment by fuji97** [comment]
Ciao, leggi le [FAQ](https://github.com/fuji97/pokemon-xenoverse-tracker), c'è la soluzione temporanea per il Centro Pokèmon, nella prossima versione verrà sistemato automaticamente.
No, non aggiungeremo un tasto per velocizzarebil gioco perché kina l'esperienza di gioco.
Per la questione della versione Android ti rimando all'ultimo video caricato sul canale WEEDle dove ne parlano verso la fine

**Comment by CADORE90** [comment]
Ok grazie mille gentilissimo
