### ISSUE TITLE
Lag e rallentamenti del gioco

### ISSUE THREAD

**Issue by Puzzlebublo** [fuji97/pokemon-xenoverse-tracker#171]
Ciao, lo scrivo qua perché non so altro dove riportare questo mio problema.
Il gioco mi va tremendamente a scatti, le animazioni di incontro pokemon selvatico e di cattura sono eterne. 
Volevo solamente capire se era un problema del mio pc o anche qualcun'altro ha riscontrato il mio stesso problema.
Ci sto giocando su windows 10 (e non su mac).
Sapreste aiutarmi?

Grazie in anticipo

**Comment by Evyck** [comment]
ciao, anche io gioco su w10
è abbastanza potente il tuo pc?
stai giocando con i permessi di amministratore?
(tasto destro sul gioco, run as administrator)

**Comment by Puzzlebublo** [comment]
Si ho giocato con i permessi di amministratore, però nulla da fare ahimé.
Il mio pc è un Intel Core i5 4590, 4GB di RAM, scheda grafica GeForce GTX 960 e Hard Disk SSD.
Gli altri giochi non mi danno questo problema. Non vorrei che fosse qualcosa legato all' antivirus o a qualche opzione strana che non fa andare bene il gioco.

**Comment by fabstarkey** [comment]
ciao! purtroppo è un problema del tuo pc, dato che gli altri utenti non riscontrano il problema..prova a disattivare l'antivirus mentre giochi!

**Comment by Puzzlebublo** [comment]
Ok grazie, ho provato ma nulla da fare... mannaggia... eh vabbé....
