### ISSUE TITLE
Problema Collisioni CampusAcero

### ISSUE THREAD

**Issue by 0C-34** [fuji97/pokemon-xenoverse-tracker#173]
L'accesso ovest di Capus Acero è completamente privo di collisioni sul lato a nord
![catturaxeno](https://user-images.githubusercontent.com/22325420/30251036-9295e998-9658-11e7-877f-0ca693885331.PNG)

**Comment by fabstarkey** [comment]
già aggiustato, disponibile nella patch che uscirà a breve. :)
