### ISSUE TITLE
Evento Gengar

### ISSUE THREAD

**Issue by GaetanoTufariello** [fuji97/pokemon-xenoverse-tracker#174]
Non so come fare per sfidare gengar. Sono bloccato li con il soldato che mi segue, giro per tutta la città ma l'evento non prosegue.. gengar è sulla cima della piramide e davanti a lui a bloccare la salite ci sono tutti i frutti

**Comment by fabstarkey** [comment]
ciao! lo stiamo risolvendo. Con la release della patch sarà possibile continuare l'evento.

**Comment by GameWarrior251** [comment]
quando uscirà la patch?
