### ISSUE TITLE
Piccoli errori grafici

### ISSUE THREAD

**Issue by Sacco99** [fuji97/pokemon-xenoverse-tracker#176]
Sul percorso 6, quando si cammina sopra alcuni fiori viene visualizzato come se fosse erba alta
https://drive.google.com/open?id=0B0AUur7k6UJtUFNGQ3Rvbmx3TjA
https://drive.google.com/open?id=0B0AUur7k6UJtRmJRa25Db2ZycFE
https://drive.google.com/open?id=0B0AUur7k6UJtbmxqQThsWW42MFk

**Comment by fabstarkey** [comment]
grazie per la segnalazione!
