### ISSUE TITLE
casa esteban

### ISSUE THREAD

**Issue by congzhouye** [fuji97/pokemon-xenoverse-tracker#179]
nell'abitazione di esteban dopo essere arrivato dalla nave ho provato a girovagare per la casa e ho notato che alcune caselle(dalla posizione in cui sono fino al vaso) sono intangibili come se ci fosse qualcosa nel mezzo
![esteban](https://user-images.githubusercontent.com/31779770/30252455-40b3e7a4-9673-11e7-9dd7-4eb2cf55eeea.PNG)

**Comment by fabstarkey** [comment]
grazie per la segnalazione. corretto!
