### ISSUE TITLE
non mi estrae tutti i file per il download

### ISSUE THREAD

**Issue by teckentech** [fuji97/pokemon-xenoverse-tracker#18]
allora io scarico il gioco emi comincia a estrarre ma poi mi si blocca 

mando screen

![error](https://user-images.githubusercontent.com/31789748/30237698-fb2fa362-9537-11e7-8117-2ad7153ffd77.PNG)

**Comment by fuji97** [comment]
Prova a riscaricare il gioco e a cambiare la cartella di installazione, potrebbe essere già in uso da qualcos'altro

**Comment by teckentech** [comment]
ho provato a fare il download sia nella cartella c: quella di default quella meno spaziosa sia in quella d: la memoria esterna ma entrambi si bloccano mentre stanno estraendo i dati ho pure cancellato tutti gli altri download precedenti e le cartelle ma non cambia nulla

**Comment by fuji97** [comment]
Ok, allora prova a riscaricare il gioco

**Comment by teckentech** [comment]
andando nel sito? si lo ho gia fatto almeno 5 volte

**Comment by teckentech** [comment]
si blocca sempre sull estrazione

**Comment by teckentech** [comment]
per favore aiutatemi vorrei veramente giocare al vostro gioco

**Comment by teckentech** [comment]
@fuji97 si blocca sempre sull' estrazione ho gia cancellato tutte el copie scaricate ma non cambia nulla non so come fare

**Comment by fuji97** [comment]
Non segnalare lo stesso bug più volte. Comunque quell'errore è causato dal tuo sistema non dall'installer. Hai provato a disabilitare tutti gli antivirus/firewall?

**Comment by teckentech** [comment]
@fuji97 come si disabilitano?

**Comment by fuji97** [comment]
Dipende dall'antivirus che hai
