### ISSUE TITLE
Errore Inseguimento

### ISSUE THREAD

**Issue by zioteto** [fuji97/pokemon-xenoverse-tracker#182]
La mossa Inseguimento non ha priorità, cosa che invece dovrebbe avere. Errore riscontrato più volte quindi escludo bug casuale.

**Comment by rigandrea** [comment]
da pokecentral, la mossa ha priorità "...solo se il pokémon avversario viene sostituito nello stesso turno in cui Inseguimento viene utilizzato".
Hope it helps :)

**Comment by zioteto** [comment]
Ops... Grazie =)
