### ISSUE TITLE
Crash macchine curatrici

### ISSUE THREAD

**Issue by Tuttovideogiochi** [fuji97/pokemon-xenoverse-tracker#184]
Quando entro in un centro pokemon e curo i pokemon mi crasha il gioco e quindi devo curarmi sempre con 500€ alla macchina clefary

**Comment by fabstarkey** [comment]
devi aprire il programma come amministratore:

proprietà>Compatibilità e in basso checkare la spunta esegui questo programma come amministratore.

**Comment by Tuttovideogiochi** [comment]
Grazie


Il 10 set 2017 23:26, "fabstarkey" <notifications@github.com> ha scritto:
