### ISSUE TITLE
non riesco a parlare coi personaggi

### ISSUE THREAD

**Issue by fuji97** [fuji97/pokemon-xenoverse-tracker#185]
ciao, mi metto davanti a un personaggio ma cliccando A non riesco a parlargli credo sia un bug

**Comment by ivanfgk** [comment]
prova a versare del latte col miele sulla tastiera e urlare "DI COLOREH DIVERSOH".
metodo sicuro e garantito.

**Comment by fuji97** [comment]
Fatto, ma ora non mi si accende più il PC, è normale?

**Comment by ivanfgk** [comment]
Certo, questo prova che tu non debba avere tecnologia tra le mani e che devi giocare a briscola con gli anziani nel bar sotto casa.
Bevi molto vino e campa 100 anni, metodo sicuro GARANTITO!

**Comment by fuji97** [comment]
Va bene, grazie, chiudo
