### ISSUE TITLE
Scambio forzato con un npc

### ISSUE THREAD

**Issue by Sidim1937** [fuji97/pokemon-xenoverse-tracker#187]
Ho parlato con la scienziata vicino alla palestra del Campus Acero. Alla scelta del pokemon mi si è chiuso il gioco (il pc che uso per giocare è un po' lento, mi capita abbastanza spesso) salvando in automatico. Quando ho ricaricato il salvataggio, nonostante non avessi il pokemon richiesto, lo scambio è partito in automatico e mi ha scambiato il quinto pokemon che avevo in squadra (Farrowl) per Chigami. Inoltre parlando nuovamente con l'npc, mi chiede di nuovo se voglio scambiare (al quale ho immediatamente chiuso il gioco per evitare di scambiare un altro pokemon).

**Comment by fabstarkey** [comment]
questo purtroppo è dovuto al tuo computer che avrà causato qualche problema bloccandosi,
visto che molte altre persone sono riuscite a scambiare tranquillamente!
