### ISSUE TITLE
Bug che ho riscontrato e consigli. per favore leggetelo

### ISSUE THREAD

**Issue by SHerluu** [fuji97/pokemon-xenoverse-tracker#190]
Complimenti  al team WEEDle per il fan-game, mi sto divertendo un sacco a scoprire i tutti fakemon e tutti i Pokémon X.

Qui elencherò alcuni bug che per ora ho riscontrato(ancora non ho finito tutta la parte 1).
1. Nella stanza Sharpedo, poco prima che iniziasse la lotta contro Sharpedo X uno script ha impiegato troppo tempo  a caricarsi di conseguenza il gioco si è riavviato. Poco prima che premessi invio per riprendere la partita è accaduto questo(leggete dove mi trovo).
![image](https://user-images.githubusercontent.com/31817777/30253259-eafb5c48-9681-11e7-8753-83e530b1936a.png)
2. Quando salvo la partita sul percorso 3 mi dice che salvo sul Monte Pico.
![image](https://user-images.githubusercontent.com/31817777/30253284-4b9ad952-9682-11e7-9cbb-d801a5caf585.png)
3. Quando si spacca una roccia sulla Grotta Ghiacciolo e inizia uno scontro l'ombra della roccia rimane per tutto il tempo, finché non si sconfigge il Pokémon selvatico, anche se l'ombra rimane ancora per qualche secondo dopo lo scontro, per poi scomparire definitivamente.
![image](https://user-images.githubusercontent.com/31817777/30253337-1df04860-9683-11e7-8565-4ff1d8feb2c2.png)Infatti se notate bene si vede un quadratino nero, che sarebbe lo sfondo nero che appare prima della lotta.
4. Quando si può usare il Denerium z (non mi ricorda come si chiama) sul masso, e si esce dalla grotta Ghiacciolo diventi invisibile per pochi secondi e si sente il rumore di quando vai a sbattere contro qualcosa.
![image](https://user-images.githubusercontent.com/31817777/30253386-26079372-9684-11e7-98b0-7a638505d6af.png)
5. In quasi tutte le scale del Monte Ghiacciolo, che ti permettono di scendere, si può notare,
se si sta attenti,  che rimane una parte dell'ombra del protagonista(non ho fatto altri screenshot, perché
non riesco più a cliccare al momento giusto il pulsante per fare lo screenshot).
![image](https://user-images.githubusercontent.com/31817777/30253784-4fb984ac-968c-11e7-87e7-afae37ff7722.png) Lo so che forse questo è un dettaglio che non avrà notato quasi nessuno, però visto che ci mettete  tanto impegno e cuore in questo progetto volevo farvi notare anche questa cosa.
6. Questo non so se definirlo un vero e proprio bug, visto che si è risolto da solo, comunque lo segnalo lo stesso. Il primo Tranpille che ho catturato è stato quello fuoco coleottero, successivamente ho catturato quello coleottero spettro e andando sul Pokèdex ho notato  che ci fosse Tranpille Gengar al posto di Tranpille Chiarizard, ma andando a leggere la sua descrizione appariva l' immagine  di Tranpille Chiarizard. Il motivo per cui dubito che questo non sia un bug è per il fatto che il giorno successivo il problema si era risolto da solo.
8. Queste sono delle domande: esistono delle cartelle da cui possiamo recuperare i nostri vecchi salvataggi? Se non esistono le aggiungerete in futuro? Creerete una patch in cui potremmo personalizzare ampliamente il nostro personaggio? I Pokémon selvatici e non avranno, oltre alla solita barra della vita, una percentuale per rendere le lotte più "tecniche"?

Consigli
Aggiungete la possibilità di velocizzare il gioco, come se fosse un emulatore, perché in alcuni casi, come l'inizio o certe lotte, il tutto è molto lento (es. puppillon di liv 9 contro un Gastly che utilizza malosguardo. Vi  ricordo che a questo livello Puppillon come mossa per infliggere danno ha solo botta. Aggiungiamoci che il computer è lentissimo a caricare le animazioni...insomma avete capito).
Aggiungete la possibilità di dare i  soprannomi ai Pokémon dal Box,  perché onestamente aspettare di arrivare ad un certo posto per cambiare un nome mi scoccia e non poco.
Aggiungete al PokeWES la possibilità di ascoltare le musiche del gioco nel momento in cui si  sbloccano(es. quando entri nel centro Pokémon si sblocca la sua musica e se vuoi, la puoi riascoltare  tutte le  volte che vuoi dal PokeWES).
Aggiungete la possibilità di creare più di una partita.
Aggiungete nelle opzioni la possibilità di selezionare la difficoltà, e modificare il suono e le musiche di gioco(se non erro Starkey aveva già confermato la difficoltà selezionabile e anche l'online).
Spero con tutto il cuore che mi risponderete e prenderete in considerazione tutto quello che vi ho detto.
Lo so che dovevo dire tutte questo cose in più messaggi, però se avessi fatto così non avrei finito mai.
Un abbraccio da un tizio  a caso xD.
P.s. Se voglio esprimere una mia opinione dopo aver finito la parte1 posso sempre esprimerla qua? Spero che il mio papiro vi sia piaciuto xD
(Scusate se forse ci saranno degli errori grammaticali e ortografici gravi, ma sono quasi da tre ore che sto scrivendo ininterrottamente e sono le tre di notte).

**Comment by SHerluu** [comment]
L'episodio M che fine ha fatto?

**Comment by fabstarkey** [comment]
sei molto attento! grazie per le segnalazioni ma questi non possono praticamente essere definiti bug, i tranpille possono variare sul pokedex essendo forme alternative e come avrai notato dall'opzione forme, sarà tutto disponibile nella parte 2. Grazie comunque!
