### ISSUE TITLE
Non so come andare avanti nel gioco nell' "oasi cocente"

### ISSUE THREAD

**Issue by Patrickso99** [fuji97/pokemon-xenoverse-tracker#191]
Sono bloccato qui, non so come andare avanti nel gioco, perfavore aiutatemi

![cattura](https://user-images.githubusercontent.com/31846151/30267522-25025354-96e3-11e7-97ba-1bb80daec75d.PNG)

**Comment by fabstarkey** [comment]
E' un errore che abbiamo corretto nella patch. Uscirà tra oggi e domani!

**Comment by Patrickso99** [comment]
Ti ringrazio infinitamente :)
