### ISSUE TITLE
bug volo all'arcipelago vodoo

### ISSUE THREAD

**Issue by alecope** [fuji97/pokemon-xenoverse-tracker#193]
![screenshot 2017-09-11 11 53 39](https://user-images.githubusercontent.com/31846943/30269294-a2160372-96e8-11e7-916f-a1e85860a011.png)
Volando all'arcipelago vodoo il gioco mostra il messaggio dell'evento di lapras per poi rimanere bloccato in quel punto

**Comment by fabstarkey** [comment]
corretto nella patch che uscirà a breve ;)
