### ISSUE TITLE
Musiche mancanti

### ISSUE THREAD

**Issue by Sburanga** [fuji97/pokemon-xenoverse-tracker#2]
Il gioco, fin dall'inizio, non presentava alcuna OST. Gli unici effetti sonori presenti sono quelli dati dai tasti premuti, dai versi dei pokemon, dall'uso degli strumenti e da alcune interazioni con l'ambiente (contatto col muro ad esempio, ma NON cura centro pokemon/Azzurra). Le musiche sembra siano state estratte tutte correttamente nella cartella Audio del programma. L'installazione di tutti i font, l'uso delle impostazioni consigliate (tramite "Risoluzione problemi compatibilità" di Windows 8) ed il far partire il gioco da amministratore non hanno risolto il problema, così come il reinstallarlo e neppure riscaricarlo da zero.

**Comment by fuji97** [comment]
Grazie per la segnalazione, questo errore è molto strano, ne teniamo in considerazione per la prossima release
