### ISSUE TITLE
Testi centro Pokemon

### ISSUE THREAD

**Issue by BestPlayerIta02** [fuji97/pokemon-xenoverse-tracker#205]
Non si vedono le scritte per scegliere se far curare o no i pokemon.
Comunque Bel Gioco!
![bug xenoverse 1](https://user-images.githubusercontent.com/31851294/30273974-a83fd760-96fb-11e7-9ac9-8041470e4ebd.JPG)

**Comment by REYBAN23** [comment]
per le scelte credo devi installare i font se non lo hai già fatto (quelli nella loro cartella)

**Comment by BestPlayerIta02** [comment]
Ha funzionato,grazie
