### ISSUE TITLE
Bug volo regno caramello

### ISSUE THREAD

**Issue by drbick** [fuji97/pokemon-xenoverse-tracker#223]
Molto semplicemente, una volta utilizzato volo per andare al regno caramello, compare solo una schermata nera. Posso muovermi, sento infatti i suoni del pg che sbatte su muri, ma non mi fa accedere a nulla (nemmeno al pkmn center dietro di me).

Edit: stesso problema con l'arcipelago vodoo, mi segnala che lapras vuole portarmi da qualche parte e si bugga in una schermata mezza nera

**Comment by Patrickso99** [comment]
Scusami, dove si ottiene "volo"????

**Comment by drbick** [comment]
Lo otterrai durante lo svolgimento della trama da un npc fondamentale, verso la fine. Dire di più sarebbe spoiler, in bocca al lupo

**Comment by Patrickso99** [comment]
E' che io sono bloccato all'oasi (dove c'è Gengar) e quelli di Weedle mi hanno detto che il bug lo hanno risolto e quindi fino a che non si risolve non posso andare avanti nel gioco :(

**Comment by Patrickso99** [comment]
Volo lo ottieni dopo l'oasi, vero? (perchè senò ho fatto tutto per niente ;( )


p.s. non sono ancora andato nel vulcano

**Comment by Patrickso99** [comment]
Il gioco lo hai già finito?

**Comment by drbick** [comment]
Gioco finito, sì. Se non parte l'evento di gengar, puoi solo aver pazienza e fare altro nel frattempo, come allenare la squadra! Volo è parecchio successivo alla bossfight con gengar, perciò niente allarmismi

**Comment by drbick** [comment]
Gioco finito, sì. Se non parte l'evento di gengar, puoi solo aver pazienza e fare altro nel frattempo, come allenare la squadra! Volo è parecchio successivo alla bossfight con gengar, perciò niente allarmismi

**Comment by Patrickso99** [comment]
Bon bon, mi bastava sapere che è molto dopo e che non me lo sono molto perso :D

**Comment by Patrickso99** [comment]
Non posso nemmeno livellarli perché sono bloccato in un punto in cui la guardia non mi fa tornare indietro e l'evento di Gengar non funziona :(

**Comment by Evyck** [comment]
ma voi avete sbloccato surf?
io, pur avendo sharpedo X in squadra, non posso andare nell'acqua...
consigli?
