### ISSUE TITLE
ALCUNI POKEMON EVOLVENDOSI NON IMPARANO PIù MOSSE

### ISSUE THREAD

**Issue by ANDREUCCIODAPERUGIA** [fuji97/pokemon-xenoverse-tracker#229]
ho fatto evolvere elekid x e non impara più nulla. trishout ogni volta per fargli imparare una mossa devo togliergli l'anello terrestre

**Comment by Patrickso99** [comment]
Come si evolve Elekid X????

**Comment by ems11** [comment]
A un certo punto arriva Ezio e ti porta da un albero/portale Xenoverse e ti dice che lì si evolvono i pokemon X, infatti se fai salire Elekid X di un livello in quell'area si evolverà.

**Comment by andrewrov** [comment]
A me Trishout pure con l'anello terrestre impara lo stesso delle mosse... (per ora ce l'ho al 39)

**Comment by Claus02** [comment]
@andrewrov Hai scaricato la patch?

**Comment by andrewrov** [comment]
Ho scaricato la patch, comunque ho scoperto che le mosse che mi imparava Trishout-T erano sbagliate (tipo Profumino -_- ) e avendolo al 39 e avendo saltato mosse molto importanti ho re-iniziato il gioco

**Comment by fabstarkey** [comment]
Aggiustato e tutto disponibile nella patch che uscirà a breve! :)
