### ISSUE TITLE
Bug Nave dopo Sig.Marino

### ISSUE THREAD

**Issue by Jurayax** [fuji97/pokemon-xenoverse-tracker#23]
![xenoverse](https://user-images.githubusercontent.com/31792783/30238604-3353fe7a-954a-11e7-995a-9dc82d8e3052.png)
 
Arrivato all'entrata della nave il personaggio sbanda a destra ed è impossibile farlo muovere in altre direzioni  (difatti si sente permanentemente il rumore di quando si va a sbattere) , mettendomi in una situazione di stallo in quell'esatto punto. 
Ho riavviato il gioco dopo aver salvato e mi ritrovo bloccato in quel punto .. Ora credo di dover ricominciare il gioco da capo , a meno che non abbiate un debugger o una cosa del genere .
Se può essere d'aiuto anche se il pg non si può muovere , il menù si può aprire e scorrere. 
Help me

**Comment by fuji97** [comment]
Segnalo, purtroppo non sono presenti debugger per gli utenti quindi o aspetti la prossima release o resetti il gioco. Quando capitate in bug simili evitate di salvare che potreste bloccarvi in questo modo
