### ISSUE TITLE
Butterfree Sprite Missing

### ISSUE THREAD

**Issue by AntoIannaccone** [fuji97/pokemon-xenoverse-tracker#231]
![o](https://user-images.githubusercontent.com/20368637/30291914-9c22a7c6-9734-11e7-9f80-5a01bb242286.jpg)

**Comment by JeckX** [comment]
Stesso problema, Butterfree invisibile...

![cattura](https://user-images.githubusercontent.com/31808466/30352711-d4a6cf4e-9821-11e7-8a02-c7cde563e651.JPG)
