### ISSUE TITLE
Crash al Campus Acero

### ISSUE THREAD

**Issue by LuckyGhast** [fuji97/pokemon-xenoverse-tracker#236]
In pratica ero al Campus, ho parlato col giocatore di baseball nella piazzetta ed il gioco mi crasha dicendomi che c'è un errore nel codice, ma salvandomi i dati.
Così riavvio il gioco ma premendo "Continua" mi crasha appena vedo un frame.
Questo è ciò che mi compare:

Script 'Interpreter' line 276: RuntimeError occured.

Script error whithin event 14, map 34 (Campus Acero):
Exception: NoMethodError
Message: Section212:796:in fbDispose'undefined method dispose' for nil:NilClass
***Full Script:
fbDispose

Interpreter:243:in pbExecuteScript'
(eval):1:in pbExecuteScript'
Interpreter:1606:in eval'
Interpreter:243:in pbExecuteScript'
Interpreter:1606:in command_355'
Interpreter:494:in execute_command'
Interpreter:193:in update'
Interpreter:106:in loop'
Interpreter:198:in update'
Scene_Map:103:in zer0_choice_window_upd'

**Comment by LeonidaXX1** [comment]
Nella piazzetta del campus se non sbaglio c'è una studentessa che cammina in tondo... Forse è lei il problema. Credo che il gioco non riesca a salvare correttamente quando gli npc sono in movimento. Anch'io ho avuto questo problema e riflettendoci l'npc che avevo davanti al momento del salvataggio si muoveva, era il primo sciatore che trovi al percorso 3. Visto che avevo iniziato da poco il gioco ho deciso di ricominciarlo e da allora salvo solo nei posti dove sto solo io o con npc che non fanno nemmeno un passo... A te è capitato che sei più avanti nell'avventura, spero che in questa patch o nella prossima ti risolvino il problema perché mi spiacerebbe se dovessi ricominciare da capo come è accaduto a me

**Comment by Espo27** [comment]
anch'io come te ho lo stesso problema, ma a me succede davanti il secondo capopalestra e non mi sembra ci sia qualche npc che si muova. in piu non so per quale motivo si è salvato da solo il gioco quindi sono in un loop continuo di crash

**Comment by LuckyGhast** [comment]
Infatti la cosa che non mi torna è che prima di crashare mi è venuta la finestra dei dialoghi, mi è venuto scritto:"Errore di codice", o qualcosa del genere e poi mi ha salvato automaticamente.

**Comment by SHerluu** [comment]
Anche a me è successo,  prima con Gennaro Bullo, poi con il secondo allenatore del percorso 4, che si trova sul ponte. Il crash è causato sempre da uno script che impiega troppo tempo  a caricarsi, di conseguenza salva il gioco. Il salvataggio, dopo aver premuto continua, ti porta davanti all' allenatore che devi sfidare  e pochi secondi dopo, senza premere alcun pulsante, fa crashare il gioco 
Ecco uno screenshot del crash del fan-game:
 
![image](https://user-images.githubusercontent.com/31817777/30329665-3a9f237c-97d3-11e7-8e01-88a1a9e2d0bc.png)
Spero veramente col cuore che sia un problema dei nostri computer.

**Comment by SHerluu** [comment]
*spero veramente che non sia un problema dei nostri computer.

**Comment by Espo27** [comment]
e quindi l'unica cosa che posso fare é ricominciare?


2017-09-12 17:11 GMT+02:00 SHerluu <notifications@github.com>:

**Comment by SHerluu** [comment]
L'unica soluzione per evitare di perdere tutto è quella di provare a cercare un cartella con i nostri vecchi salvataggi. Non voglio offendere Luckyghast, ma cambia il nome del post specificando con chi  avviene il crash, altrimenti il team WEEDle penserà che si tratterà del crash del centro Pokemon di Ludopoli.

**Comment by SHerluu** [comment]
Espo27 onestamente non vedo altre soluzioni (tranne quella che ho detto nel mio precedente commento). Ora vado a scaricarmi la patch 1.0.1 e  per una volta spero  che mi ricapiti  questo crash del gioco,  per vedere se hanno risolto il problema. 
P.S. Questa è la terza volta che riinizio il gioco.

**Comment by LuckyGhast** [comment]
A me con la patch ha ripreso a funzionar bene, non so voi.

**Comment by SHerluu** [comment]
Io ho fatto nuova partita...

**Comment by Espo27** [comment]
scusa se te lo chiedo, ma dove potrei trovare la cartella dei vecchi
salvataggi? e se la trovassi cosa dovrei fare?


Il giorno 13 settembre 2017 12:09, SHerluu <notifications@github.com> ha
scritto:

**Comment by Espo27** [comment]
dove la trovo la patch? e come hai fatto?


2017-09-13 17:43 GMT+02:00 SHerluu <notifications@github.com>:

**Comment by LeonidaXX1** [comment]
Il salvataggio sta in C/Utenti/Utente/Partite salvate, dove "Utente" è la cartella che si chiama come il nickname con cui accedi al pc. Purtroppo non credo che ci siano salvataggi precedenti, si tratta di una sola cartella di salvataggio che viene sovrascritta con dei nuovi dati ogni volta che salvi.

**Comment by Espo27** [comment]
ok grazie

Il giorno 13 settembre 2017 18:46, LeonidaXX1 <notifications@github.com> ha
scritto:

**Comment by SHerluu** [comment]
Hai  trovato la patch Espo27?

**Comment by Espo27** [comment]
si ma per ora non è disponibile, devo aspettare che esca

2017-09-14 9:09 GMT+02:00 SHerluu <notifications@github.com>:
