### ISSUE TITLE
Informazioni su Evento Gengar

### ISSUE THREAD

**Issue by Kyuzzinoh** [fuji97/pokemon-xenoverse-tracker#237]
Al mio primo tentativo l'evento Gengar è partito senza alcun problema e fino a qui tutto apposto, dato che non riuscivo a catturarlo ho deciso di riavviare il gioco, questa volta però, ho salvato dopo l'incontro di Joele e l'evento non è partito. Possibile che il salvataggio sia la causa del bug?

**Comment by fabstarkey** [comment]
non è possibile catturare gengar!
