### ISSUE TITLE
viva il follow

### ISSUE THREAD

**Issue by Falco97** [fuji97/pokemon-xenoverse-tracker#243]
![bug epico](https://user-images.githubusercontent.com/31868226/30299830-dcb80a02-9751-11e7-9a88-3b5a9c8d5aa9.PNG)

non dicevate che non c'era il follow. Io non so come lo ho trovato

**Comment by fabstarkey** [comment]
Aggiustato e tutto disponibile nella patch che uscirà a breve! :)

**Comment by Falco97** [comment]
Grazie mille strakey sei un grande stimo tutto il team.
