### ISSUE TITLE
Salvataggio online

### ISSUE THREAD

**Issue by andrewrov** [fuji97/pokemon-xenoverse-tracker#244]
Non sarebbe male come implementazione futura di poter gestire un username/password per poter giocare (o per salvare il profilo online), in modo tale da rendere più facile l'accesso da piattaforme differenti e, con l'aggiunta della versione android, si potrebbe addirittura portare il salvataggio pc sul proprio cellulare...

**Comment by fabstarkey** [comment]
vediamo di farlo!
