### ISSUE TITLE
persone invisibili, pokemon non catturabili e centri pokemon

### ISSUE THREAD

**Issue by Obscurlo** [fuji97/pokemon-xenoverse-tracker#246]
Dal titolo si dovrebbe capire ma i centri pokemon non hanno la grafica interna, nessun problema con gli npc, se non per il classico crash già riportato da altri.
 Alcuni npc in città non si vedono, l'unica cosa visibile sono le ombre, e dopo aver battuto la terza palestra non posso più catturare pokemon. (ps gioco fantastico, complimentoni avete veramente surclassato anche la più rosea aspettativa, non ditelo a nintendo ma quando ho ripreso il gioco di carte online cercavo Herchinsect XD)

**Comment by fabstarkey** [comment]
riscarica il gioco ed eseguilo come amministratore, il pc non ti legge dei file
