### ISSUE TITLE
Bug Bosco Filante & Tranpille

### ISSUE THREAD

**Issue by theyangs96** [fuji97/pokemon-xenoverse-tracker#248]
Dopo l'evento di Galvantula X gli oggetti si resettano (puoi raccoglierli 2 volte)

Tranpille Heracross è di tipo coleottero/fuoco

**Comment by Latenzo** [comment]
Spero si possa aggiungere un bug legato allo stesso luogo anche in un commento...

Gli alberi dell'evento di Galvantula sono trapassabili...

**Comment by fabstarkey** [comment]
Aggiustato e tutto disponibile nella patch che uscirà a breve! :)
