### ISSUE TITLE
errore all'avvio del gioco

### ISSUE THREAD

**Issue by Noruxen** [fuji97/pokemon-xenoverse-tracker#25]
![immagine](https://user-images.githubusercontent.com/31793552/30238777-3537d898-954e-11e7-8f52-841df9bcbe97.png)

aiutatemi pls

**Comment by xWiFi31** [comment]
prova ad avviarlo come amministratore

**Comment by Noruxen** [comment]
provato, non vaç_ç

**Comment by blackbluestyle** [comment]
Anche a me dà questo errore pls rispondi weedle

**Comment by Noruxen** [comment]
io continuo a non poter giocare

**Comment by blackbluestyle** [comment]
Anch'io spero che rispondano per questo problema

**Comment by blackbluestyle** [comment]
Mi è successa la stessa cosa con mirror edge catalyst

**Comment by fuji97** [comment]
Molto strano, avete antivirus o firewall particolari attivi

**Comment by Noruxen** [comment]
ho provato con anti virus e firewall disattivati ma niente, ho provato a riscaricare più volte e provato a istallare i font ma nulla

**Comment by blackbluestyle** [comment]
Rispondeteeeeee pls😭😭😭😭😭😭

**Comment by Noruxen** [comment]
Black calmati, sono pienissimo di lavoro è normale. Riposati che hanno comunque annunciato un patch p

**Comment by fuji97** [comment]
Andiamo a tentativi, provate a [disattivare il DEP](http://www.thewindowsclub.com/disable-data-execution-prevention)

**Comment by MarcoCinque55** [comment]
Disattivando il DEP è partito a me

**Comment by fuji97** [comment]
Ok, allora credo sia quello, lo aggiungo alle FAQ, se avete altri problemi scrivetelo sempre in questo post grazie

**Comment by Noruxen** [comment]
perdonami Fuji ma nemmeno disattivando il DEP va, non c'è bisogno che rispondi aspetto magari una la prossima versione, magari quella va
