### ISSUE TITLE
Errore Ludopoli (NO CENTRO PKM)

### ISSUE THREAD

**Issue by tonynart** [fuji97/pokemon-xenoverse-tracker#252]
Ho riscontrato questo errore che non mi permette di andare avanti nella storia. 
Uscito dal centro Pokémon di Ludopoli, e assistito alla scenetta con il fuoco, ecco che crasha il tutto restituendomi schermo nero e una finestra di log. Vi allego uno screen:
![screen](https://user-images.githubusercontent.com/21858752/30315838-82854118-97a5-11e7-8010-e235a6454432.jpg)
Da premettere che ho avviato il tutto come amministratore e l'errore persiste, ho anche seguito il suggerimento postato sotto il video YouTube spuntando "esegui come amministratore" dalle proprietà di Xenoverse, ma non cambia minimamente nulla. Spero possiate risolvere in tempi brevi :)

**Comment by fabstarkey** [comment]
prova a riscaricarlo, i dati non li perdi !

**Comment by tonynart** [comment]
con la patch 1.0.1 si è risolto tutto, almeno per quanto riguarda questo errore ;)
