### ISSUE TITLE
ogni volta che si entra nel CENTRO PKMN e si ricaricano i pkmn escce questo avviso e crasha

### ISSUE THREAD

**Issue by VOICE97** [fuji97/pokemon-xenoverse-tracker#253]
Script Interpreter'  line 276:  RuntimeError occurred.  Script error within event 1,  map 30(Centro Pokémon).  Exception:  Errno:  EACCES Message:  Section182:49:in 'delete' Permission denied Graphics/Characters/Healing balls left. ***Full script:  MakeHealingBallGraphics.new Interpreter:243:in pbExecuteScript HealingBall 49:in initialize' (eval)  1:in new(eval)  1:in pbExecuteScript Interpreter:  1606 in eval Interpreter:243 in pbExecuteScript Interpreter 1606 in command 355 Interpreter 494 in execute command'  Interpreter 193 in update Interpreter 106 in loop

**Comment by varola** [comment]
Avvia il gioco come amministratore

**Comment by Achy77** [comment]
succedeva anche a me e avviando come amministratore la cosa non succede più .. solo che non si leggono le scritte si e no nelle scelte solo una barra gialla e una nera.. ;)
