### ISSUE TITLE
Efficacia pokemon

### ISSUE THREAD

**Issue by OmegaHarley** [fuji97/pokemon-xenoverse-tracker#254]
Druddigon nella palestra Cannella non subisce danno superefficacie da parte di mosse ti tipo drago
Mossa usata "Ira di Drago" da Gyarados

**Comment by varola** [comment]
Ira di drago toglie 40 PS a qualunque pokemon, il fatto che non esce la scritta "superefficacie" è giusto

**Comment by OmegaHarley** [comment]
Scusate allora errore mio
