### ISSUE TITLE
Starter e pokemon selvatici

### ISSUE THREAD

**Issue by napoletano88** [fuji97/pokemon-xenoverse-tracker#257]
Salve ho iniziato l'avventura e non mi compare lo starter e nessun pokemon nell'erba alta, già subito dopo l'incontro con nonna Lea. Non posso nemmeno vedere il pokemon che la mamma mi ha appena dato... Grazie mille
![immagine](https://user-images.githubusercontent.com/31884370/30318631-f1502236-97ad-11e7-880b-1a93b5bf2282.png)

**Comment by fabstarkey** [comment]
ricomincia il gioco e riscaricalo
