### ISSUE TITLE
Borgo Mela Centro Pokémon

### ISSUE THREAD

**Issue by Latenzo** [fuji97/pokemon-xenoverse-tracker#258]
Entrato nel Centro Pokémon a Borgo Mela parte uno script dove l'infermiera Joy dice di stare attento a non so cosa, il problema è che parla al vuoto dato che te sei ancora sulla soglia della porta...

**Comment by fabstarkey** [comment]
Esegui il pc come amminsitratore

**Comment by Latenzo** [comment]
Già avviato come amministratore.

Il 16/set/2017 02:51, fabstarkey <notifications@github.com> ha scritto:

Esegui il pc come amminsitratore
