### ISSUE TITLE
Crash all'apertura della partita(problema con il pokemon che ti segue)

### ISSUE THREAD

**Issue by xWiFi31** [fuji97/pokemon-xenoverse-tracker#26]
Per Ripetere il bug: Prendere l'oggetto dal pokemon, salvare, far crashare il gioco. Ora ogni volta che riapro il salvataggio, il gioco crasha.
Se parlo con il pokemon dietro, la prima volta mi darà un oggetto, ma alla seconda il gioco crasha. Ho provato a reinstallarlo e ad avviarlo come amministratore.
![a](https://user-images.githubusercontent.com/31794464/30238963-56bce5d6-9552-11e7-888b-400f5296983d.PNG)
Come primo pokemon ho Sharpedo X. E prima di crashare, si sente il suono di elekid(che ho nella squadra)

**Comment by fuji97** [comment]
Il Follow me non dovrebbe esistere, cancella manualmente il salvataggio
