### ISSUE TITLE
Non trovo il pokedex

### ISSUE THREAD

**Issue by TommasoRusso23** [fuji97/pokemon-xenoverse-tracker#261]
sapete dirmi dove si trova il pokedex e se si trova nella borsa?

**Comment by varola** [comment]
È nel pokewes

**Comment by TommasoRusso23** [comment]
chi te lo da sto pokewes?????

**Comment by Patrickso99** [comment]
laboratorio all'inizio del gioco

**Comment by Patrickso99** [comment]
parla con tutti quelli dentro e sicuramente uno te lo darà
