### ISSUE TITLE
Bug Oasi Cocente 

### ISSUE THREAD

**Issue by zioteto** [fuji97/pokemon-xenoverse-tracker#265]
![oasi cocente](https://user-images.githubusercontent.com/31824841/30320960-a930600e-97b4-11e7-8bbf-0fb46aaf3d3d.png)
Si può salire passando attraverso le rocce, anche nella zona non accessibile. Inoltre sono riuscito a prendere l'oggetto (velopuro) anche se ci sono tutte le guardie a bloccare l'accesso...

**Comment by fabstarkey** [comment]
Aggiustato e tutto disponibile nella patch che uscirà a breve! :)
