### ISSUE TITLE
Regole da aggiornare

### ISSUE THREAD

**Issue by KetsubanZero** [fuji97/pokemon-xenoverse-tracker#267]
Nonostante il gioco sia aggiornato con mosse e pokemon di 7a generazione, utilizza ancora le regole della 5a generazione, nella versione completa, sarebbe bello avere le regole aggiornate alla settima generazione con i tipi elettro immuni alla paralisi e i tipi erba immuni alle polveri

**Comment by onthedam** [comment]
Q8

**Comment by fabstarkey** [comment]
il gioco è con le regole di 5 gen ;)
