### ISSUE TITLE
DOVE è IL MIO SCALEON 

### ISSUE THREAD

**Issue by ettorre97** [fuji97/pokemon-xenoverse-tracker#268]
come scritto nel titolo e sparito il mio scaleon dal team,era presente fino alla fine... Dopo i titoli di coda ho aperto il menu e sono andato su pokemon scoprendo che il mio pokemon era sparito, ho provato a utilizare il volo e ho visto che lo scaleon che appariva non era un ologramma.... magari ho perso dei passaggi ma io lo rivoglio nel mio team. per il resto nulla di rilevante oltre ad un lag continuo dopo aver sconfitto gengar x

**Comment by varola** [comment]
Ho avuto lo stesso problema, ma è gia stato segnalato quindi provvederanno a risolvere. Il bug è dovuto dal che durante la battaglia oleandro ti da il suo di scaleon, probabilmente nel momento in cui questo viene tolto dal team anche altri scaleon presenti nella squadra si eliminano. Per ora poi sviare al bug riprendendo da un salvataggio precedente alla battaglia finale e mettere scaleon nel box

**Comment by ettorre97** [comment]
grazie del suggerimento, anche se non ho idea di dove andare a recuperare i salvataggi, se lo sai mi faresti un favore enorme se no attenderò con pazienza che venga risolto

**Comment by varola** [comment]
Io non avevo salvato e perciò mi è bastato riavviare, per recuperare i vecchi file di salvataggio non saprei

**Comment by Armasus** [comment]
anche a me è successo :(

**Comment by fabstarkey** [comment]
Aggiustato e tutto disponibile nella patch che uscirà a breve! :)
