### ISSUE TITLE
Un po' di confusione tra chi e chi

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#269]
Due bug che ho notato riguardo a chi attribuire l'effetto di una mossa e negli oggetti dati e tolti ai Pokémon. Il primo, quando uso Parassiseme, il mio Pokémon recupera PS e quello avversario ne perde ma nella descrizione dell'effetto, paradossalmente, esce scritto che a recuperare PS è l'avversario! E poi il secondo, quando tolgo uno strumento ad un Pokémon, dovrebbe uscir scritto, ad esempio, "Ricevi Mirino da Farrowl", invece compare "Farrowl riceve Mirino". La descrizione è praticamente identica a quando lo strumento lo riceve effettivamente, solo che in questo caso la frase continua dicendo "Farrowl riceve Mirino da tenere". Lo so, sono due bug di poco conto rispetto a qualcun altro, risolvete prima quelli urgenti ma non dimenticate quanto ho scritto!

**Comment by fabstarkey** [comment]
Aggiustato e tutto disponibile nella patch che uscirà a breve! :)
