### ISSUE TITLE
non mi estrae il gioco

### ISSUE THREAD

**Issue by teckentech** [fuji97/pokemon-xenoverse-tracker#27]
in poche parole non mi estrae il gioco durante il download ho provato a scaricarlo sia nel la memoria interna sia esterna ma non cambia nulla
![error](https://user-images.githubusercontent.com/31789748/30239017-854040e6-9553-11e7-83df-8a6dde07f9ca.PNG)

**Comment by fuji97** [comment]
Non creare segnalazioni multiple
