### ISSUE TITLE
Suggerimento per lo zainetto

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#271]
Visto che ci avete reso la vita un po' più facile grazie al Self-Chansey, mi chiedo se potreste riorganizzare il modo, a mio avviso vecchio, di distribuire le tasche dello zaino. Le comodità per noi giocatori sono un fattore che faranno la fortuna di Xenoverse. Ecco, penso che potreste differenziarvi dai giochi Pokémon tradizionali anche in questo. Propongo un menu a scelta multipla in cui è possibile selezionare la tasca che serve usando tutti e quattro i tasti direzionali, e magari a lato ci lascerei l'immagine dello zaino con la tasca del momento evidenziata in rosso. Si potrebbe premere Invio e si accede alla tasca. Ho sempre trovato fastidioso dovermi muovere a sinistra e destra 4-5 volte per trovare una tasca. Per quanto abbia trovato delle scorciatoie (usare sinistra anziché destra e viceversa) rimane comunque un problema. Ad esempio io mi posiziono sempre sulla tasca Strumenti perché la uso di più ma mi servono anche le Bacche e, sia che vada a destra che vada a sinistra, sempre lontane un miglio stanno 'ste bacche.

**Comment by onthedam** [comment]
Mi accodo a questo post perché non è un bug ma un consiglio riguardante sempre lo zaino...

- se "possibile" cambiare i colori del menù dello zaino perché quando si è sopra uno strumento si fa (almeno io) fatica a leggere cosa si è selezionato.

- dare la possibilità di ordinare gli strumenti, in modo che si possano sistemare i più utili in alto alla propria tasca (ad esempio i repellenti tra gli strumenti, le pozioni tra i rimedi, l'amo tra gli strumenti base...). Una via per ordinarli c'è, è usare il pc strumenti, ma è veramente scomoda

Buon lavoro e grazie ancora per il gioco

**Comment by fabstarkey** [comment]
ci proveremo :)
