### ISSUE TITLE
Errore Percorso 8

### ISSUE THREAD

**Issue by zioteto** [fuji97/pokemon-xenoverse-tracker#272]
![percorso 8](https://user-images.githubusercontent.com/31824841/30323761-bd10098a-97be-11e7-9355-a10b29ea6184.png)
Fine percorso 8, entrata grotta per Rocca Draconica: Perché entrare normalmente quando si può entrare da sopra con un bel tuffo a candela? XD

**Comment by DragonX93** [comment]
Lo stesso bug c'é anche all'entrata del corridoio roccioso

**Comment by fabstarkey** [comment]
grazie per la segnalazione!
