### ISSUE TITLE
Palestra numero 3

### ISSUE THREAD

**Issue by Joytonic** [fuji97/pokemon-xenoverse-tracker#276]
Mi trovo nella palestra numero 3. Dopo essere stato sconfitto da Druddigon, sono tornato al centro Pokemon, ho curato i pokemon e sono tornato alla palestra. Dopo aver avviato il dialogo afferma che ho già superato la prima prova e sconfitto Druddigon.

**Comment by fabstarkey** [comment]
Aggiustato e tutto disponibile nella patch che uscirà a breve! :)
