### ISSUE TITLE
Non ho il pokewes e sono all oasi cocente please aiuto

### ISSUE THREAD

**Issue by TommasoRusso23** [fuji97/pokemon-xenoverse-tracker#277]
allego la prova
![image](https://user-images.githubusercontent.com/31884811/30326010-52b15d88-97c7-11e7-8a7d-c2d72c67ab5f.png)

**Comment by odinoo** [comment]
Il gioco non ti "costringe" a prenderlo. Basta che torni indietro alla prima città e vai al laboratorio di Ezio

**Comment by TommasoRusso23** [comment]
*bestemmia in silenzio*
