### ISSUE TITLE
punti salute che  calano in maniera strana

### ISSUE THREAD

**Issue by Achy77** [fuji97/pokemon-xenoverse-tracker#279]
allora sto facendo le prime battaglie... percorso 1 e 2 e ho notato che quando un pokemon colpisce (sopratutto Sparkowl) fanno un danno di 3 (per dire) lo segna e poi mi leva ancora altri punti salute.... come se ci fosse un danno secondario o cose del genere 🗡 

mentre gioco aggiorno.. anche adesso mi succede con lo starter .. mi fa 3 danni poi quando è il mio turno ho più danni di 3...

grazie a tutti e buon lavoro (il vostro è un gran bel buon lavoro)

**Comment by fabstarkey** [comment]
grazie per la segnalazione!
