### ISSUE TITLE
Non posso continuare a giocare + abilità e mosse buggate

### ISSUE THREAD

**Issue by siamoacortodigrog** [fuji97/pokemon-xenoverse-tracker#280]
Dopo aver battuto la prima palestra, se vado a curarmi il gioco chrasha perché non riesce a visualizzare le icone delle pokéball nella macchinetta dell'infermiera Joy

Inoltre

La mossa pungiglione non fa aumentare l'attacco

L'abilità copricapo di tranpill non funziona, viene addormentato dalle polveri del capopalestra

**Comment by varola** [comment]
Per il crash devi avviare il gioco come amministratore

**Comment by aceggi** [comment]
Il gioco segue le regole della 5 gen quindi è normale che copricapo non protegga dalle polveri

**Comment by siamoacortodigrog** [comment]
Eh allora le descrizioni sono sbagliate. Perché nelle info del pokémon dice "protegge dalle polveri, da sabbia e da grandine"
