### ISSUE TITLE
Schermo Nero dopo sconfitta alla palestra Zucchero

### ISSUE THREAD

**Issue by Gabbo99** [fuji97/pokemon-xenoverse-tracker#281]
Dopo essere stato sconfitto alla palestra zucchero non riesco più a giocare, dato lo schermo completamente nero. Riesco ad aprire il menù ed il gioco va avanti, ma non vedo ciò che succede
Allego pic. per far capire
![xenoverse 12_09_2017 16_12_00](https://user-images.githubusercontent.com/31892820/30330390-3ba4f5ba-97d5-11e7-94f1-62e90857bbfc.png)

**Comment by fabstarkey** [comment]
prova a riscaricare ed eseguire il gioco come amministratore
