### ISSUE TITLE
Bug grafici Regno Caramello e Percorso 6

### ISSUE THREAD

**Issue by Piofox4** [fuji97/pokemon-xenoverse-tracker#283]
Percorso 6:
![xenoverse 12_09_2017 15_13_55](https://user-images.githubusercontent.com/31799861/30332901-d86a4c6e-97db-11e7-885a-dda712734fd9.png)
Regno Caramello:
![xenoverse 12_09_2017 15_15_29](https://user-images.githubusercontent.com/31799861/30332903-d86bb810-97db-11e7-8fd9-e56266297b6f.png)
![xenoverse 12_09_2017 15_15_44](https://user-images.githubusercontent.com/31799861/30332899-d869d324-97db-11e7-9776-d1657f81450c.png)
![xenoverse 12_09_2017 15_16_02](https://user-images.githubusercontent.com/31799861/30332905-d9c08830-97db-11e7-96c0-33834e310f4f.png)
![xenoverse 12_09_2017 15_16_18](https://user-images.githubusercontent.com/31799861/30332900-d86a6ece-97db-11e7-9673-0ac86bdbd596.png)
![xenoverse 12_09_2017 15_17_08](https://user-images.githubusercontent.com/31799861/30332902-d86aa38a-97db-11e7-89fe-2bd59434599d.png)

**Comment by fabstarkey** [comment]
grazie per la segnalazione!
