### ISSUE TITLE
Mosse buggate starter

### ISSUE THREAD

**Issue by LorasMastark** [fuji97/pokemon-xenoverse-tracker#284]
Tenendo lo starter in forma T non impara le sue mosse livellando. Impara mosse non legittime come Profumino o Parassiseme. Io parlo di Trishout ma penso valga anche per gli altri.

**Comment by Claus02** [comment]
Anche a me succede questo perchè da quando ho evoluto Trishout in forma T ad adesso che è  livello 40 non ha imparato neanche una mossa
