### ISSUE TITLE
2 TRISHOUT X MI INSEGUONO 

### ISSUE THREAD

**Issue by umbryy** [fuji97/pokemon-xenoverse-tracker#285]
PRATICAMENTE SE VADO A PARLARCI SONO 2 PERSONAGGI CHE HO INCONTRATO..
ALICE E JOELE.
![screnn 1](https://user-images.githubusercontent.com/31894426/30333390-84ad542c-97e5-11e7-8906-7eddbdc27279.PNG)

![screen 2](https://user-images.githubusercontent.com/31894426/30333398-89b2ff1c-97e5-11e7-97f2-5a4e8c379f45.PNG)

![screnn 3](https://user-images.githubusercontent.com/31894426/30333429-9b5db806-97e5-11e7-84e6-989f15887fcb.PNG)

**Comment by Kirino6533** [comment]
Pure io avevo sto bug con Shulong in teoria ti basta perdere contro un allenatore / pokemon per sbuggarti
