### ISSUE TITLE
Non mi fa caricare il mio salvataggio

### ISSUE THREAD

**Issue by Ghosttrick03** [fuji97/pokemon-xenoverse-tracker#287]
Quando provo a caricare il mio salvataggio mi crasha il gioco e mi appaiono due errori
![error 01](https://user-images.githubusercontent.com/31895001/30334200-2d19d330-97df-11e7-9bb3-8600dd18ac56.PNG)
![error 02](https://user-images.githubusercontent.com/31895001/30334207-2e93db16-97df-11e7-8003-e294e064fdd9.PNG)

**Comment by Ghosttrick03** [comment]
Vi prego rispondete! Non voglio cancellare il mio salvataggio!!

**Comment by fabstarkey** [comment]
hai i salvataggi corrotti, hai toccato qualcosa? prova a reinstallarlo
