### ISSUE TITLE
IMBOSSIBILITA' DI CATTURARE POKEMON NEL CORRIDOIO ROCCIOSO

### ISSUE THREAD

**Issue by Claus02** [fuji97/pokemon-xenoverse-tracker#289]
Con tutti i pokemon selvatici che trovo all'interno della grotta, quando uso una qualsiasi pokeball mi viene il messaggio che non possono essere catturati.
Per favore potreste risolvere? (Perché mi serve Diglett e non penso sia fatto apposta)

**Comment by LeonidaXX1** [comment]
Non è fatto apposta, capita con tutti i Pokémon e dovunque essi siano, non dipende dunque dal fatto che ti trovi nella grotta. Durante gli eventi del Regno Caramello è capitato a tutti di imbattersi in questo bug davvero importante perché Pokémon nasce con la sigla "Gotta catch'em all", questo bug annienta l'essenza stessa del gioco. Comunque lo hanno già risolto, siamo in attesa della patch.

**Comment by Claus02** [comment]
Benissimo grazie mille
