### ISSUE TITLE
Errore Dialogo + Errori Pokédex

### ISSUE THREAD

**Issue by MattPendragon** [fuji97/pokemon-xenoverse-tracker#29]
Nel laboratorio di Ezio uno scienziato dice che sta lavorando "alla veleno".
La funzione "cerca" nel pokédex non è attivabile e non compare nessun messaggio che faccia riferimento alla possibilità di attivarla nella parte 2.
Bremand non compare nel pokédex nonostante l'abbia catturato.

A parte queste piccolezze il gioco mi sta piacendo molto (le chicche di alcuni dialoghi sono geniali ahahah )

**Comment by fuji97** [comment]
Il primo non è un bug, ma una citazione a AGSoldier, uno dei dev che è diventato famoso perché "deve lavorare alla veleno", lunga storia.
Questo lo segniamo e vi aggiorniamo
Per Bremand è già stato segnalato

**Comment by fabstarkey** [comment]
corretto tutto.
