### ISSUE TITLE
È martedì e deve ancora uscire la patch del Day One

### ISSUE THREAD

**Issue by AlberoSaggio** [fuji97/pokemon-xenoverse-tracker#290]
Come da titolo, dopo 5 giorni ancora non è uscita la patch del D1

**Comment by fuji97** [comment]
Eh, infatti oggi è il day one della patch, niente di sbagliato mi dicono dalla regia

**Comment by andrewrov** [comment]
Giusto per evitare di controllare ogni 5 secondi se sia uscita una patch o meno, lasciare un comunicato che avvisa un'orario/un giorno per la patch?

**Comment by Magician-red-98** [comment]
Dove si può controllare l'eventuale arrivo della patch (scusate l'ignoranza)

**Comment by deku9** [comment]
Scusate l'ignoranza ma patch che vuol dire? Sarebbe l'aggiornamento volto a eliminare i bug che hanno creato problemi?

**Comment by Lorenz0203** [comment]
Dove si trovare codesta patch_ per favore

**Comment by Lorenz0203** [comment]
deku 9:Si
