### ISSUE TITLE
Non riesco a caricare i dati di salvataggio 

### ISSUE THREAD

**Issue by zepolino** [fuji97/pokemon-xenoverse-tracker#291]
![screenshot_1](https://user-images.githubusercontent.com/31896251/30335853-b1811f62-97e3-11e7-8b16-1544064a3392.png)
![screenshot_2](https://user-images.githubusercontent.com/31896251/30335854-b1add5ca-97e3-11e7-8928-d8c4f8e5f490.png)
come da screen quando provo ad entrare nel salvataggio mi esce questo bug, help?

**Comment by fabstarkey** [comment]
hai qualche problema di salvataggio, prova a reinstallarlo
