### ISSUE TITLE
Problema smistamento oggetti nelle tasche

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#292]
Premendo Z su uno strumento della tasca e poi premendo Invio su un altro strumento, si invertono di posto. Comodo, ma forse è meglio rimanere sulla classica funzione prevista nei giochi Pokémon tradizionali, cioè l'oggetto selezionato si posiziona fra altri due oggetti. Ad esempio, io nella tasca Rimedi ho, in ordine, Pozioni, Superpozioni e Iperpozioni. Se io raccolgo un'Iperpozione e non ce l'ho già nello zaino, mi finisce in fondo. Allora, se io faccio Z e poi clicco Invio in corrispondenza delle Superpozioni con l'intenzione che l'Iperpozione si posizioni sotto, ottengo che si cambiano il posto e le Superpozioni finiscono in fondo, quindi devo spostarle e metterò in fondo quello che viene dopo alle Iperpozioni, gli Eteri nel mio caso. Ritengo che sia più ottimale selezionare l'oggetto e, in maniera simile ai giochi targati Nintendo, far comparire una linea che si frappone fra gli oggetti, mandare su e giù la linea per centrare il punto esatto in cui sistemare l'oggetto e fare Invio. Se trovate che sia una soluzione migliore questo metodo di smistare gli oggetti, e per me lo è, vi sarei grato se lo implementaste nel gioco, perlomeno quello completo.

**Comment by fabstarkey** [comment]
Queste cose sono di essential e non le abbiamo scriptate noi, non possiamo fare niente purtroppo..cercheremo però di trovare una soluzione
