### ISSUE TITLE
Evoluzione bugbag

### ISSUE THREAD

**Issue by grouchality** [fuji97/pokemon-xenoverse-tracker#293]
Se l'evoluzione di bugbag fosse realmente settata al lv 30, nel mio caso non si avvia portando Bugbag al 31 contro Joele. 
Il tutto avviene in contemporanea col blocco delle catture e col bug della quest di Gengar X

**Comment by Coccio98** [comment]
Bugbag si evolve al 37

**Comment by grouchality** [comment]
perfetto grazie

**Comment by DragonX93** [comment]
Grazie dell'informazione anche io volevo saperlo... Ho bugbag al 35 e anche io avevo letto sulla wiki che l'evoluzione era al 30... e mi sembrava strano non succedesse nulla
