### ISSUE TITLE
Crash all'interno di la casa del cavaliere nel regno caramello 

### ISSUE THREAD

**Issue by Magician-red-98** [fuji97/pokemon-xenoverse-tracker#294]
Esplorando il regno caramello, entrai in una casa con all'interno un cavaliere del regno ed appena ci ho parlato mi comparse questa finestra sottostante. Facendo l'auto-salvataggio impostato ogni volta che ci sono errori nei codici, una volta riaperto il gioco me lo da come punto di salvataggio così da non darmi la benché minima possibilità di proseguire la mia esperienza di gioco riapparendo sempre questa finestra.
[
![cattura4](https://user-images.githubusercontent.com/31898003/30339081-27a3c1cc-97ee-11e7-8876-28f28f0ef662.JPG)
](url)

**Comment by fabstarkey** [comment]
non è un problema dovuto al gioco ma al tuo pc che non è riuscito a leggere il gioco e ha salvato per non perdere i dati, purtroppo può succedere, prova a riscaricare il gioco
