### ISSUE TITLE
Percorso 1: Come mai Mareep si paralizza?

### ISSUE THREAD

**Issue by C3li0** [fuji97/pokemon-xenoverse-tracker#295]
I pokemon tipo elettro, dalla sesta generazione in poi, non si potevano più paralizzare (né con mosse dirette ad es. Tuononda, né con abilità ad es. Statico: chiaramente vi sono casi particolari, come un ditto paralizzato che si trasforma in un pokemon elettro, ma finisce lì). Era un piccolo nerf.
Mareep ha attaccato un mio pokemon con Statico e si è paralizzato: è un errore o è semplicemente una meccanica di ricordo della terza/quarta/quinta generazione?
Ciao ciao!

**Comment by DartFeld92** [comment]
Il programma che stanno usando per sviluppare il gioco ha come base le meccaniche di 5 generazione.

**Comment by C3li0** [comment]
Ok, grazie! Un po di DPP non fa male, haha
