### ISSUE TITLE
Crash gioco quando curo i pokemon al centro pokemon

### ISSUE THREAD

**Issue by GabboMCPE** [fuji97/pokemon-xenoverse-tracker#296]
Dopo aver catturato il primo pokemon X se vado a curare i pokemon il gioco crasha. (ho provato 3 volte ma continua a venire) [https://imgur.com/a/OxBvl](url)

**Comment by DartFeld92** [comment]
Avvia il gioco con i diritti di amministrazione. Tasto destro sull'icona del gioco -> Proprietà -> Compatibilità -> Esegui questo programma come amministratore
