### ISSUE TITLE
Crash del gioco curando i pokémon al pkmn center

### ISSUE THREAD

**Issue by frances1307** [fuji97/pokemon-xenoverse-tracker#297]
Ero al primo pokemon center, a ludopoli, ho dato la conferma per farmi curare i pokemon e il gioco è crashato dandomi runtime error. 😭

**Comment by DartFeld92** [comment]
Avvia il gioco con i diritti di amministrazione. Tasto destro sull'icona del gioco -> Proprietà -> Compatibilità -> Esegui questo programma come amministratore

**Comment by frances1307** [comment]
Grazie, non ci avevo pensato ^^"
