### ISSUE TITLE
(Scusate l'ignoranza) Dove uscirà la patch per la correzione degli errori?

### ISSUE THREAD

**Issue by Magician-red-98** [fuji97/pokemon-xenoverse-tracker#298]
Tutto scritto nel titolo

**Comment by Lorenz0203** [comment]
Scusa tu che l hai capito, mi potresti dire come si fa, per favore

**Comment by Claus02** [comment]
Penso che weedle metta un video con il link della patch

**Comment by Lorenz0203** [comment]
ok grazie
Pero come l avete ottenuta
