### ISSUE TITLE
non visualizzo le lotte

### ISSUE THREAD

**Issue by lio12314** [fuji97/pokemon-xenoverse-tracker#3]
quando entro nell'erba per la prima volta dopo che parlo con la nonna ritorno indietro come se avessi combattuto ma invece non l'ho fatto. anche quando incontro un'allenatore parte il dialogo e musica ma niente scena di battaglia :(

**Comment by fuji97** [comment]
Molto strano, hai provato a reinstallare e fare nuovo gioco?
