### ISSUE TITLE
Non riesco più a catturare un qualsiasi pokemon

### ISSUE THREAD

**Issue by maciomicio** [fuji97/pokemon-xenoverse-tracker#300]
Dopo aver ottenuto la medaglia zucchero, quendo tento di lanciare una qualsiasi pokeball (ho provato solamente con: la mega ball,con la rete bal e con la sub ball) mi esce scritto "il pokemon non può essere catturato".

**Comment by Lorenz0203** [comment]
per via di un bug comune quasi a tutti che verra risolto da una pacth cioe quella cosa che eliminera i bug

**Comment by Claus02** [comment]
Mi succede la tua stessa identica cosa, sia nel corridoio roccioso che nel percorso 7 (sono arrrivato fino a li ma penso che sia dappertutto) speriamo che risolvino questo bug e non altri bug grafici che non incidono niente sul gioco, perchè non si può andare avanti se non puoi catturare nessun pokemon con nessuna pokeball

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
