### ISSUE TITLE
Backsprites giganti

### ISSUE THREAD

**Issue by DragonX93** [fuji97/pokemon-xenoverse-tracker#302]
![1505242856516314201505](https://user-images.githubusercontent.com/31856559/30343401-bef427b0-97fd-11e7-844e-ae0f6578ca38.jpg)
I back sprites di questi pokemon  (Harowl e Honchen) sono piuttosto grandi e coprono gran parte della schermata di battaglia (quello di Honchen va addirittura a coprire il pokemon avversario)
![20170912_205540](https://user-images.githubusercontent.com/31856559/30343588-4b8ee048-97fe-11e7-9118-1cb7b520afb8.jpg)

**Comment by fabstarkey** [comment]
correggermo in futuro! diciamo che abbiamo voluto lasciare le dimensioni reali dei pokemon
