### ISSUE TITLE
[BUG] Alberi calpestabili

### ISSUE THREAD

**Issue by emanueledomingo** [fuji97/pokemon-xenoverse-tracker#303]
Ciao a tutti, mi sono accorto di questo bug nel percorso 5, ovvero la possibilità di camminare sugli alberi.
![xeno](https://user-images.githubusercontent.com/11682323/30343986-b8651dee-97ff-11e7-82e2-f859f73b6b86.jpg)

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
