### ISSUE TITLE
Persone diventano starte

### ISSUE THREAD

**Issue by OwlolwO** [fuji97/pokemon-xenoverse-tracker#304]
Ogni missione dopo la terza palestra che include il "following" di qualche persona, fa diventare la persona il proprio starter. Allego esempio, prima dell'evento Gengar
![cattura](https://user-images.githubusercontent.com/31901580/30344213-a522904e-9800-11e7-9641-4b823edee594.PNG)

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
