### ISSUE TITLE
Lapras

### ISSUE THREAD

**Issue by Kirino6533** [fuji97/pokemon-xenoverse-tracker#307]
Se provi ad andare al arcipelago vodoo con volo ti viene scritto: ''Lapras vuole portarti da qualche parte'' dopo questa riga di testo l'unica cosa che sei in grado di vedere è un quarto di schermo, inoltre come sottofondo avrai solo la musica il rumore di quando sbatti contro i muri

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
