### ISSUE TITLE
Repellente non funziona

### ISSUE THREAD

**Issue by JeckX** [fuji97/pokemon-xenoverse-tracker#309]
Nella zona del corridoio roccioso, anche usando repellente, i pokemon continuano ad apparire normalmente.
Edit: fuori dalla grotta e nella prima parte continuano ad apparire pokemon, più avanti funziona correttamente.

**Comment by LeonidaXX1** [comment]
La descrizione del repellente recita che allontana i Pokémon selvatici "più deboli". Vuol dire che impedisce lo spawn di Pokémon di livello pari o inferiore a quello del primo Pokémon della tua squadra, ma quelli di livello superiore verranno comunque spawnati.

**Comment by JeckX** [comment]
Se è così, chiedo scusa, non ci ho mai fatto caso... Grazie per il chiarimento
