### ISSUE TITLE
Animazione mosse

### ISSUE THREAD

**Issue by Dade66cl** [fuji97/pokemon-xenoverse-tracker#31]
non so se è un bug o è fatto apposta cosi, alcune mosse hanno le stesse animazioni, esempio vocalizzo=graffio=ruggito invece braciere ha la propria animazione

**Comment by AlberoSaggio** [comment]
Purtroppo mettere le animazioni delle mosse con pokemon essential è un lavoro apocalittico, quindi per questa parte 1 ce ne sono poche condivise tra più mosse. Per la parte 2 ci impegneremo ad aggiungerne di ulteriori
