### ISSUE TITLE
Lotta in coppia ma il mio Pokémon combatte da solo

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#310]
Volevo far presente questa cosa che non so se sia un bug, ma certamente mi ha messo un po' in difficoltà. Ho concluso il combattimento con le due reclute nella grotta, è previsto un combattimento in coppia in cui io duello con Alice. Naturalmente lei ha tre Pokémon. Quando a lei glieli buttano giù tutti e tre, fa parte delle normali regole che io poi non possa usare il posto che lei lascia libero per metterci un mio Pokémon? In altre parole, dopo che tutti i suoi Pokémon sono stati sconfitti, il mio ha dovuto affrontare da solo gli altri Pokémon rimasti degli avversari, che però erano sempre due alla volta, finché non gli ho buttato giù il quinto e allora ne rimaneva uno solo a combattere. Quando combattevo in coppia nei giochi classici non mi è mai capitato di battere i Pokémon di uno solo dei miei sfidanti e quindi non ho idea se, quando ciò accade, quello sconfitto sta a guardare o è possibile cedere il suo posto vacante a qualche altro Pokémon dell'altro.

**Comment by fabstarkey** [comment]
hai mai giocato a pokemon? ahaha, è normale leonida :)
