### ISSUE TITLE
(Bug) Non viene presa in considerazione l'aumento di vita se affetti da stato BRUCIATO

### ISSUE THREAD

**Issue by loltag22** [fuji97/pokemon-xenoverse-tracker#311]
Mentre stavo affrontando Galvantula X, ho bruciato il pokemon e... visto che aveva anche aquanello beh si rimette la vita con acquanello, ma al momento del danno da scottatura la vita torna allo stato originale e viene sottratto quanto dovuto per la scottatura. (Annullando l'effetto di acquanello)
Non ho provato il VELENO, ma dovrebbe essere lo stesso.

**Comment by fabstarkey** [comment]
grazie per la segnalazione!
