### ISSUE TITLE
BUG NON POSSO CONTINUARE A GIOCARE, CAMPUS ACERO- PENSIONE 

### ISSUE THREAD

**Issue by maly96** [fuji97/pokemon-xenoverse-tracker#312]
Dopo aver sconfitto A e B uscendo dalla biblioteca e entrando nella pensione , il gioco mi dice che ci sono problemi nel codice e successivamente salva in automatico ... quello che succede dopo è questo 
![bug1](https://user-images.githubusercontent.com/31905724/30353968-e1277c3e-9829-11e7-8dab-36b1fbe6e4b8.png)
![bug2](https://user-images.githubusercontent.com/31905724/30353974-ed648b5e-9829-11e7-931f-c4e30c8ece8d.png)
quando ricarico il salvataggio succede questo : 
![pokemon bug](https://user-images.githubusercontent.com/31905724/30353991-0c91733e-982a-11e7-9845-85b504620c2a.png)
Vi ringrazio per il vostro lavoro , spero di continuare a giocare presto

**Comment by fabstarkey** [comment]
ciao! è un problema del tuo pc che non legge lo script. Prova a disinstallarlo e riscaricarlo (non perdi i dati) ed esegui come amministratori!

**Comment by maly96** [comment]
sono già amministratore
