### ISSUE TITLE
Vari bug dopo la patch

### ISSUE THREAD

**Issue by Natzkul** [fuji97/pokemon-xenoverse-tracker#313]
Per prima cosa una richieste, l'artwork di Harrowl si potrebbe abbassare leggermente per evitare di offuscare tutto il campo di gioco?

1) Le mura d'ingresso del Regno Caramello permettono una penetrazione sui lati, mi riferisco alla porta principale

2) Quando si usano le pokéball (le ball in generale) dopo aver lanciato la prima il menù non salva più l'ultima scelta quindi se si spamma il tasto "A" tirerà la prima ball che si ha nell'inventario, nel mio caso la Xeno quindi poco male

Grandi ragazzi continuate così avete fatto un lavoro fantastico

**Comment by fuji97** [comment]
Grazie per la segnalazione
