### ISSUE TITLE
Bug pokedex post patch

### ISSUE THREAD

**Issue by Kyran333** [fuji97/pokemon-xenoverse-tracker#314]
Dopo la patch nel pokedex ci sono i pokemon mancanti ma quando clicco su uno di loro(ho provato con puppilon)il gioco crasha col seguente errore.
![bug pkmn xenoverse](https://user-images.githubusercontent.com/31869377/30354390-a80fbc60-982c-11e7-8acd-4afdc4de11e0.PNG)

**Comment by fuji97** [comment]
Grazie per la segnalazione, vedremo di risolvere il prima possibile

**Comment by Kyran333** [comment]
Grazie a voi, buon lavoro

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
