### ISSUE TITLE
Crash v1.0.1 contro Druddigon

### ISSUE THREAD

**Issue by Aesier** [fuji97/pokemon-xenoverse-tracker#315]
Alla prima prova della terza palestra contro Druddigon, alla fine della battaglia (sia che vinca sia che perda) c'è l'animazione come se dovesse cominciare un'altra lotta e poi il gioco crasha.

**Comment by fuji97** [comment]
Grazie per la segnalazione, vedremo di risolvere il prima possibile, ci puoi passare lo screen dell'errore?

**Comment by Aesier** [comment]
![screenshot 1](https://user-images.githubusercontent.com/31907097/30355131-9c868194-9831-11e7-9a9b-07ca96d94cb2.png)

**Comment by cloud90** [comment]
a me ha dato errore diverso avendo perso lo scontro contro druddigon...
![1cattura](https://user-images.githubusercontent.com/9502612/30358512-38640948-9845-11e7-921c-3b202ff98af2.PNG)

**Comment by xZekro51** [comment]
Risolto, il fix verrà applicato con la prossima Patch.
