### ISSUE TITLE
Immagini Premier Ball e Rete Ball invertite 

### ISSUE THREAD

**Issue by SatoshiTales** [fuji97/pokemon-xenoverse-tracker#316]
Sia nel menu in battaglia che nel menu della borsa le immagini delle ball sono invertite. Questo da dopo la patch 1.0.1
![ball](https://user-images.githubusercontent.com/31908365/30356039-42cd3ce6-9837-11e7-8d87-83a9156294c2.png)

**Comment by fuji97** [comment]
Grazie per la segnalazione, piccola svista nel rinominare i nuovi file

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
