### ISSUE TITLE
Descrizione Pokedex Sandygast in inglese

### ISSUE THREAD

**Issue by SatoshiTales** [fuji97/pokemon-xenoverse-tracker#317]
La descrizione di Sandygast è ancora in inglese. Inoltre nella scelta del soprannome il nome del pokemon risulta spezzato perchè troppo lungo

![bug sandgast](https://user-images.githubusercontent.com/31908365/30356075-693ec1b0-9837-11e7-957e-982028bad651.png)

**Comment by fuji97** [comment]
Grazie per la segnalazione
