### ISSUE TITLE
Esercito di Starter che ti seguono

### ISSUE THREAD

**Issue by SatoshiTales** [fuji97/pokemon-xenoverse-tracker#318]
Arrivati all'oasi dove si trova Gengar, quando il soldato si unisce a te, oltre alla presenza fissa di Alice trasformata in starter, si aggiunge anche lui.

![bug persone](https://user-images.githubusercontent.com/31908365/30356682-9e8fca5a-983a-11e7-84d2-b28ae849d6d8.png)

**Comment by Kyran333** [comment]
Seguo, ho riscontrato lo stesso errore.

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
