### ISSUE TITLE
URGENTE, NON MI VA PIU' IL GIOCO DOPO LA PATCH

### ISSUE THREAD

**Issue by Patrickso99** [fuji97/pokemon-xenoverse-tracker#319]
Sulla schermata:
Continua
Nuovo gioco
Opzioni

Quando clicco su "continua" mi viene fuori questo messaggio :(

![cattura](https://user-images.githubusercontent.com/31846151/30360253-9914d28a-9850-11e7-977f-97c875d91b70.PNG)

e poi crasha...vi prego aiutatemi :(

p.s. (il gioco l'ho sempre eseguito come amministratore)

**Comment by fabstarkey** [comment]
aspetta la patch nuova che uscirà a breve.
