### ISSUE TITLE
Errori Pokedex

### ISSUE THREAD

**Issue by LorasMastark** [fuji97/pokemon-xenoverse-tracker#32]
1) La scritta "Pokédex regionale" a volte si sovrappone ai pulsanti "info-area-forme".
2) Catturando Bremand mi è apparsa la voce Pokédex di un fakemon uccello di tipo Spettro/Suono.
3) Lo scorrimento delle voci dei Pokémon nel Pokédex è davvero troppo lento, rende praticamente inutizzabile lo strumento.

**Comment by fuji97** [comment]
Per favore, create un diverso "Issue" per ogni errore e non metteteli assieme, comunque:
1) Ok, ce lo segniamo
2) Già segnalato
3) Non possiamo farci nulla noi, è un problema di base di Essentials
