### ISSUE TITLE
Problema centro pokémon

### ISSUE THREAD

**Issue by Giacos93** [fuji97/pokemon-xenoverse-tracker#320]
Ogni volta che entro in un centro pokémon lo trovo in questo stato.
![21586211_10210648645713465_801013832_n](https://user-images.githubusercontent.com/31915989/30364178-635b5fe8-9863-11e7-9f28-4ecca421d063.jpg)

**Comment by Sharyeeza** [comment]
Riscontro lo stesso problema che avevo anche prima della patch, centro pokemon completamente nero e alcuni personaggi "invisibili" di cui si vedono solo le ombre. Già seguito il #37 ma nessun cambiamento.

![1](https://user-images.githubusercontent.com/31808583/30367369-5ba3765e-986e-11e7-9b69-095fc8e3f2e6.jpg)
![2](https://user-images.githubusercontent.com/31808583/30367370-5ba6320e-986e-11e7-9312-7b5b27699fe8.jpg)

**Comment by fabstarkey** [comment]
avete scaricato male il gioco, eseguite anche come amministratori!

**Comment by Giacos93** [comment]
Ho sempre eseguito il gioco come amministratore. Ho riscaricato ed il problema persiste
