### ISSUE TITLE
Bug sprite npc

### ISSUE THREAD

**Issue by Giacos93** [fuji97/pokemon-xenoverse-tracker#321]
Per molti npc non viene visualizzato lo sprite ma solo un'ombra a terra (come in foto)
![screenshot 2](https://user-images.githubusercontent.com/31915989/30364728-b39ab06a-9865-11e7-968e-fa14f142ede2.png)

**Comment by fabstarkey** [comment]
hai scaricato male il gioco, riscaricalo o accedi come amministratore!
