### ISSUE TITLE
Dopo aver sconfitto druddigon nella prima prova della palestra , il gioco crasha (ho già installato la patch)

### ISSUE THREAD

**Issue by Jackanddax** [fuji97/pokemon-xenoverse-tracker#323]

**Comment by fuji97** [comment]
Grazie per la segnalazione, potrebbe fornirci uno screen dell'errore?

**Comment by Jackanddax** [comment]
![cattura di schermata 514](https://user-images.githubusercontent.com/31917688/30366887-9a701fda-97f7-11e7-9a67-c6f3ad9e4109.png)

**Comment by Claus02** [comment]
scusa dove hai scaricato la patch? @Jackanddax

**Comment by Dhell96** [comment]
Successo identico anche a me! Io l'ho scaricata dal sito originale.

**Comment by Coccio98** [comment]
Idem

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
