### ISSUE TITLE
TRISHOUT/ALICE CHE MI SEGUE SEMPRE

### ISSUE THREAD

**Issue by Claus02** [fuji97/pokemon-xenoverse-tracker#325]
Entrato nel corridoio Roccioso, dopo aver incontrato Alice e fatto la prima battaglia al posto di lei c'è Trishout e se ci parlo invece è la ragazza, questo succede anche una volta usciti e non si resce a mandarlo via 

![cattura](https://user-images.githubusercontent.com/31895218/30369426-c8575c06-9874-11e7-8de3-b721c2293d7e.PNG)

![cattura1](https://user-images.githubusercontent.com/31895218/30369438-d23040b2-9874-11e7-99f4-5cc87343d3f9.PNG)

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
