### ISSUE TITLE
Non mi apre l'installer (Risolto)

### ISSUE THREAD

**Issue by Richicraft22** [fuji97/pokemon-xenoverse-tracker#33]
Ho appena scaricato l'installer di Pokémon Xenoverse, ma cliccandoci due volte, non si apre, neanche se lo eseguo come amministratore!

Io possiedo un Windows 10 (in origine era Windows 8.1)

**Comment by Richicraft22** [comment]
P.S. Ho provato a riscaricarlo più volte, ma niente.

**Comment by fuji97** [comment]
Quando lo apri devi aspettare un po'. Inoltre ricordati che non parte se non gli confermi i permessi di amministratore, controlla in basso se appare un icona con lo scudo

**Comment by Richicraft22** [comment]
C'è un'icona con lo scudo, ma come faccio a confermare i permessi, perchè non si apre se lo eseguo come amministratore.

**Comment by Richicraft22** [comment]
Ho risolto scaricando la zip che avevi messo al posto del link del sito "xenoteam"

**Comment by fuji97** [comment]
Va bene, allora chiudo
