### ISSUE TITLE
MOSSE TRISHOUT

### ISSUE THREAD

**Issue by Claus02** [fuji97/pokemon-xenoverse-tracker#331]
Io ho trishout T e ho scoperto ora che al 30 e al 36 doveva imparare rispettivamente rogodenti e lanciafamme ma non le ha imparate (C'è l'ho al 40...) Ci sarà un modo per risolvere questo bug e avere le mosse volutesi?

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
