### ISSUE TITLE
Problema Follow/Alice Post Patch

### ISSUE THREAD

**Issue by poket1** [fuji97/pokemon-xenoverse-tracker#332]
![21766905_2168716776487411_2112280748_o](https://user-images.githubusercontent.com/31869388/30371010-8dcb8300-9879-11e7-89f3-d43e87024811.jpg)

Ho un problema con lo script del follow (si ho già installato la patch)

Praticamente dopo l'evento dei fossili, avevo il problema del follow ma se parlavo col pokemon mi si attivava questo dialogo, quindi mi sa che si sono sovrapposti codici vari e mi legge il follow del pokemon come se fosse Alice

Pensavo che la patch me l'avrebbe tolto D:

**Comment by poket1** [comment]
Ah non vedete nulla dietro di me perchè non ho lo starter al primo posto della squadra, ma se mi giro dietro di me e premo come se parlassi con qualcuno mi appare questo D: quindi lo script del follow di Alice è rimasto

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
