### ISSUE TITLE
[1.0.1] [Major Bug]: Conseguenze mossa "Teletrasporto"

### ISSUE THREAD

**Issue by silvioiolli** [fuji97/pokemon-xenoverse-tracker#333]
Dopo aver usato la mossa _Teletrasporto_ di **Kadabra** non vengono caricati BG e Sprite vari, se non quello del personaggio

[<a href="https://gyazo.com/dd34e97d01d4101e00fcfb03aea41901"><img src="https://i.gyazo.com/dd34e97d01d4101e00fcfb03aea41901.png" alt="https://gyazo.com/dd34e97d01d4101e00fcfb03aea41901" width="512"/></a>](url)

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
