### ISSUE TITLE
[1.0.1] [Minor Bug]: Sprite Poké Ball invertiti

### ISSUE THREAD

**Issue by silvioiolli** [fuji97/pokemon-xenoverse-tracker#334]
Gli sprites di **Premier Ball** e **Rete Ball** sono stati invertiti

[<a href="https://gyazo.com/8802cbe22f0e3451858789fdb5551005"><img src="https://i.gyazo.com/8802cbe22f0e3451858789fdb5551005.png" alt="https://gyazo.com/8802cbe22f0e3451858789fdb5551005" width="511"/></a>](url)[<a href="https://gyazo.com/0943f86875b8d2ecbb97e23ac76aed6d"><img src="https://i.gyazo.com/0943f86875b8d2ecbb97e23ac76aed6d.png" alt="https://gyazo.com/0943f86875b8d2ecbb97e23ac76aed6d" width="513"/></a>](url)

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
