### ISSUE TITLE
Bug contro Trishout X

### ISSUE THREAD

**Issue by q1w2e34** [fuji97/pokemon-xenoverse-tracker#338]
dopo la patch nell'ultima battaglia contro Trishout X quando muore il primo pokemon e ne devo scegliere uno nuovo o quando provo a sostituirlo mi appare un errore ripetutamente e non riesco a continuare lo scontro
![cattura](https://user-images.githubusercontent.com/31922107/30373030-3dcb9262-9880-11e7-8c2a-bae192e981d3.PNG)

**Comment by Metalcape** [comment]
Come ho scritto in un'altra issue:

Non so se è già stato risolto, ma il bug del cambio pokémon durante la boss fight di Trishout X è molto banale, semplicemente lo scaleon di oleandro non è uno scaleon ma un altro pokemon (numero 943) e mancano gli sprite nelle cartelle graphics/icons e graphics/battlers. Basta andare in queste cartelle, copiare gli sprite di scaleon "normale" (numero 753) e nominarle icon943.png o 943.png a seconda del caso.

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
