### ISSUE TITLE
Bug - è possibile annullare evoluzione con pietra

### ISSUE THREAD

**Issue by rigandrea** [fuji97/pokemon-xenoverse-tracker#339]
Come da titolo, per puro caso ho premuto la X (il pulsante B del DS) mentre stavo facendo evolvere il mio Weepinbell.

L'evoluzione è stata annullata (nei giochi non è possibile farlo) e la pietra è stata rimossa dall'inventario.

Ho cercato un po' nel tracker, non mi pare qualcuno l'abbia già segnalato. Nel caso contrario, chiedo venia!

**Comment by fabstarkey** [comment]
scusa ma perchè hai premuto b? lol comunque cercheremo di aggiustare pure se è anche difficile pensare che qualcuno disattivi una evoluzione con le pietre lol

**Comment by rigandrea** [comment]
In realtà non era mia intenzione premere B :D mi sfuggì la tastiera di mano (è wireless) e per prenderla al volo schiacciai per sbaglio il tasto :P 

Sì, sarà difficilissimo che qualcun altro abbia in mente di cancellare l'evoluzione con pietra, ma mi sembrava giusto segnalarlo, tutto qui :)
