### ISSUE TITLE
bug dopo patch

### ISSUE THREAD

**Issue by shadowfury91** [fuji97/pokemon-xenoverse-tracker#340]
Dopo aver installato la patch(pre-patch avevo salvato dopo l'incontro con druddigon)ho battuto la terza palestra, salvato e al riavvio mi appare il seguente errore:
![image](https://user-images.githubusercontent.com/31922399/30373439-9fc1b09a-9881-11e7-918e-4e1be9f9d642.png)

**Comment by Patrickso99** [comment]
Anche a me non va piu' dopo la patch -> https://github.com/fuji97/pokemon-xenoverse-tracker/issues/319

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
