### ISSUE TITLE
[All Versions] [Bug]: Problema con disinstallazione Pokémon Xenoverse

### ISSUE THREAD

**Issue by silvioiolli** [fuji97/pokemon-xenoverse-tracker#341]
L'avvio dell'applicazione "_Disinstalla Pokémon Xenoverse_" causa la rimozione del solo file _**Uninstall**_ all'interno della cartella */Programmi (x86)/Pokémon Xenoverse e non del resto dei file (allo stato attuale sono presenti tutti i file meno quello di uninstall, posso ancora giocare normalmente)

[<a href="https://gyazo.com/55cd0328ded5780b1fa7ac8d22f59ffd"><img src="https://i.gyazo.com/55cd0328ded5780b1fa7ac8d22f59ffd.png" alt="https://gyazo.com/55cd0328ded5780b1fa7ac8d22f59ffd" width="1124"/></a>](url)

**Comment by andrewrov** [comment]
Ho notato pure io lo stesso problema e se non ricordo male non è possibile cancellare la cartella manualmente...

**Comment by silvioiolli** [comment]
La cartella è possibile cancellarla in seguito facendo così una disinstallazione manuale, per poi reinstallarlo alla versione 1.0.0 senza problemi

**Comment by fuji97** [comment]
Corretto
