### ISSUE TITLE
Crash Pokedex

### ISSUE THREAD

**Issue by xRatchet** [fuji97/pokemon-xenoverse-tracker#343]
Ho installato la patch 1.01 e, controllando che tutto stesse in ordine e non fosse sparito qualcosa, ho notato che se si tenta di aprire la finestra del pokemon (quella con la descrizione, il luogo dove trovarlo ecc. per interderci) il gioco crasha.

![immagine](https://user-images.githubusercontent.com/31922876/30374315-d1de3352-9884-11e7-8fa4-6dde9aa4f144.png)

Sapreste aiutarmi?

**Comment by fabstarkey** [comment]
attendi la patch nuova che uscirà a breve! e prova a riscaricare tutto
