### ISSUE TITLE
[1.0.1] [Bug]: Bremand nel Pokèdex errato e causa crash

### ISSUE THREAD

**Issue by silvioiolli** [fuji97/pokemon-xenoverse-tracker#344]
**Bremand** appare ancora con lo sprite sbagliato e causa crash se si tenta di aprire la voce del pokédex

[<a href="https://gyazo.com/61f70857f452fce5de6a80b3bbddd799"><img src="https://i.gyazo.com/61f70857f452fce5de6a80b3bbddd799.png" alt="https://gyazo.com/61f70857f452fce5de6a80b3bbddd799" width="514"/></a>](url)[<a href="https://gyazo.com/54852c7b09603548d4a039bdf93efb45"><img src="https://i.gyazo.com/54852c7b09603548d4a039bdf93efb45.png" alt="https://gyazo.com/54852c7b09603548d4a039bdf93efb45" width="512"/></a>](url)

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
