### ISSUE TITLE
[1.0.1] [Minor Text Bug]: Testo permanente

### ISSUE THREAD

**Issue by silvioiolli** [fuji97/pokemon-xenoverse-tracker#346]
Dopo aver cercato nel cestino nella casa di Esteban il testo è diventato permanente

[<a href="https://gyazo.com/0fee24f060005c0096252622570a7e5e"><img src="https://i.gyazo.com/0fee24f060005c0096252622570a7e5e.png" alt="https://gyazo.com/0fee24f060005c0096252622570a7e5e" width="514"/></a>](url)

[<a href="https://gyazo.com/87197979a50935f4deb470bc8f261bc3"><img src="https://i.gyazo.com/87197979a50935f4deb470bc8f261bc3.png" alt="https://gyazo.com/87197979a50935f4deb470bc8f261bc3" width="513"/></a>](url)

Edit: Ricaricando il salvataggio il testo sparisce.

**Comment by Sharyeeza** [comment]
Stesso problema

**Comment by fabstarkey** [comment]
grazie per la segnalazione!
