### ISSUE TITLE
Bug Caricamento Salvataggio e Problemi con il Sito

### ISSUE THREAD

**Issue by notLura** [fuji97/pokemon-xenoverse-tracker#350]
Cercando di caricare la partita da ieri mi da questo errore:

![screenshot 1](https://user-images.githubusercontent.com/31926043/30378679-4902bc50-9894-11e7-98d8-2c2513942363.png)

Inoltre il sito https://www.xenoteam.it/ viene considerato pericoloso su microsoft edge (win10) e la patch eliminata come virus da windows defender (per installarla ho dovuto creare eccezioni sia per la cartella di download che per quella di installlazione di xenoverse).

Spero non sia nulla di grave, in bocca al lupo!

**Comment by notLura** [comment]
PS il problema lo dava prima della patch, poi patchato ho provato a caricare per vedere se era tutto ok, ha caricato; quindi ho salvato il gioco e chiuso, al riavvio successivo non funzionava di nuovo

**Comment by fabstarkey** [comment]
prova a scaricare la patch nuova che uscirà a breve, questo non è un problema di gioco, ma del pc.
