### ISSUE TITLE
Mi crasha dopo lo scontro contro druddigon nel regno caramello

### ISSUE THREAD

**Issue by Magician-red-98** [fuji97/pokemon-xenoverse-tracker#352]
[
![cattura](https://user-images.githubusercontent.com/31898003/30378910-0e570da8-9895-11e7-9602-f06ed60452c3.JPG)
](url) Dopo aver messo termine alla sfida mi compare questo.
(Logicamente dopo aver scaricato la patch...)

**Comment by Magician-red-98** [comment]
Alla fine del combattimento compare questo.

**Comment by loltag22** [comment]
Confermo anche io

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
