### ISSUE TITLE
Errore durante level up (Shyleon)

### ISSUE THREAD

**Issue by Emax220x** [fuji97/pokemon-xenoverse-tracker#354]
Ogni volta che Shyleon sale di livello, appare questo errore : ---------------------------
Xenoverse
---------------------------
Exception: NameError

Message: uninitialized constant DISARMINGVOICE

MultipleForms:925

MultipleForms:920:in `call'

MultipleForms:172:in `call'

MultipleForms:96:in `getMoveList'

PokeBattle_Battle:1870:in `pbGainEXP'

PokeBattle_Battle:1837:in `loop'

PokeBattle_Battle:1876:in `pbGainEXP'

PokeBattle_Battle:1721:in `each'

PokeBattle_Battle:1721:in `pbGainEXP'

PokeBattle_Battle:1692:in `each'

This exception was logged in 

C:\Users\emanu\Saved Games/Xenoverse/errorlog.txt.

Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------
 
![shyleon](https://user-images.githubusercontent.com/31655629/30379293-452edf08-9896-11e7-9fa1-c97823ba7799.png)

Questo avviene dal livello 39 o 40, chiudendo l'avviso si può continuare a giocare regolarmente.

**Comment by rococo96** [comment]
Ho fatto varie prove, dato che ho scelto anche io Shyleon come starter e ho notato diverse cose:
-l'errore lo da solo se Shyleon è in possesso dell'Anello Terrestre;
-le statistiche aumentano comunque, ma il Pokemon non impara nuove mosse;
-se Shyleon è privo dell'Anello Terrestre, riesce a imparare le mosse normalmente;
-se viene data a Shyleon T una caramella rara, il gioco crasha; mentre non succede nulla per Shyleon privo dell'Anello Terrestre.

![errore xenoverse](https://user-images.githubusercontent.com/31927053/30381730-8b504f92-989d-11e7-839b-0dbeae314762.png)

Vedendo il nome dell'errore sembrerebbe essere legato alla mossa INCANTAVOCE.

Buon lavoro al Team e grazie di tutto :P

**Comment by fabstarkey** [comment]
Errore corretto nella patch che uscirà a breve :)
