### ISSUE TITLE
Non si può catturare Gengar X (v1.0.1)

### ISSUE THREAD

**Issue by Kyuzzinoh** [fuji97/pokemon-xenoverse-tracker#355]
inoltre scottando il pokémon, esso riceve danno ogni volta che si usa una Xenoball senza che esso attacchi

**Comment by aceggi** [comment]
È normale che non si possa catturare

**Comment by LeonidaXX1** [comment]
Non si può catturare perché altrimenti non si potrebbe verificare la sequenza che viene dopo, cioè che lui si innervosisce e se ne va promettendo di ritornare. Per quanto riguarda il fatto che lui non fa niente quando provi a catturarlo con le Xeno Ball, è vero, c'è un bug e hai fatto bene a farlo notare. Quando è il tuo turno e provi ad usare la Xeno Ball, un messaggio deve avvisarti che non puoi catturarlo, e questo accade, ma dopodiché, devi riprendere il combattimento, invece il gioco, al momento, considera quel messaggio che non puoi catturarlo come un turno appena concluso anziché come una notifica, e quindi fa applicare tutti gli effetti che si attivano alla fine del turno come i danni da veleno o scottatura, oppure i PS rigenerati con Parassiseme e simili.

**Comment by Kyuzzinoh** [comment]
oh pensavo che fosse un glitch, non ho mai sentito da nessuna parte che ritornasse in futuro. Grazie.
