### ISSUE TITLE
Avete implementato il follow?

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#356]
Come da titolo. Quando avvio il gioco mi appare sempre Trishout ed è però nella forma iniziale anche se tiene l'anello terrestre, quando però lo metto come primo della squadra, il follow viene sostituito con la sua forma terrestre, salvo poi scomparire quando lo cambio di posto. Tutto ciò avviene dopo aver patchato, quindi vi chiedo: nella patch ce lo avete aggiunto - e ci sarebbe comunque il bug perché mi compare in una forma diversa da quella che assume - o c'è qualche problema?

**Comment by fabstarkey** [comment]
In realtà il follow è un bug, che è stato corretto nella patch!
