### ISSUE TITLE
Problema Trishout X

### ISSUE THREAD

**Issue by SiberyanZ** [fuji97/pokemon-xenoverse-tracker#357]
Durante la battaglia con Trishout X mi sono imbattuto in questo errore:
![ererfg](https://user-images.githubusercontent.com/27746769/30381293-482070a4-989c-11e7-93f7-58b85ff7f6fe.PNG)
L'errore è probabilmente causato da eventuali cambiamenti di stato di Trishout X in quanto era stato paralizzato da Statico. Nello stesso turno ha mandato il mio Pokemon K.O. e ciò mi impediva di effettuare la sostituzione, con frequente apparizione del messaggio a schermo "Trishout è paralizzato e non può agire". Ho testato più volte e sembrano essere i problemi di stato la causa del bug.
Evitando di causargli problemi di stato sono riuscito a proseguire.

**Comment by Michi888** [comment]
a me questo bug si effettuava quando mi buttava giù il primo pokemon

**Comment by mattiaquila** [comment]
Anche a me. senza problemi di stato o niente. appena mi butta giu il primo e mi si apre la schermata per sostituirlo, appare il bug. e se clicco di non voler sostituire il pokemon il Trishout X continua ad attaccare senza avversario
