### ISSUE TITLE
C'è lo STAB?

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#358]
Ho Kungfur con Pugnorapido e Sharpedo X con Acquagetto. Sono due mosse di potenza 40, un valore un po' basso per dei Pokémon livello 30 e passa. Però sono due mosse dello stesso tipo dei miei Pokémon, quindi stabbate sarebbero 60 di potenza ed è un po' meglio. C'è lo STAB oppure no?

**Comment by fabstarkey** [comment]
Grazie per la segnalazione!
