### ISSUE TITLE
Problema Volo

### ISSUE THREAD

**Issue by SiberyanZ** [fuji97/pokemon-xenoverse-tracker#359]
Se si prova ad utilizzare Volo verso l'Arcipelago Vodoo si arriva qui:
![ervev](https://user-images.githubusercontent.com/27746769/30381894-f984d5c8-989d-11e7-872a-26d7a122fc12.PNG)
Mentre se si prova a volare verso il Regno Caramello lo schermo rimane completamente nero.
Rimane comunque possibile riutilizzare volo per andarsene.

**Comment by fuji97** [comment]
Grazie per la segnalazione
