### ISSUE TITLE
Bug battaglia con Trishout X (post patch) e altri bug minori

### ISSUE THREAD

**Issue by Michi888** [fuji97/pokemon-xenoverse-tracker#360]
Prima della battaglia l'npc ti presta Scaleon ma appena parte la battaglia Trishout X mi distrugge il primo pokemon e quando si apre la schermata per cambiare pokemon mi da errore, e se provo a cambiare
pokemon non lo cambia e Trishout X continua ad usare mosse, questo bug si verifica anche se non c'è Scaleon in squadra .
Durante il gameplay ho riscontrato anche altri bug come quello dello starter che ti segue ma non cosi problematici come quello che ho spiegato sopra.
Non so se è stato segnalato ma per sbaglio sono andato nel lato di un dislivello e il personaggio si è bloccato dentro.
Complimenti per il lavoro svolto dal Team Xenoverse nonostante i vari errori presenti nel gioco.

**Comment by Michi888** [comment]
Ah e ho trovato anche degli errori grafici che permettono al giocatore di trapassare alcuni oggetti.

**Comment by mattiaquila** [comment]
Seguo

**Comment by Metalcape** [comment]
Non so se è già stato risolto, ma il bug del cambio pokémon durante la boss fight di Trishout X è molto banale, semplicemente lo scaleon di oleandro non è uno scaleon ma un altro pokemon (numero 943) e mancano gli sprite nelle cartelle graphics/icons e graphics/battlers. Basta andare in queste cartelle, copiare gli sprite di scaleon "normale" (numero 753) e nominarle icon943.png o 943.png a seconda del caso.

**Comment by mattiaquila** [comment]
Io sto giocando con un emulatore di Windows su Mac. Non riesco ad aprire la cartella purtroppo, anche perché non uso Windows da una vita. Qualche dritta?

**Comment by Michi888** [comment]
Grazie Metalcape

**Comment by fabstarkey** [comment]
Errori risolti nella patch che uscirà a breve :)
