### ISSUE TITLE
Scaleon di Oleandro rimane in team

### ISSUE THREAD

**Issue by Emax220x** [fuji97/pokemon-xenoverse-tracker#361]
Dopo la fine della prima parte, andando in un centro pokemon per curare la squadra, ho notato che il suono delle pokeball posizionate nella macchina per curare contava 7 pokeball, nonostante il team fosse composto da 6 pokemon, ho quindi deciso di depositare un pokemon nel box e nel team è apparso lo scaleon di Oleandro, che ora risulta mio a tutti gli effetti. 
![scaleon](https://user-images.githubusercontent.com/31655629/30382514-98b8821a-989f-11e7-9394-0281ba1391ae.png)

**Comment by Armasus** [comment]
invece a me è sparito il mio...
