### ISSUE TITLE
Bug Oasi Cocente - Oggetto "TOMATO"

### ISSUE THREAD

**Issue by Xangeon** [fuji97/pokemon-xenoverse-tracker#362]
Salve, all'oasi cocente, se si prova a raccogliere questo oggetto
 
![1](https://user-images.githubusercontent.com/31928922/30383235-8a1d2cf4-98a1-11e7-8135-e47a6f00cc5e.jpg)

crasha il gioco, dando questo errore

![2](https://user-images.githubusercontent.com/31928922/30383264-a2852530-98a1-11e7-91b1-814356352aa0.jpg)

per la mancanza di questo oggetto "TOMATO".

**Comment by fabstarkey** [comment]
Errore risolto nella patch che uscirà a breve :)

**Comment by Xangeon** [comment]
Grandissimi :D
