### ISSUE TITLE
Download non funzionante

### ISSUE THREAD

**Issue by Infinity2000123** [fuji97/pokemon-xenoverse-tracker#364]
è da ieri sera che provo a scaricare Xenoverse ma, arrivato a 459 su 459 si blocca e non me lo fa aprire, ho liberato tantissimo spazio ma non va comunque, ho provato ad istallalo in modi diversi 5 volte e  non ha funzionato

**Comment by fuji97** [comment]
Non è colpa nostra, controlla se qualche anti-virus blocca il download e prova con qualche altro Browser
