### ISSUE TITLE
Problema con Pokedex (Dopo installazione patch)

### ISSUE THREAD

**Issue by DragonX93** [fuji97/pokemon-xenoverse-tracker#365]
Se seleziono un qualsiasi pokemon nel pokedex per guardare le sue informazioni viene un messaggio di errore e il gioco crasha (ho provato con 5/6 pokemon  a caso e dà lo stesso risultato)
![20170913_171016](https://user-images.githubusercontent.com/31856559/30385840-9dc98318-98a8-11e7-88ad-a77fd711824c.jpg)

**Comment by fabstarkey** [comment]
Errore risolto nella patch che uscirà a breve :)
