### ISSUE TITLE
va a scatti e non full screen

### ISSUE THREAD

**Issue by ettore111** [fuji97/pokemon-xenoverse-tracker#366]
1 come mai non riesco a mettere il full screen?
2 come mai se premo un tasto l azione parte con 5 secondi di ritardo? 
3 va leggermente a scatti, ho un pc buono vi lavoro con photoshop quindi dovrebbe leggere alla stragrande il gioco. tnks

**Comment by fuji97** [comment]
Grazie per la segnalazione, ci puoi inviare uno screen della scheda allenatore?

**Comment by ettore111** [comment]
non ho neanche iniziato il gioco se si vuole dire , ho aperto il menu sono andato nella sezione impostazioni e per muovermi ci metteva un fracasso, ho dato il via al gioco ho visto fin che il padre prende il figlio n collo ma andava a scatti. comunque potreste impostare il gioco in full screen o dare la possibilità oltre alle versioni finestra piccola media e grande?. ultima cosa si può usare il joystick?

grazie mille

**Comment by fabstarkey** [comment]
prova a scaricare la patch nuova che uscirà a breve e facci sapere.

**Comment by fffffffffffffffffffffffffffffffffffg** [comment]
per mettere a schermo intero basta premere invio+alt (o control+alt a seconda della tastiera). Prova

**Comment by ettore111** [comment]
scusate del ritardo, quando esce la patch vi faccio sapere

**Comment by ettore111** [comment]
![image](https://user-images.githubusercontent.com/31930637/30521519-2c8b29ce-9bc1-11e7-885e-e90d2d758938.png)
 comunque lo schermo full screen da questi problemi
