### ISSUE TITLE
[Patch 1.0.1]: "problemi" rimasti

### ISSUE THREAD

**Issue by DragonX93** [fuji97/pokemon-xenoverse-tracker#367]
Nella Patch 1.0.1 sono ancora presenti delle cose che avevo segnalato precedentemente:
- descrizione MT Sanguisuga nello zaino é errata
- backsprites Honchen e Harrowl sono enormi, dovrebbero essere rimpiccioliti un po'

(Per dettagli, guardare tra i miei ultimi post)

**Comment by fabstarkey** [comment]
Grazie per la segnalazione! saranno aggiornati in futuro
