### ISSUE TITLE
Errore quando Shyleon sale di livello

### ISSUE THREAD

**Issue by Dentice** [fuji97/pokemon-xenoverse-tracker#368]
Quando shyleon sale di livello, mi appare questo errore. Il gioco non crasha se premo OK.
http://prntscr.com/gkppg7

**Comment by AlberoSaggio** [comment]
@Dentice Questo errore prima o dopo aver applicato la patch 1.0.1?

**Comment by Yvaall** [comment]
succede anche a me, esattamente la stessa cosa, dopo la patch.
Se invece uso una caramella rara, dopo l'errore crasha il gioco

**Comment by fabstarkey** [comment]
Errore risolto nella patch che uscirà a breve :)
