### ISSUE TITLE
Visualizzazione mappa PKMN CENTER + altro

### ISSUE THREAD

**Issue by nutthegreat** [fuji97/pokemon-xenoverse-tracker#37]
Salve,

intanto complimenti per il gioco perchè si vede la cura messa finora.

segnalo alcuni problemi che ho trovato sinora, nonostante abbia reinstalalto più volte il gioco:

nella intro le tre pokeball degli starter non vengono visualizzate sull'erba nella mappa

la mossa vocalizzo non presenta descrizione,

mi sembra che le texture dei tipi di mossa (fisico/speciale/stato) siano sfalsate quando si controllano le mosse

alcuni png sembrano volatilizzarsi durante alcune scene o diventare "fantasmi" per poi riapparire subito dopo.

statico triggera su vocalizzo (che mi sembra una mossa ranged) ma più strano ancora mi triggera su Sparkly (che essendo di tipo elettrico non dovrebbe essere paralizzabile)

e non per ultimo l'intera mappa del pokemon center a lumipoli non mi viene visualizzata. si vedono solo i png, joy e il cartello dietro di lei (per il resto funziona, ma cercare il pc al buio è stata una tragedia.

FIGHT!

![luminopolipkmncenter](https://user-images.githubusercontent.com/31795895/30239379-ab994924-955b-11e7-8e60-a83460672f39.png)

**Comment by nutthegreat** [comment]
Aggiornamento: potrebbe essere la codifica dei caratteri unicode di Windows a causare questo ed altri problemi. ho provato a smanettare con le impostazioni base e ora la mappa è correttamente visualizzata.

**Comment by lukenaster** [comment]
Scusa potresti spiegare come hai risolto il problema nel dettaglio?

**Comment by nutthegreat** [comment]
Nelle impostazioni della lingua, devi guardare sulla gestione dei caratteri unicode e assicurarti che sia impostata la lingua italiana



Inviato da smartphone Samsung Galaxy.

-------- Messaggio originale --------
Da: lukenaster <notifications@github.com>
Data: 09/09/17 15:01 (GMT+01:00)
A: fuji97/pokemon-xenoverse-tracker <pokemon-xenoverse-tracker@noreply.github.com>
Cc: nutthegreat <nutthegreat@hotmail.it>, Author <author@noreply.github.com>
Oggetto: Re: [fuji97/pokemon-xenoverse-tracker] Visualizzazione mappa PKMN CENTER + altro (#37)


Scusa potresti spiegare come hai risolto il problema nel dettaglio?

**Comment by fuji97** [comment]
> Nelle impostazioni della lingua, devi guardare sulla gestione dei caratteri unicode e assicurarti che sia impostata la lingua italiana

Sicuro che funziona? Mi dici precisamente quali impostazioni bisogna impostare per farlo funzionare?

**Comment by nutthegreat** [comment]
Non sono al computer, tuttavia le impostazioni dovrebbero essere quelle dei caratteri unicode, la data e l'ora in formato italiano e l'area geografica italiana



Inviato da smartphone Samsung Galaxy.

-------- Messaggio originale --------
Da: Federico Rapetti <notifications@github.com>
Data: 09/09/17 18:56 (GMT+01:00)
A: fuji97/pokemon-xenoverse-tracker <pokemon-xenoverse-tracker@noreply.github.com>
Cc: nutthegreat <nutthegreat@hotmail.it>, Author <author@noreply.github.com>
Oggetto: Re: [fuji97/pokemon-xenoverse-tracker] Visualizzazione mappa PKMN CENTER + altro (#37)


Nelle impostazioni della lingua, devi guardare sulla gestione dei caratteri unicode e assicurarti che sia impostata la lingua italiana

Sicuro che funziona? Mi dici precisamente quali impostazioni bisogna impostare per farlo funzionare?

**Comment by Sharyeeza** [comment]
Riscontro lo stesso identico problema e nel mio pc lingua, data, ora e area geografica sono tutte impostate su Italiano.

Riguardo altri problemi, anche io ho notato che la scheda allenatore del personaggio femminile ha la foto di quella maschile e infine in alcuni momenti di gioco il testo era in inglese, ad esempio in una scheda pokedex e in un avviso di fine avvelenamento (al di fuori della battaglia).

**Comment by fuji97** [comment]
> Non sono al computer, tuttavia le impostazioni dovrebbero essere quelle dei caratteri unicode, la data e l'ora in formato italiano e l'area geografica italiana

Dove si trova l'impostazione dei caratteri Unicode?

**Comment by fabstarkey** [comment]
riscarica il gioco e dovrebbe funzionare!
