### ISSUE TITLE
Non appaiono le scritte, solo i dialoghi

### ISSUE THREAD

**Issue by Infinity2000123** [fuji97/pokemon-xenoverse-tracker#370]
Appena ho aperto Xeoverse non mi dava le scritte come nuovo inizio, opzioni ecc.
Ho pensato che fosse un problema che si sarebbe sistemato dopo aver salvato ed istallato la patch, ma nulla, le uniche scritte che mi appaiono sono i dialoghi con gli altri pg. Spero riusciate ad aiutarmi dato che così non posso nè godermi il gioco nè giocarlo.

**Comment by Emax220x** [comment]
Potrebbe essere un problema di font, vai nella cartella d'installazione del gioco, apri la cartella "fonts", selezionali tutti e premendo col tasto destro fai "installa"

**Comment by Infinity2000123** [comment]
Non funziona comunque
