### ISSUE TITLE
Problema battaglia trishoutX

### ISSUE THREAD

**Issue by XVGamer** [fuji97/pokemon-xenoverse-tracker#372]
quando mi muore il primo pokemon contro trishout e voglio cambiare pokemon mi esce una scritta e non mi fa cambiare pokemon  e trishout attacca all impazzata

**Comment by DarkWolfss** [comment]
Stesso problema, spero si possa risolvere in fretta

**Comment by fabstarkey** [comment]
Inviaci l'errore che ti da il gioco!
