### ISSUE TITLE
BUG GIGANTESCO

### ISSUE THREAD

**Issue by MarishDima92** [fuji97/pokemon-xenoverse-tracker#373]
Installata la nuova patch sono arrivato al villaggio simil Egitto. salvo, raccolgo un oggetto luccicante sulla destra della mappa e mi crasha il gioco. Riapro il gioco e mi trovo in casa di un vecchio con la tipa che mi parla ma il mio personaggio non appare su schermo e non mi posso muovere! come faccio?

**Comment by fabstarkey** [comment]
Errore risolto nella patch che uscirà a breve :)
