### ISSUE TITLE
Bug Druddigon terza palestra

### ISSUE THREAD

**Issue by Matthingly** [fuji97/pokemon-xenoverse-tracker#374]
Dopo aver battuto Druddigon nella terza palestra il gioco mi craso. Ho già applicato la patch.

**Comment by andrewrov** [comment]
Stai parlando di un bug oramai ben noto e segnalato da molti, dovrai aspettare una nuova patch

**Comment by fabstarkey** [comment]
Errore risolto nella patch che uscirà a breve :)
