### ISSUE TITLE
Crush quando si accedono alle info dei Pokemon sul Pokedex

### ISSUE THREAD

**Issue by Ring94** [fuji97/pokemon-xenoverse-tracker#375]
Ciao,ho scaricato la patch e ho risolto i problemi che prima vi erano; solo che mi crusha il gioco quando sul Pokedex accedo alle informazioni di un Pokemon.
Lo schermo si oscura ed esce fuori una casella di testo contenente un errore (allego lo screen in spoiler).
Come mai accade ciò?

[spoiler][img]https://imgur.com/znBwC7o.jpeg[/img][/spoiler]

**Comment by Soar16** [comment]
Anche a me succede la stessa cosa


Il 13 set 2017 7:19 PM, "Ring94" <notifications@github.com> ha scritto:

**Comment by fabstarkey** [comment]
Errore risolto nella patch che uscirà a breve :)
