### ISSUE TITLE
[1.0.0 to 1.0.1] [Bug]: Cattura Pokemon

### ISSUE THREAD

**Issue by silvioiolli** [fuji97/pokemon-xenoverse-tracker#376]
Ho fatto downgrade alla 1.0.0 per bypassare il bug alla 3a palestra e ho poi fatto upgrade alla 1.0.1 ma il bug che non permette la cattura persiste anche con la patch

**Comment by fabstarkey** [comment]
Scarica la 1.0.2 appena esce!
