### ISSUE TITLE
Schifo all' entrata del Corridoio Roccioso^^

### ISSUE THREAD

**Issue by Noruxen** [fuji97/pokemon-xenoverse-tracker#378]
![immagine](https://user-images.githubusercontent.com/31793552/30393843-a0601ea2-98c1-11e7-95fd-be716933ffa4.png)

a voi^^

**Comment by Noruxen** [comment]
non ho ancora aggiornato alla 1.0.1 quindi non so se il bug è risolto

**Comment by DragonX93** [comment]
Nella 1.0.1 questo bug é risolto :)

**Comment by Noruxen** [comment]
grazie DragonX93 con questo allo chiudo
