### ISSUE TITLE
Domanda MT79 Alitogelido

### ISSUE THREAD

**Issue by merians** [fuji97/pokemon-xenoverse-tracker#380]
Ciao volevo sapere se per sbaglio questa mt è stata messa sia al vulcano decibel che al monte pico ( o grotta ghiacciolo) visto che credo di averne trovate due. Grazie e davvero ottimo lavoro con pokemon xenoverse

**Comment by NicoBaldi94** [comment]
seguo

**Comment by fabstarkey** [comment]
Grazie per la segnalazione, risolveremo nella patch 1.0.3.
