### ISSUE TITLE
Bug percorso 8

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#381]
Come vedete in questo percorso non è possibile usare i dossi per muoversi più velocemente verso giù

![bug perc 8 post patch](https://user-images.githubusercontent.com/31867848/30398777-e9528176-98d1-11e7-944a-583832da4adc.jpg)

**Comment by fabstarkey** [comment]
risolveremo nella patch 1.0.3.
