### ISSUE TITLE
BUG anello xenoverse

### ISSUE THREAD

**Issue by NicoBaldi94** [fuji97/pokemon-xenoverse-tracker#383]
Dopo la battaglia finale contro il mio starter. ogni vota che sconfiggo un pokemon selvatico  quest'ultimo lascia un anello xenoverse, quello blu per intenderci. questo è avvenuto dopo che ho scaricato la patch.
Non so se sono l'unico.

**Comment by fabstarkey** [comment]
Errore risolto nella patch che uscirà a breve :)
