### ISSUE TITLE
BUG lotta contro lo starter

### ISSUE THREAD

**Issue by DarkWolfss** [fuji97/pokemon-xenoverse-tracker#384]
Durante il combattimento contro lo starter al Vulcano Decibel se tento di accedere alla squadra per cambiare Pokemon (idem quando mi viene messo K.O.) il gioco mi crasha e Trishout continua ad attaccare a vuoto , ho provato pure a togliere il mio Schaleon dalla squadra ma mi da sempre lo stesso errore , si può risolvere in qualche modo ?

Comunque a parte i vari Bug inevitabili ne approfitto per fare i miei complimenti a tutto il Team per il fantastico prodotto che ci hanno offerto :)

**Comment by LeonidaXX1** [comment]
Ho trovato il modo di aggirare il bug, anche se ciò genera un altro bug... In pratica il gioco va in tilt perché non riconosce i sei posti che occupano i Pokémon quando affronti Trishout X con cinque Pokémon, quindi devi averne sei in squadra, così facendo potrai affrontarlo tranquillamente. Come già detto questo procedimento a sua volta genera un bug e cioè che tutte le mosse dell'ultimo Pokémon della squadra vengono sostituite con quelle dello Scaleon del saggio. In sostanza il gioco dovrebbe aggiungerti il suo Scaleon in squadra e quindi dovrebbe verificare che tu affronti Trishout X con al massimo cinque Pokémon per far spazio a Scaleon, ma non lo fa, e anzi non calcola il sesto posto se lo combatti con cinque, quindi devi averne sei e vederti sostituire tutte le mosse dell'ultimo Pokémon. A me paradossalmente il bug ha fornito un vantaggio perché all'ultimo posto ci ho aggiunto il mio di Scaleon, al livello 11, ma già uppato con mosse tipo Dragartigli...

**Comment by fabstarkey** [comment]
Errore risolto nella patch che uscirà a breve :)
