### ISSUE TITLE
Bug Volo Regno Caramello

### ISSUE THREAD

**Issue by Yvaall** [fuji97/pokemon-xenoverse-tracker#386]
Dopo aver finito la parte uno, se uso volo per andare a Regno Caramello Finisco in uno schermo nero. Il gioco sembra funzionare ugualmente, l'audio funziona in sottofondo e anche quando sbatto contro i muri. Semplicemente non si vede niente, schermo completamente nero

**Comment by fabstarkey** [comment]
Grazie per la segnalazione!
