### ISSUE TITLE
Move set Sharpedo X

### ISSUE THREAD

**Issue by AkeRoss** [fuji97/pokemon-xenoverse-tracker#390]
ho portato Sharpedo X al livello 30 e ancora non ha imparato neanche mezza mossa d' acqua, sono disperato :(

**Comment by LeonidaXX1** [comment]
Impara Acquagetto al liv 34 se non erro, comunque pochi livelli sopra il 30. È di potenza 40 ma perlomeno è stabbata e, leggendo la descrizione, sembra sia anche veloce. Comunque conviene puntare anche su altre mosse, il mio ha anche Sgranocchio e Lacerazione.
