### ISSUE TITLE
Bug nel box

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#391]
Prima parte conclusa ed è doveroso fare sinceramente i miei complimenti a tutto lo staff. Detto ciò, dopo la battaglia contro Trishout X il gioco rilevava che avevo sette Pokémon in squadra e perciò crashava, ho risolto spostandone uno nel box, il mio Scaleon che però ha assorbito tutte le mosse dello Scaleon di Oleandro. Fin qui tutto risolto e anzi il bug ha fatto imparare al mio Pokémon delle mosse niente male... Il problema è che il posto in box che Scaleon occupava ora non è più utilizzabile perché il gioco crasha anche solo se ci passo col cursore

**Comment by fabstarkey** [comment]
Errore risolto nella patch che uscirà a breve :)
