### ISSUE TITLE
Circuiti per fare Poké Ball senza immagini

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#392]
Idem per il Circuito Velox Ball

![bxdb](https://user-images.githubusercontent.com/31867848/30421107-07b81972-993c-11e7-86b9-9c9380d161b6.jpg)

**Comment by fabstarkey** [comment]
Grazie per la segnalazione! Ci puoi dire dove hai trovato il circuito?

**Comment by LeonidaXX1** [comment]
Dopo aver concluso la prima parte sono ritornato a Ludopoli e me le hanno consegnate, se non ricordo male, due scienziati del laboratorio di Ezio

**Comment by fabstarkey** [comment]
grazie per la segnalazione. Abbiamo risolto!
