### ISSUE TITLE
Trovata la citazione al Saluta Andonio nazionale

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#393]
Complimenti per la genialità, ma ora questo npc dovrà andare a farsi una canna e un giro all'Iper per tutta la vita... PS: all'inizio non ci avevo fatto caso, però mi sembrava così assurdo farsi un giro al centro Pokémon che ho analizzato attentamente... Il fatto che si chiami Marco era la citazione che cercavo. Bravi, ingegnosi e spiritosi, siete il top uajù.

![bfxd](https://user-images.githubusercontent.com/31867848/30421252-79b005e4-993c-11e7-9b6b-cd2427ac4a50.jpg)

**Comment by fabstarkey** [comment]
:)
