### ISSUE TITLE
MANCA IL POKEDEX

### ISSUE THREAD

**Issue by joti92** [fuji97/pokemon-xenoverse-tracker#394]
![cattura](https://user-images.githubusercontent.com/31956578/30426267-aef1efa6-994b-11e7-95c2-5621c17dac81.PNG)

non c'è il pokedex

**Comment by fabstarkey** [comment]
dovresti aver ottenuto il pokewes (la casellina mancante), perchè non lo tieni?

**Comment by joti92** [comment]
non lo so
