### ISSUE TITLE
non posso catturare pokemon

### ISSUE THREAD

**Issue by rub03** [fuji97/pokemon-xenoverse-tracker#396]
se provo a catturare un pokèmon mi dice che il pokèmon non può essere catturato e lo fa in qualsiasi zona vi prego sistematelo

**Comment by AkeRoss** [comment]
a me non da una cosa del genere, il gioco lo fai partire in modalità amministratore?

**Comment by rub03** [comment]
Si lo faccio partire come amministratore
Il 14 set 2017 14:38, "AkeRoss" <notifications@github.com> ha scritto:

**Comment by rub03** [comment]
Si avvio come amministratoreInviato dal mio dispositivo Huawei-------- Messaggio originale --------Oggetto: Re: [fuji97/pokemon-xenoverse-tracker] non posso catturare pokemon (#396)Da: AkeRoss A: fuji97/pokemon-xenoverse-tracker CC: rub03 ,Author a me non da una cosa del genere, il gioco lo fai partire in modalità amministratore?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fuji97/pokemon-xenoverse-tracker","title":"fuji97/pokemon-xenoverse-tracker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fuji97/pokemon-xenoverse-tracker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AkeRoss in #396: a me non da una cosa del genere, il gioco lo fai partire in modalità amministratore?"}],"action":{"name":"View Issue","url":"https://github.com/fuji97/pokemon-xenoverse-tracker/issues/396#issuecomment-329468839"}}}

**Comment by rub03** [comment]
ora ti invio una foto 
![cattura](https://user-images.githubusercontent.com/31958434/30430768-91194c20-995c-11e7-812f-af4a67d91e64.PNG)

**Comment by rub03** [comment]
lo fa con tutti i pokemon di questa zona e di quelle precedenti

**Comment by Nadttam** [comment]
ho lo stesso tuo problema.. come si può risolvere???? please help

**Comment by Nadttam** [comment]
io ho provato anche a liberare il box.. ma niente..

**Comment by rub03** [comment]
Nemmeno io sono riuscito a risolverlo pure svuotando il box e reinstallando
il gioco
Il 14 set 2017 17:57, "Nadttam" <notifications@github.com> ha scritto:

**Comment by giovannipicotti98** [comment]
anche io, sono da due giorni che installo e disinstalllo, ma senza risultati

**Comment by giovannipicotti98** [comment]
esatto rub03

**Comment by Nadttam** [comment]
in teoria non so perche come hanno scritto la prossima patch risolve alcuni problemi, ma tra quelli che hanno elencato non c'è questo...

**Comment by rub03** [comment]
Ci resta la speranza che leggano l'avviso e che aggiustino questo bug
altrimenti saremo costretti ad usare i pokemon che abbiamo e basta
Il 14 set 2017 18:16, "Nadttam" <notifications@github.com> ha scritto:

**Comment by fabstarkey** [comment]
Risolto nella patch che uscirà a breve :)

**Comment by rub03** [comment]
Ok grazie mille
Il 16 set 2017 00:50, "fabstarkey" <notifications@github.com> ha scritto:
