### ISSUE TITLE
Che fine ha fatto la patch da scaricare ?

### ISSUE THREAD

**Issue by rickkkkkkk** [fuji97/pokemon-xenoverse-tracker#398]
Quando clicco download per la patch non c'è la versione 1.01

**Comment by andrewrov** [comment]
Prima di chiedere non guasterebbe guardare le altre domande, altrimenti si ritrovano 200 domande tutte uguali...
Se avessi avuto la pazienza di cercare tra le altre domande avresti visto che l'hanno tolta perché contiene altri bug, comunque tra oggi e domani (teoricamente a breve ma potrebbero avere problemi) dovrebbero rilasciare la 1.0.2 che risolve i principali problemi della 1.0.0 e 1.0.1

**Comment by rickkkkkkk** [comment]
Ok hai ragione e ti ringrazio per la risposta ma siccome me ne sono accorto stamattina che mancava la patch pensavo l'avessero appena tolta dato che ieri non ho guardato se c'era o no. Nella prima pagina, dove puoi fare le domande ,non ne ho notato altre uguali alla mia e non ho pensato a vedere le pagine precedenti. Mi pareva strano guardare le domande più vecchie, dato che pensavo la patch fosse stata tolta questa mattina.

**Comment by Absol99** [comment]
Ho già aspettato 4 giorni e sinceramente uno o due di più non mi cambiano le cose

**Comment by Absol99** [comment]
Vorrei riuscire a scaricarla entro la fine della settimana, ma aspetto volentieri
