### ISSUE TITLE
Bug relitto Sharpedo

### ISSUE THREAD

**Issue by Zyechdar** [fuji97/pokemon-xenoverse-tracker#399]
Sono entrato nella sala in cui c'è Sharpedo X, ma mi appare schermo nero. Sento i suoni, posso muovermi ma non posso uscire né interagire. Che faccio?

**Comment by andrewrov** [comment]
Hai provato a ricaricare il gioco? Io ho fatto quella parte sia nella 1.0.0 che nella 1.0.1 e non mi è mai capitato

**Comment by fabstarkey** [comment]
Risolto nella patch che uscirà a breve :)
