### ISSUE TITLE
Pulsanti Si/No senza scritta

### ISSUE THREAD

**Issue by loplace** [fuji97/pokemon-xenoverse-tracker#4]
Innanzitutto, i miei complimenti per il lavoro. sono a 2-3 ore di gioco e mi sto divertendo un mondo.
Poi, come intuibile dal titolo, quando compaiono i box per selezionare Si/No alle domande (es. vuoi curare i tuoi pokemon?) compaiono i box di testo, ma non il testo all'interno. Per carità, nulla di grave o problematico, ma pensavo fosse giusto segnalarlo.
Vedendo gli altri 2 bug segnalati al momento in cui sto facendo questo report, confermo la descrizione mancante di vocalizzo, ma fortunatamente non il problema delle OST.

**Comment by loplace** [comment]
Ho letto ora le faq, appena ho un minuto provo a reinstallare i font ed eventualmente aggiornare l'issue.

**Comment by fuji97** [comment]
Fammi sapere se hai risolto

**Comment by fuji97** [comment]
Non avendo ricevuto altre segnalazioni do per scontato che sia risolto
