### ISSUE TITLE
Bug scomparsa pokemon 

### ISSUE THREAD

**Issue by Berna20** [fuji97/pokemon-xenoverse-tracker#400]
Dopo aver sconfitto trishout x e dopo aver visto i sottotitoli ho aperto la mia squadra e ho notato che mancava il mio scaleon ho provato a vedere se era nel box del pc ma non c'era
 (Ho la versione non patchata)

**Comment by mrchaos92** [comment]
Ho notato anche io, ma avevo anche notato che se guardavo le statistiche dei pokemon e continuavo a scorrere i pokemon verso il basso, il mio scaleon era ancora lì ed era come se avessi 7 pokemon in squadra. Quindi praticamente avevo risolto andando in un box pokemon e depositando un pokemon della squadra nel box. Poi ero andato sulla squadra (sempre attraverso il menù del box) ed avevo guardato le statistiche dei pokemon per poi  scorrere verso il basso fino a vedere le statistiche del mio scaleon ed infine avevo premuto il tasto per tornare indietro. Qui la freccia indicava lo spazio vuoto nella squadra ed, dopo aver premuto il tasto di conferma, ho depositato il pokemon nel box. Così, appunto me lo sono ritrovato nel box e l'ho potuto ritirare

**Comment by Berna20** [comment]
Vai grazie mille! Mi era preso un colpo perché è il pokemon più forte che ho in squadra se non il più figo

**Comment by fabstarkey** [comment]
Risolto nella patch che uscirà a breve :)
