### ISSUE TITLE
Trishout può imparare Ultrasuono?

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#401]
Al momento ho rimasto nel move set del mio Trishout la mossa Vocalizzo perché è l'unica di tipo suono, però è un po' scarsa, con 45 di potenza, gliel'ho rimasta perché fa comodo il superefficace contro acqua o volante, contro Rochelle è stato utilissimo contro il folletto. Rimane comunque una mossa deboluccia ed è strano che il mio Pokémon ce l'abbia praticamente dall'inizio e ancora non impari qualche altra mossa suono, come invece ha fatto col tipo fuoco imparando, dopo Pirolancio, anche Rogodenti e addirittura Lanciafiamme. Ho letto da qualche parte che Trishout in forma evoluta non impara le mosse, allora lo faccio livellare senza equipaggiarlo con uno dei due anelli. Purtroppo prima del livello 30, più o meno, non lo sapevo, e quindi è da quel livello che sto facendo così. E' possibile che Trishout impari Ultrasuono prima di quel livello e che quindi me lo sono perso? Ho visto usare quella mossa da Trishout X ma lui era pure al livello 50. Al Trishout di qualcuno è capitato di impaparla? Il mio ora è al 42 e niente ancora.

**Comment by Edo17995** [comment]
Impara infrasuono al 46

**Comment by andrewrov** [comment]
@Edo17995 sicuro? Perché sui file del gioco non dice nulla, te l'ha imparata realmente o l'hai letto da qualche parte?
Nel caso te l'avesse imparata, in che forma era? Normale/T/X?
Perché ho notato che è abbastanza buggato l'apprendimento delle mosse, al 30 senza anello terrestre impara Rogodenti, se invece glie lo lasci non impara nulla.
Poi seguendo i file di gioco avrebbe dovuto imparare Lanciafiamme al 36 ma invece al mio l'ha imparato in forma T al 32...

**Comment by LeonidaXX1** [comment]
@andrewrov Scusa la domanda, dove sono questi file di gioco?

**Comment by andrewrov** [comment]
@LeonidaXX1 Click tasto destro sul gioco -> Apri percorso file
Dopo nella cartella "PBS" c'è un file "pokemon" in cui ci sono i vari pokemon nel gioco con le varie statistiche tra cui le mosse ed i livelli in cui le dovrebbero imparare.
Però sinceramente non so se quei file siano d'esempio o se vengano letti realmente dal gioco

**Comment by LeonidaXX1** [comment]
Ok, grazie
