### ISSUE TITLE
Bug allenatrice dopo il campus acero

### ISSUE THREAD

**Issue by fffffffffffffffffffffffffffffffffffg** [fuji97/pokemon-xenoverse-tracker#402]
c'è una allenatrice subito dopo il campus acero (una campeggista che viene sfidata subito dopo un bullo che si definisce il "discepolo di Gennaro Bullo". Ha l'evoluzione di Sparkowl e un, BugBag e Beedrill). Se dopo averla sconfitta si prova a parlarle, il gioco crasha, in quanto il file del dialogo è inesistente.

**Comment by fabstarkey** [comment]
Risolto nella patch che uscirà a breve :)
