### ISSUE TITLE
Download patch only

### ISSUE THREAD

**Issue by MalcryZ** [fuji97/pokemon-xenoverse-tracker#404]
Non avendo una connessione a internet, non mi è possibile patchare il gioco, è possibile avere un link per scaricare la 1.01 da browser? Dato che con il 3G posso scaricarla e poi passarla qui

**Comment by andrewrov** [comment]
La patch 1.0.1 è stata tolta dal download perché conteneva altri problemi e hanno preferito toglierla e far aspettare il rilascio della 1.0.2 (in teoria in uscita a breve, al massimo entro domani) per poter risolvere tutti i problemi delle precedenti versioni

**Comment by MalcryZ** [comment]
Oh,lol
