### ISSUE TITLE
Shulong moovset BUG

### ISSUE THREAD

**Issue by NicoBaldi94** [fuji97/pokemon-xenoverse-tracker#405]
dal file del gioco shulong dovrebbe imparare delle mosse come dragospiro, ripresa, acquatail, muddywater, riduttore. ma sembra (come ho letto anche in altri post) che quando gli starter siano in forma terra questi non imparino le mosse. o almeno è quello che è successo a me che mi ritrovo uno shulong al 40 ancora con bollaraggio come stab doppiocolpo e alitogelido per la mt.
esiste un ricorda mosse? o sarà presente solo nella seconda parte del gioco?

**Comment by fabstarkey** [comment]
Risolto nella patch che uscirà a breve :)
