### ISSUE TITLE
Bug minori

### ISSUE THREAD

**Issue by ChiaBaka00** [fuji97/pokemon-xenoverse-tracker#406]
![ffefefe](https://user-images.githubusercontent.com/31824752/30439188-6540de6c-9973-11e7-9370-cc0072cf2111.PNG)

![ddddddd](https://user-images.githubusercontent.com/31824752/30439224-75c5763a-9973-11e7-884e-7961792bc994.PNG)

![nnnnn](https://user-images.githubusercontent.com/31824752/30439239-7dba97a8-9973-11e7-9195-8213194bf9c0.PNG)
Questo personaggio continua a dire di dovere aiutare lo scienziato, anche dopo averlo già salvato.

**Comment by fabstarkey** [comment]
Grazie per la segnalazione!
