### ISSUE TITLE
"Script 'PokemonFollow' line 293: NoMethod occurred" AIUTATEMI PERFAVORE

### ISSUE THREAD

**Issue by Patrickso99** [fuji97/pokemon-xenoverse-tracker#407]
Quando clicco su "continua" mi appare questo:

![30360253-9914d28a-9850-11e7-977f-97c875d91b70](https://user-images.githubusercontent.com/31846151/30439549-672dcbda-9974-11e7-9ef3-c141cc95a40a.PNG)

cosa devo fare? Non voglio cancellare il salvataggio perchè sono quasi alla fine del gioco e cancellare i dati dopo tante ore di gioco e quasi alla fine mi sembra un'ingiustizia

p.s. tutto questo mi è successo dopo aver installato la patch 1.0.1

**Comment by fabstarkey** [comment]
Tra poco uscirà la nuova patch, prova a scaricarla, se l'errore persiste, ricontataci
