### ISSUE TITLE
Errori di battitura e testi generali

### ISSUE THREAD

**Issue by LeoPantaniHD** [fuji97/pokemon-xenoverse-tracker#41]
In un testo in particolare, quando Elisio si trova nel laboratorio che ti fornisce il pokemonwes (credo?) è presente un errore di battitura: https://i.imgur.com/J4FpVRq.jpg.

Inoltre diversi testi hanno doppi spazi, non che sia un problema grave, ma dovrebbe essere facilmente risolvibile, con notepad++ basta aprire i intl.txt si mette sostituisci (  ) con ( ) e problema risolto. A meno chè non ci siano doppi spazi messi apposto nel file di traduzione.

Grazie per la lettura e fantastico gioco ancora!

**Comment by fuji97** [comment]
Grazie per la segnalazione, risolveremo il prima possibile
