### ISSUE TITLE
Bug Centro Pokemon

### ISSUE THREAD

**Issue by xSkyEaglex** [fuji97/pokemon-xenoverse-tracker#410]
Al primo centro pokemon se si cerca di far curare i propri pokemon crasha con il log sottostante
![3 - copia](https://user-images.githubusercontent.com/31965234/30440436-cf1186c2-9976-11e7-8a34-f47bbad6c50f.jpg)

**Comment by loltag22** [comment]
Avvia come amministratore il programma
