### ISSUE TITLE
bug palestra dolcetto

### ISSUE THREAD

**Issue by alessio00** [fuji97/pokemon-xenoverse-tracker#411]
Dopo aver finito di combattere contro druddigon mi crasha e mi da un errore. Allego screen per capire bene.
Aggiungo che si sente la musica di sottofondo........
![cattura1](https://user-images.githubusercontent.com/31782150/30440912-2ca86142-9978-11e7-967d-25ff43ccd4ca.PNG)

**Comment by andrewrov** [comment]
Bug già conosciuto e postato da varie (fin troppe) persone.
Prima di postare non guasterebbe dare un'occhiata se il problema sia nuovo o meno, altrimenti riempite gli sviluppatori di decine di domande uguali...

**Comment by fabstarkey** [comment]
Risolto nella patch che uscirà a breve :)
