### ISSUE TITLE
Dati pokedex beartic

### ISSUE THREAD

**Issue by drbick** [fuji97/pokemon-xenoverse-tracker#412]
Volevo solo far notare che i dati di beartic sono tuttora in inglese, magari possono esser sfuggiti in fase di traduzione.
![1505407813394-1859480327](https://user-images.githubusercontent.com/31858641/30442722-9389df4e-997d-11e7-9d22-5a20f9f36f7c.jpg)

**Comment by fabstarkey** [comment]
Risolto nella patch che uscirà a breve :)
