### ISSUE TITLE
EVOLUZIONI le quali nn conosco il livello

### ISSUE THREAD

**Issue by Lorenz0203** [fuji97/pokemon-xenoverse-tracker#413]
L' evoluzione di Yemin, Hikiloo e Jalapucha

**Comment by LeonidaXX1** [comment]
A me Yemin si è evoluto al 27 ma alcuni si evolvono da un certo livello, non per forza a quel livello. Continua a livellarlo, si evolve di sicuro come testimonia il mio Kungfur

**Comment by andrewrov** [comment]
Yemin livello 27
Hikiloo livello 35
Jalapucha tramite Pietrafocaia

**Comment by grouchality** [comment]
mi accodo: nunvil?

**Comment by Lorenz0203** [comment]
Grazie

**Comment by andrewrov** [comment]
Nunvil si evolve di notte se ha l'oggetti Tiara Proibita (almeno secondo i file di gioco)
