### ISSUE TITLE
Bug nella prova di pesca della palestra di Rochelle

### ISSUE THREAD

**Issue by LelouchZero** [fuji97/pokemon-xenoverse-tracker#414]
In sostanza ho riscontrato che durante la seconda prova nella palestra di Rochelle del regno caramello, nello specifico quella dell'acqua, dove si deve pescare il cucchiaio d'oro sul fondale, cercando di abbandonare la prova ( causa problemi di lag ) per poi ritentare, una volta usciti dalla sala della prova ( e chiudendo e riaprendo il gioco, ma non sono sicuro questa cosa abbia influito ), parlando col cavaliere che ci consente l'accesso alla prova, la prova in questione era stata catalogata come già risolta, e ho potuto affrontare Rochelle pur senza l'ausilio del cucchiaio.

**Comment by fabstarkey** [comment]
grazie per la segnalazione!
