### ISSUE TITLE
non riesco a istallare la versione 1.0.1

### ISSUE THREAD

**Issue by StoneMG** [fuji97/pokemon-xenoverse-tracker#415]
perche la versione 1.0.1 non si trova nel sito del dowload

**Comment by Absol99** [comment]
Perchè è stata rimossa per far posto alla 1.0.2 Anch'io sono bloccato all'oasi senza poter combattere con Gengar ma aspetto impaziente che esca 'sta benedetta patch

**Comment by GameWarrior251** [comment]
iDEM

**Comment by StoneMG** [comment]
Ok grazie

Il 15 set 2017 9:14 PM, "GameWarrior251" <notifications@github.com> ha
scritto:

iDEM

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fuji97/pokemon-xenoverse-tracker/issues/415#issuecomment-329874792>,
or mute the thread
