### ISSUE TITLE
Testi conversazioni migliorabili

### ISSUE THREAD

**Issue by Glustrod27** [fuji97/pokemon-xenoverse-tracker#416]
Salve, giocando a Xenoverse ho notato come nella quasi totalità dei dialoghi presenti l'ortografia sia assente o imprecisa.
Un semplice esempio:

"Ciao benvenuto al Pokémon Center [...]."
"**Ciao, benvenuto** al Pokémon Center [...]."

Se doveste aver desiderio di sistemare i dialoghi, sarei disponibile ad aiutare.

**Comment by fabstarkey** [comment]
sarà aggiustato nella patch ;)
