### ISSUE TITLE
Joele - v1.0.1

### ISSUE THREAD

**Issue by pgiao** [fuji97/pokemon-xenoverse-tracker#417]
Dopo aver accettato la richiesta di Joele, cambiando l'ordine dei pokemon in squadra mettendo lo starter per primo, Joele diventerà lo starter. Invece mettendo per primo qualsiasi altro pokemon, Joele sparirà.

![image](https://user-images.githubusercontent.com/31972527/30457228-e63bb270-99a6-11e7-90fc-304cfec74927.png)

**Comment by pgiao** [comment]
Inoltre, dopo aver sconfitto Gengar X Joele ci seguirà a tempo indefinito, sempre con lo sprite del primo pokemon vivo in squadra, per di più con la possibilità di parlargli e sfidarlo all'infinito (esperienza e soldi potenzialmente infiniti).

**Comment by fabstarkey** [comment]
Già risolto nella patch che uscirà a breve :)

**Comment by Patrickso99** [comment]
Io lo ho risolto così:

1) Estrai i salvataggi [ C:\Users\Patrick Reichert\Saved Games\Xenoverse ] fanne una copia e metti i due/tre file sul desktop
2) Disinstalla Xenoverse (COMPLETAMENTE)
3) Installa SOLO la versione 1.0.0 (quella base) [NON INSTALLARE ANCORA LE PATCH!!!]
4) Rimetti i salvataggi dentro la cartella [ C:\Users\Patrick Reichert\Saved Games\Xenoverse ]
5) avvia il gioco come amministratore (SEMPRE) e ti ritroverai nel gioco (probabilmente seguito dal tuo starter)
6) A questo punto, sostituisci il tuo primo pokemon con un altro a caso della tua squadra (L'IMPORTANTE E' CHE IL TUO STARTER NON SIA MESSO PER PRIMO)
7) Nel caso in cui lo sprite del pokemon non sia sparito, entra nella borsa, poi esci...entra nel pokedex e poi esci...entra nelle opzioni e poi esci....e continua a fare così fino a che lo sprite del pokemon che ti segue non sparisce
8) Se lo sprite sparisce SALVA IMMEDIATAMENTE e chiudi il gioco
9) Ripeti il primo punto (cancellando i vecchi salvataggi e facendo il backup di quelli nuovi)
9) Successivamente installa le patch 1.0.1 e 1.0.2 (se vuoi, una dopo l'altra)
10) Quando riaprirai il gioco, funzionerà tutto :)

p.s. questa guida l'ho inventata io a caso xD anch'io avevo lo stesso problema, poi ho ragionato e mi sono inventato questo e ha pure funzionato...spero di essere stato utile :)
