### ISSUE TITLE
Bug volo al Regno Caramello e all'Isola Voodoo

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#418]
Bug già lamentato pre-patch e anche post. Usando Volo per raggiungere il Regno Caramello, lo schermo è tutto nero, ma è comunque possibile raggiungerlo senza problemi procedendo a piedi. L'Isola Voodoo è invece raggiungibile solo tramite la Gemma-N e quindi il bug è un bel problema, si vede un rettangolo d'acqua sul lato sinistro mentre tutto il resto è nero, inoltre si direbbe che si rimane letteralmente bloccati perché, comunque si premano i tasti direzionali, comparirà quella specie di sbuffo come quando vai a sbattere contro una parete senza possibilità di procedere.

**Comment by fabstarkey** [comment]
Ciao! Volo è stato aggiustato nella patch che uscirà a breve :)
