### ISSUE TITLE
[INFO] Ricordamosse

### ISSUE THREAD

**Issue by NicoBaldi94** [fuji97/pokemon-xenoverse-tracker#419]
nella patch 0.1 c'è scritto che è stato aggiunto il ricordamosse. qualcuno sa dov'è di preciso?

**Comment by elvibllano** [comment]
Il ricordamosse si trova a Rocca Draconica.

**Comment by NicoBaldi94** [comment]
Grazie per l'info, ma ho parlato con tutti gli rpg e non ho trovato nessun ricordamosse...

**Comment by fabstarkey** [comment]
Lo troverai nella patch
