### ISSUE TITLE
Bug riscontrati

### ISSUE THREAD

**Issue by BaroneBirraX** [fuji97/pokemon-xenoverse-tracker#42]
Ho notato i seguenti bug giocando:
Vocalizzo viene colpito da statico, magari è voluto, ma non credo sia una mossa da contatto vocalizzo.
Se un pokemon avvelenato muore appare la scritta in inglese invece che in italiano.
Tenere premuta la 'Z' manda avanti i discorsi e se mentre si corre appare un personaggio che vuole parlare si rischia di perdere le prime parti del dialogo.
Spero di esservi stato d'aiuto!

**Comment by fuji97** [comment]
Grazie per la segnalazione, abbiamo già segnato tutto e verranno risolti il prima possibile
