### ISSUE TITLE
[CRASH] Sfida Trishout X

### ISSUE THREAD

**Issue by MattWolf96** [fuji97/pokemon-xenoverse-tracker#420]
Durante la sfida con il boss Trishout X appena mi viene messo k.o. Il primo pokemon e passo nel menù squadra per scegliere un sostituito si apre una finestra di dialogo con errori vari impedendo di sostituire il pokemon e proseguire. 
![img_20170915_110850](https://user-images.githubusercontent.com/31985217/30475531-7431ce74-9a07-11e7-9ec8-2e4710910edb.jpg)

**Comment by Metalcape** [comment]
Come ho scritto in un altra issue:

Non so se è già stato risolto, ma il bug del cambio pokémon durante la boss fight di Trishout X è molto banale, semplicemente lo scaleon di oleandro non è uno scaleon ma un altro pokemon (numero 943) e mancano gli sprite nelle cartelle graphics/icons e graphics/battlers. Basta andare in queste cartelle, copiare gli sprite di scaleon "normale" (numero 753) e nominarle icon943.png o 943.png a seconda del caso.
