### ISSUE TITLE
Bug battaglia sulla nave

### ISSUE THREAD

**Issue by Dvdshaman** [fuji97/pokemon-xenoverse-tracker#421]
Ho riscontrato questo bug: se si perde una battaglia sulla nave e il tuo ultimo luogo di cura è sull'isola bonita, quando si riorna dall'isola si rimane bloccati sul molo e se si parla con il capitano ber inmbarcarti si rimani bloccati in uno script di movimento; fortunatamente avevo salvato prima, ma questo bug credo sia un problema alquanto grave...

**Comment by fabstarkey** [comment]
Ciao! Il problema è stato aggiustato nella patch che uscirà a breve, ma con molta probabilità non riuscirai a sbloccare, il bug è in loop infinito, provaci se no devi rigiocarlo dall'inizio, ma essendo praticamente ad inizio gioco non dovrebbero esserci problemi a ricominciarlo! ci scusiamo per l'inconveniente :)
