### ISSUE TITLE
EVOLUZIONI POKEMON 

### ISSUE THREAD

**Issue by sow99** [fuji97/pokemon-xenoverse-tracker#422]
Electabuzz X si può evolvere in qualche modo in Electivire X?
Kadabra in che modo si può evolvere in Alakazam?

**Comment by andrewrov** [comment]
Kadabra al momento non si può ancora evolvere, hanno detto che con la parte 2 metteranno un modo per poter completare il pokedex anche senza scambi (che da quello che ho capito verrano anch'essi integrati) quindi dovrai aspettare.
Per Electabuzz X non è trapelato ancora nulla, comunque la versione normale richiedeva comunque uno scambio con Elettritore dato ad Electabuzz quindi mi sa che anche per lui dovrai aspettare

**Comment by andrewrov** [comment]
Anzi, mi correggo, qualcuno ha da poco postato che con Cucchiaio Torto dato a Kadabra si evolve facendolo salire di un livello

**Comment by fabstarkey** [comment]
Electabuzz X non si può evolvere nella parte 1. Per alakazam sei stato già risposto!

**Comment by sow99** [comment]
E dove posso trovare il cucchiaio torto?

**Comment by andrewrov** [comment]
In una casa nell'Oasi Cocente
