### ISSUE TITLE
C'E' STATO UN PROBLEMA CON I CODICI. IL GIOCO SARA' RIAVVIATO

### ISSUE THREAD

**Issue by StefanoRosa** [fuji97/pokemon-xenoverse-tracker#423]
prima il gioco appena entravo in partita crashava per un altro errore.. adesso ho riprovato e crasha ancora prima di arrivare al menù di gioco con questo errore
![cattura](https://user-images.githubusercontent.com/31822023/30485034-7c0173a0-9a2c-11e7-8477-456d899e6229.PNG)
![cattura](https://user-images.githubusercontent.com/31822023/30485075-93bc9524-9a2c-11e7-9780-67bd1aa2d348.PNG)

**Comment by fabstarkey** [comment]
Disinstallalo e riscaricalo..Non è un problema del gioco ma del tuo pc che probabilmente non legge qualche file, prova anche ad accedere a xenoverse come amministratore.
