### ISSUE TITLE
Bug Anello Xenoverse

### ISSUE THREAD

**Issue by JaoTheEmperor** [fuji97/pokemon-xenoverse-tracker#424]
Bug nato da dopo la battaglia contro la mia Nemesi nel mondo Xenoverse.

Ogni qualvolta sconfiggo un pokemon selvatico, mi rilascia un "anello Xenoverse" 
al momento sono a quota 15.
![immagine](https://user-images.githubusercontent.com/31991973/30486227-27ed3674-9a30-11e7-9cfc-5a230326ec98.png)

**Comment by NicoBaldi94** [comment]
succede anche a me!

**Comment by fabstarkey** [comment]
Risolto nella patch che uscirà a breve :)
