### ISSUE TITLE
Problema Evs/statistiche

### ISSUE THREAD

**Issue by q1w2e34** [fuji97/pokemon-xenoverse-tracker#425]
Allenando la squadra ho notato che bunnelby da punti abilità in difesa speciale. Controllando il file pokemon.txt ho notato che la statistica di velocità è in quarta posizione e per alcuni pokemon, che dovrebbero dare Evs in velocità, si ha invece un valore di effort points diverso da zero in ultima posizione. Per altri invece, per esempio zubat, il valore in effort points è diverso da zero in quarta posizione e i punti abilità ottenuti nel gioco sono corretti. 
Spero di essermi spiegato e complimenti per il gioco.

**Comment by fabstarkey** [comment]
Errore risolto nella patch che uscirà a breve :)
