### ISSUE TITLE
CRASH - Sfida Trishout X

### ISSUE THREAD

**Issue by Patrickso99** [fuji97/pokemon-xenoverse-tracker#426]
Durante la sfida con il boss Trishout X appena mi viene messo k.o. Il primo pokemon e passo nel menù squadra per scegliere un sostituito si apre una finestra di dialogo con errori vari impedendo di sostituire il pokemon e proseguire.

![bug](https://user-images.githubusercontent.com/31846151/30492818-1e045cf2-9a42-11e7-9cd9-6f39eeed9859.PNG)

**Comment by Zorua1280** [comment]
ho lo spesso problema!
