### ISSUE TITLE
(non riesco a risolvere) RGSS Player ha smesso di funzionare

### ISSUE THREAD

**Issue by Ic3Wol** [fuji97/pokemon-xenoverse-tracker#428]
Ogni volta che ho provato a reinstallare il gioco mi da sempre questo errore ho provato a cambiare cartella di installazione e ho provato ad aprirlo come amministratore. Vi prego sto vedendo la serie di Federic e più la vedo e più mi viene da giocare aiutatemi che se no divento come un drogato che non ha la droga.

**Comment by Patrickso99** [comment]
https://github.com/fuji97/pokemon-xenoverse-tracker

Vai in fondo alla paina e ti spiega cosa fare

**Comment by Ic3Wol** [comment]
lo so ma non capisco il secondo passaggio come si deve fare
