### ISSUE TITLE
Crash al Centro Pokémon di Ludopoli

### ISSUE THREAD

**Issue by Polygy** [fuji97/pokemon-xenoverse-tracker#43]
Quando tento di curare i Pokémon al CP di Ludopoli circa 4 volte su 5 il gioco va i crash e i appare questa schermata di errore.

![crash1](https://user-images.githubusercontent.com/31784770/30239643-9f16e6d8-9561-11e7-99ac-4796922fadd4.png)

Ho reinstallato il gioco e sembrava che il problema si fosse risolto. Invece 10 minuti dopo si è ripresentato.
Ecco le informazioni sul mio PC casomai servissero:

Sistema Operativo: Windows 7 Home Basic 32-bit
Processore: Intel Core 2 Duo CPU E4500 @2.20GHz
RAM: 4 GB

**Comment by Polygy** [comment]
Non avevo letto le  FAQ. 
Problema risolto.
Scusate.

**Comment by Nicola55** [comment]
Anche io ho riscontrato questo problema, però non so come risolverlo. :/

**Comment by robertosartori** [comment]
Io ho letto le FAQ, ma il problema andrebbe risolto lato sviluppatori. Il gioco non dovrebbe richiedere MAI i diritti di amministratore, se lo fa c'è qualcosa che non va. Temporaneamente basterebbe rilasciare un aggiornamento che obblighi il gioco ad avviarsi sempre con diritti elevati, così da evitare all'utente di cercare tra la FAQ.

**Comment by Polygy** [comment]
Non sono un esperto di queste cose, quindi non lo so. Hanno già risposto dicendo che nella prossima versione sarà risolto, quindi dobbiamo solo aspettare.

**Comment by robertosartori** [comment]
Bene, non sapevo che avessero detto questo.

**Comment by fuji97** [comment]
Già segnalato, abbiamo risolto per la prossima release
