### ISSUE TITLE
esperienza cala sempre di più

### ISSUE THREAD

**Issue by Jimmopolis** [fuji97/pokemon-xenoverse-tracker#432]
per ogni nuovo livello l'esperienza che i pokemon ottengono diminuisce. sono dopo il campus e far salire i pokemon con lotte nell'erba con avversari a stadio base inizia ad essere frustrante. Per favore risolvete

**Comment by andrewrov** [comment]
E' normale, più il pokemon è forte rispetto all'avversario meno esperienza prende
