### ISSUE TITLE
Victreebel

### ISSUE THREAD

**Issue by GaetanoTufariello** [fuji97/pokemon-xenoverse-tracker#433]
Sul file testo "pokemon" sono andato a vedere le statistiche base di Victreebel, e sono 80-105-65-70-100-60. Mentre sul sito bulbapedia le statistiche sono 80-105-65-100-70-70. Ora quale delle due statistiche base è giusta ?

**Comment by q1w2e34** [comment]
credo che in quel file la velocità è nella quarta posizione invece che nell'ultima, mentre quei 10 punti in meno in difesa speciale non so, forse sono per il cambio di generazione

**Comment by GaetanoTufariello** [comment]
sai se è possibile taggare uno dei creatori del game ? così da fare chiarezza

**Comment by q1w2e34** [comment]
non saprei, sono abbastanza sicuro di quello che ti ho scritto perchè ho controllato le statistiche di altri pokemon, l'unico problema si ha con le assegnazioni di alcuni Evs come ho segnalato in un post quì sotto

**Comment by fabstarkey** [comment]
Ciao! le statistiche saranno aggiornate con una patch in futuro.
