### ISSUE TITLE
Alice fin troppo ossessionata da me, (joke title)

### ISSUE THREAD

**Issue by SkareXI** [fuji97/pokemon-xenoverse-tracker#434]
Ero nel corridoio roccioso, appena iniziata la quest con Alice.
Per andare più veloce decisi di utilizzare l'overboard, e una volta fatto l'icona di alice è sparita, ma la sua ombra mi seguiva e se mi volto e premo C ci parlo anche se non c'è nessuno.
Ho pensato che una volta finita la quest il bug si sarebbe risolto da solo quindi sono andato avanti non curante. Il problema è che ho finito la quest e sono anche uscito dalla grotta ma il "fantasma" di Alice continua a "seguirmi" inoltre se metto lo starter al primo posto si sovrappone all'ombra e inizia a seguirmi.
Non so che fare e so che potrebbe causare problemi, quindi help me please!

**Comment by fabstarkey** [comment]
corretto nella patch che uscirà molto presto! :)
