### ISSUE TITLE
Personaggi trasformati in starter?

### ISSUE THREAD

**Issue by DragonX93** [fuji97/pokemon-xenoverse-tracker#435]
Partiamo dalla missione nel Corridoio Roccioso: Alice si unisce a me per combattere il team Dimension (fin qui tutto ok), poi dopo una battaglia (non ricordo se era contro allenatore o Pokemon selvatici) lo sprite di Alice dietro di me scompare e al suo posto c'è quello del mio starter Trishout (questo appare solo se il pokemon è primo in squadra, se lo sposto lo sprite dietro scompare, e ricompare se lo rimetto primo).
Se "parlo" con lui viene fuori il dialogo di Alice.
Una volta completata la missione, Alice si è separata da me, ma lo sprite dello starter continua a seguirmi e viene sempre lo stesso dialogo quando "parlo" con lui.
Questo rimane anche fuori dalla grotta, fino all'Oasi Cocente.

Arrivato all'oasi c'è la guardia che chiede il mio aiuto e si unisce a me e, magicamente il suo sprite si trasforma in un altro Trishout T che mi segue! 
Il risultato finale è questo:
![screenshot 4](https://user-images.githubusercontent.com/31856559/30504827-386ef9e2-9a71-11e7-8369-011123916191.png)
![screenshot 7](https://user-images.githubusercontent.com/31856559/30504831-3d4aabb4-9a71-11e7-9325-c18ead63b801.png)
![screenshot 8](https://user-images.githubusercontent.com/31856559/30504834-421d56f0-9a71-11e7-9b70-9aacebb87a29.png)

Ho provato a chiudere e riaprire il gioco (avevo salvato appena arrivato all'oasi) ma la situazione rimane la stessa

**Comment by DragonX93** [comment]
Altra cosa: Anche se cambio posizione allo starter e quindi non ho nessuno dietro posso lo stesso parlare con i personaggi che mi seguono anche se non si vede nessuno (in pratica parla al vuoto)

**Comment by fabstarkey** [comment]
corretto nella patch che uscirà molto presto! :)
