### ISSUE TITLE
in quale carttella sono allocti i salvataggi?

### ISSUE THREAD

**Issue by reijeix** [fuji97/pokemon-xenoverse-tracker#44]
ho un problema, ho dovuto cambiare computer  quindi ho fatto una un copia dl gioco su pennina usb, il gioco parte ma non capisco perchè non mi trova i salvataggi, io ho copiato tutta la cartella pokemon xenovers facendo apri percorso file. nel vecchio coputer dove poso trovarli?

**Comment by fuji97** [comment]
I salvataggi sono in "Partite Salvate", la cartella "Xenoverse"
