### ISSUE TITLE
Bug pokedex e terza palestra

### ISSUE THREAD

**Issue by Tetsu93** [fuji97/pokemon-xenoverse-tracker#440]
Quando entro nella terza palestra dopo la prima sfida il gioco mi crasha sempre.

Se apro il pokedex e controllo la scheda di un qualsiasi pokemon il gioco crasha

**Comment by tonynart** [comment]
anche io ho riscontrato lo stesso problema del Pokédex... Al momento conviene non aprirlo, sicuramente risolveranno col prossimo aggiornamento

**Comment by Tetsu93** [comment]
Per ora nn è un problema grave x me il pokedex, tanto nn sto lì a cercare tutti i pokemon della zona finché nn finisco il gioco ma se mi crasha il gioco con la prima prova della terza palestra sono bloccato xD
