### ISSUE TITLE
Problema in statistiche Trishout-T (forse)

### ISSUE THREAD

**Issue by SkareXI** [fuji97/pokemon-xenoverse-tracker#441]
Appena arrivato a prendere l'anello terrestre per il mio trishout e una volta cambiata la sua forma la statistica di attacco speciale cambia in peggio, diventanto inferiore.
Non ho idea se sia normale come cosa, mi sembra un po' strana più che altro siccome la forma T dovrebbe sostituire un "evoluzione" 
Vorrei un parere anche da altri giocatori che hanno scelto Trishout come starter oppure se anche con gli altri starter funziona in questo modo, grazie. :)

**Comment by Tetsu93** [comment]
Io ho trishout e con l'anello l'attacco speciale mi aumenta di circa 20 punti

**Comment by SkareXI** [comment]
Quindi è un problema di distribuzione delle statistiche, grazie dell'informazione :)

**Comment by LeonidaXX1** [comment]
Ho provato entrambi gli anelli per Trishout e per entrambi le statistiche aumentano, non c'è una sola che diminuisca durante l'evoluzione terrestre o Xenoverse, in particolare quella terrestre fortifica l'attacco speciale mentre quella Xenoverse l'attacco fisico, ma nessuna statistica scende

**Comment by SkareXI** [comment]
Mi consigliate di riniziare il gioco per vedere se si aggiusta o di aspettare una patch?

**Comment by LeonidaXX1** [comment]
Io ti consiglio di continuare a giocare e tenerlo nella forma che meglio bilancia il potenziale del pokémon. Per esempio, se ha le mosse speciali più potenti di quelle fisiche, per equilibrare scegli la forma che ha più attacco fisico. Non serve a niente aumentare l'a.s. se conosce Lanciafiamme e poi con Rogodenti, che è fisico, non fa molti danni. Chiaramente vale anche l'inverso, devi vedere tu il suo move set e quale è la forma più indicata.
