### ISSUE TITLE
Crash dopo prova fuoco al castello

### ISSUE THREAD

**Issue by sbambato** [fuji97/pokemon-xenoverse-tracker#442]
Ciao, segnalo il crash al castello. Non appena si batte Druddigon, quando dovrebbe ritornare la schermata nel castello, il gioco si chiude con un errore simile a quelli che appaiono quando non si avvia il gioco come amministratore.
Leggendo sembrerebbe un errore nella "creazione del bitmap"

Ecco la foto dell'errore 
https://ibb.co/h4VAdk

**Comment by AkeRoss** [comment]
questo bug è stato segnalato già un miliardo di volte lo stanno sistemando, con la patch 1.0.2 penso che si risorverà

**Comment by sbambato** [comment]
Si si, l'ho segnalato solo perché ho notato che è stato segnalato in altri luoghi, tutto qua.. aspettiamo volentieri :)

**Comment by morethenless** [comment]
Io avevo lo stesso problema, ho disinstallato e reinstallato la versione 1.0.0 senza patch, ora funziona!
