### ISSUE TITLE
2 bug nella mappa dell'arcipelago vodoo

### ISSUE THREAD

**Issue by AndrewRicc01** [fuji97/pokemon-xenoverse-tracker#45]
Nella zona di terra in alto a destra si può passare dal tileset dell'erba a quello della sabbia senza che ci sia una scala. In una zona in basso a destra si presentano un gruppo di fiori e risulta impossibile passare sopra quello rosso.

**Comment by fuji97** [comment]
Hai uno screen per farci vedere precisamente il posto?

**Comment by SHerluu** [comment]
Io  ho uno screenschot del secondo bug che is può trovare all' arcipelago Vodoo, però  non mi è venuto proprio bene, nonostante ciò spero sia abbastanza per favi capire dove si trovi il luogo preciso del bug.
![image](https://user-images.githubusercontent.com/31817777/30248528-c03b7aea-9629-11e7-8174-2c391572214d.png)
.

**Comment by fabstarkey** [comment]
corretto
