### ISSUE TITLE
Scaleon dove sei?!

### ISSUE THREAD

**Issue by Vineri** [fuji97/pokemon-xenoverse-tracker#451]
Il mio Scaleon ,dopo avere sconfitto il Trishout forma Xenoverse, è stato rimosso dal mio team e, non trovandosi nel mio pc, credo che sia stato liberato o che il gioco abbia rimosso tutti gli Scaleon nel team, quindi sia il mio che quello che mi era stato prestato per la battaglia.

**Comment by ironuser96** [comment]
Successo anche a me una cosa simile, praticamente il mio è stato "eliminato" e sostituito con quello di oleandro, dopo aver sconfitto il Trishout forma Xenoverse.
![scaleon](https://user-images.githubusercontent.com/32003879/30513791-a53c1850-9b09-11e7-995d-c764688ea74e.png)

**Comment by Raffy1399** [comment]
io ho scaricato anche le patch ma niente scaleon no c'è
