### ISSUE TITLE
Problema centri pokemon 

### ISSUE THREAD

**Issue by cicciosandrone** [fuji97/pokemon-xenoverse-tracker#452]
In quasi tutti i centri pokemon che ho visitato, al momento della cura (dopo dialogo con infermiera) il gioco crasha.  
![errore xenoverse](https://user-images.githubusercontent.com/32015793/30512536-fc06fee2-9af1-11e7-887b-fb69274ed339.jpg)

**Comment by Vineri** [comment]
Leggi i commenti lasciati da Weedle sotto al video del download. Lì trovi come risolvere il problema

**Comment by cicciosandrone** [comment]
Grazie!

**Comment by ivanfgk** [comment]
Corretto nella patch 1.0.2
Saluti
