### ISSUE TITLE
Quali sono i luoghi dove posso far evolvere Elekid X?

### ISSUE THREAD

**Issue by Patrickso99** [fuji97/pokemon-xenoverse-tracker#456]
Potreste mettere immagini dei luoghi dove si può evolvere?

con un'immagine sarebbe meglio

**Comment by tonynart** [comment]
se non erro al percorso 5. dovrebbe esserci un albero viola

**Comment by Patrickso99** [comment]
Grazie mille!!

**Comment by LeonidaXX1** [comment]
I nomi dei percorsi non me li ricordo, comunque ci sono al momento due alberi oscuri, il primo sta nel percorso a est del Regno Caramello, il percorso accessibile subito dopo aver battuto Rochelle - appena ci arrivi ti raggiunge Ezio e ti conduce là -, mentre il secondo è quello a ovest dell'Oasi Cocente, quello dopo essere uscito fuori dal Corridoio Roccioso, per intenderci, si trova sul lato nord di questo percorso
