### ISSUE TITLE
Fino al Campus Acero senza medaglia radice

### ISSUE THREAD

**Issue by Sburanga** [fuji97/pokemon-xenoverse-tracker#46]
Segnalo una probabile svista nella storia: subito dopo aver catturato Elekid X sono tornato sulla spiaggia lucente per cercare oggetti e allenatori. Parlando prima col marinaio di destra e poi con il capitano però sono riuscito ad imbarcarmi sulla nave SENZA aver battuto la palestra e senza il pokèWES (per altro senza volerlo ahahah). Da lì in poi il gioco è andato avanti senza contrattempi, riuscendo pure ad attivare l'oleogramma di Trapinch per spaccare le rocce.
Una volta scacciato il team malvagio al campus Acero sono riuscito a tornare con la nave a spiaggia lucente, ottenere la medaglia e andare sull'isola Bonita, come immagino dovesse essere normalmente.
Infine, ma non so se questo dipenda dal mio salto temporale nella storia, segnalo anche un bug presente nel passaggio che collega il Campus al percorso 4: dal lato del Campus è possibile camminare sopra il tetto del passaggio, andando fino alla "zona nera". Se necessario allego screen, fatemi sapere!

**Comment by fuji97** [comment]
Grazie per la segnalazione, vedremo se c'è qualche condizione che ci siamo persi in giro
Per il secondo bug del tetto, se hai uno screen ci faresti un piacere, grazie

**Comment by Sburanga** [comment]
Scusate il ritardo nella risposta. Il piccolo bug capita quando si va con il personaggio nel "palo" superiore del passaggio (vedi primo screen)
![bug_passaggio1](https://user-images.githubusercontent.com/31780069/30248326-df542070-9625-11e7-892a-b38252db9782.PNG)
![bug_passaggio2](https://user-images.githubusercontent.com/31780069/30248328-df597b38-9625-11e7-8a16-9a0e582af948.PNG)
![bug_passaggio3](https://user-images.githubusercontent.com/31780069/30248327-df571e56-9625-11e7-9afb-43a4625ceb2a.PNG)
