### ISSUE TITLE
Mancanza evento teletrasporto nave

### ISSUE THREAD

**Issue by LeoPantaniHD** [fuji97/pokemon-xenoverse-tracker#47]
Nella nave all'inizio della storia (non ricordo il nome), non è possibile entrare in una stanza senza alcun messaggio che mi dica il motivo, quindi presumo non sia voluto. Attenzione, non quella chiusa a chiave!

Screen: https://i.imgur.com/4gGmGXx.jpg

Altro errore di battitura nella nave, nella cucina: https://i.imgur.com/DYpE24g.jpg

**Comment by fuji97** [comment]
E' normale, non preoccuparti
