### ISSUE TITLE
BUG dopo 3° palestra

### ISSUE THREAD

**Issue by BullFlower** [fuji97/pokemon-xenoverse-tracker#473]
Anche scaricando la patch 1.0.2 mi si è ripresentato il problema di prima, cioè quello che dopo la 3° palestra non mi cattura più pokemon , anche quelli dei percorsi precedenti... cosa faccio?? provo a disinstallare tutto e reinstallare D: ???

**Comment by ivanfgk** [comment]
Sì, ricomincia perché il problema è risolto, mi dispiace.
Grazie
