### ISSUE TITLE
Bug mosse Trishout X

### ISSUE THREAD

**Issue by DrBoom123** [fuji97/pokemon-xenoverse-tracker#474]
Al 46 non impara infrasuono credo stia seguendo le mosse di Pancham infatti impara la mossa monito al 45. Nelle altre forme non impara niente ne al 45 ne al 46. Ho provato sia prima che dopo le patch
![immagine](https://user-images.githubusercontent.com/32022839/30515686-12131a50-9b2d-11e7-9c86-32945b2cd33b.png)

**Comment by ivanfgk** [comment]
e' corretto, al 50 impara infrasuono
