### ISSUE TITLE
alberi 

### ISSUE THREAD

**Issue by Harry11111111** [fuji97/pokemon-xenoverse-tracker#48]
Nel percorso per arrivare a Ludopoli se si passa vicino agli alberi di corsa ad un certo punto gli si passera sopra (in primo piano rispetto agli alberi)

**Comment by fuji97** [comment]
Ci servirebbe lo screen del punto preciso, grazie

**Comment by Harry11111111** [comment]
Certo, però non so come si fa il video dello scermo o lo screen mi potreste dire come fare!

**Comment by Harry11111111** [comment]
ed in più conpentro nelle roccie quella vicino a dove c'era il signor marino.

**Comment by fabstarkey** [comment]
risolto tutto!
