### ISSUE TITLE
Risposte "Sì" e "No" ancora non visualizzate.

### ISSUE THREAD

**Issue by Gengarden** [fuji97/pokemon-xenoverse-tracker#487]
E' ancora impossibile visualizzare le risposte "Sì" e "No" dopo l'uscita della versione 1.0.2.

**Comment by DartFeld92** [comment]
Se vai nella cartella dove è stato installato il gioco, nella sottocartella Fonts trovi tutti quello che serve. Seleziona i vari file, fai click destro ed installa.

**Comment by LeonidaXX1** [comment]
Non dipende dalla versione del gioco ma dai fonts installati. In genere li installa in automatico il gioco, se ti accorgi che mancano delle scritte, vai nella cartella di Xenoverse, poi apri Fonts, selezionali tutti, fai col tasto destro e scegli Installa

**Comment by tonynart** [comment]
Quoto quanto detto detto, se non installi manualmente alcuni font presenti nella cartella di Xenoverse, non appariranno MAI quelle scritte.

**Comment by Gengarden** [comment]
Grazie
