### ISSUE TITLE
Bug Volo si ripresenta anche in 1.0.2, e altri bug minori

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#488]
Ribadisco il bug che ho già riscontrato nella v. 1.0.1 per quanto riguarda l'Icarium-N usato per Regno Caramello e Isola Voodoo. Per praticità, elenco anche altri bug che ho notato:
Icone della Premier Ball e della Rete Ball invertite, l'MT34 è Fangonda e ne ha la descrizione, ma è chiamata Sanguisuga e come tale è considerata , icone dei Circuiti Poké e Velox Ball assenti, crash del gioco all'apertura del Pokédex, compare il messaggio "Pokémon ricevere Strumento" anche se quello strumento glielo sto togliendo.
In ultimo, questi sono i bug che ho trovato, ma nella 1.0.2 sicuramente c'erano dei bug aggiustati di cui non mi sono accorto, qualcuno potrebbe dirmi cosa è stato sistemato?

**Comment by fabstarkey** [comment]
il bug del volo verrà rilasciato nella 1.0.3 come abbiamo scritto recentemente.
