### ISSUE TITLE
Bambino Gaetano

### ISSUE THREAD

**Issue by grouchality** [fuji97/pokemon-xenoverse-tracker#489]
Dubbio: per il bambino di nome Gaetano fuori dalla grotta rocciosa esiste una qualche quest per il recupero del suo hippopotas?
Nel caso, anche dopo diversi passaggi non si triggera.

**Comment by fabstarkey** [comment]
Non è una quest! E' un dialogo che crea un collegamento all'arrivo dell'oasi cocente.
