### ISSUE TITLE
AIUTO EVOLUZIONI

### ISSUE THREAD

**Issue by Patrickso99** [fuji97/pokemon-xenoverse-tracker#490]
come si evolvono questi pokemon?

Weepinbell -> Victreebel? (se con la pietra foglia, dove si trova?)

Dove si trova Mareep?

Bugbug -> Herchinsect?

Golbat -> Crobat?

Dove si trova la forma base di Ninjask?

Murkrow -> Hounchkrow?

Dove si trova Misdreavus?

Dove si trova Carvanha?

Chigami -> Grudako?

Hikiloo -> Mylomute?

Galidler -> Meowgalo?

Glalie -> Froslass?

Sneasel -> Weavile?

Graveler -> Golem?

Onix -> Steelix?

Gurdur -> Conkeldur?

Kidoon -> Honchen?

Haunter -> Gengar?

Scyther -> Scisors?

Jalapucha -> evoluzione?

Kadabra -> Alakazam?

Dove si trova Elekid (normale)?

Boldore -> Gigalith?

Dove si trova la forma base di Loudred?

Magneton -> Magnezone?

Roselia -> Roserade?

Machoke -> Machamp?

**Comment by fabstarkey** [comment]
Il gioco non è finito, ergo molte evoluzioni e altre forme basi le troverai nella parte 2. Chiudo :)
