### ISSUE TITLE
statico

### ISSUE THREAD

**Issue by congzhouye** [fuji97/pokemon-xenoverse-tracker#5]
la probabilità di trigger dell'abilià statico è del 30% ma sparkowl triggera statico 6volte su 10 quindi il doppio di quello che dovrebbe essere,questo accade su bellsprout e trishout,proverò con altri pokemon

**Comment by fuji97** [comment]
La probabilità è un argomento molto spinoso, ci buttiamo un occhio, ma potrebbe comunque essere una casualità
