### ISSUE TITLE
[1.0.2] Bug enorme nella battaglia contro Trishout X

### ISSUE THREAD

**Issue by AkeRoss** [fuji97/pokemon-xenoverse-tracker#500]
se si tenta di cambiare pokemon durante la battaglia o se si deve cambiare perché esausto quello che ci stava prima appare un messaggio

![immagine](https://user-images.githubusercontent.com/31889879/30520805-364a5e78-9bb5-11e7-8ad4-48d6378991d2.png)

dopo di che rimane per sempre nella schermata di scelta del pokemon, questo nel caso finisca ko il pokemon che ci stava prima, mentre nel caso si cambia pokemon durante la lotta rimane sempre quella schermata di cambio pokemon ma si può ancora scegliere che mossa fare ma solo una perche poi rimane per sempre come l' immagine che metterò sotto

![nuova immagine bitmap 3](https://user-images.githubusercontent.com/31889879/30520839-9ea8eec6-9bb5-11e7-8fc8-0fdef63a67c7.png)

poi se provo ad usare uno strumento di cura mi da questo errore (non ho visto se sia lo stesso di prima) che mi appare sempre appena dopo la comparsa della schermata di scelta del pokemon al quale dare la cura

![immagine](https://user-images.githubusercontent.com/31889879/30520939-3c991e0c-9bb7-11e7-914c-a853ff384865.png)

e non si può neanche catturare , ma non so se sia un bug questo

il gioco lo avvio sempre in  modalità amministratore

**Comment by AkeRoss** [comment]
il gioco lo avvio sempre in modalità amministratore

**Comment by andrewrov** [comment]
Confermo, pure a me lo stesso problema
![error](https://user-images.githubusercontent.com/7448332/30521049-0d5e047a-9bb9-11e7-8e32-65e4ca163a95.PNG)

**Comment by AkeRoss** [comment]
però se si riesce a batterlo senza che riesca a metterti ko il pokemon con cui inizi la battaglia e se non si usano strumenti il gioco non presenta poi nessun problema

**Comment by andrewrov** [comment]
Ho appena notato un metodo per "risolvere", ovvero dal SelfChensey se si ritira un sesto pokemon ti permetterà di combattere e fare cambi, però l'ultimo pokemon avrà le mosse dello Scaleon che avresti dovuto ottenere... 
Però una volta battuto Trishout X e visti i titoli di coda si ha nuovamente 6 pokemon e quello ritirato è "tornato nei box", però andando a controllare al suo posto sembra non esserci nulla. Provando ad andare nel suo slot il gioco va in crash.
Io nel dubbio per evitare di corrompere il salvataggio aspetto a fare l'ultimo combattimento ma è essenziale risolvere questo bug

**Comment by AkeRoss** [comment]
io l' ho battuto con 5 pokemon in squadra riuscendo ad usarne solo uno e tutto è andato bene anche dopo la lotta
