### ISSUE TITLE
Non si possono più catturare pokemon

### ISSUE THREAD

**Issue by drz95** [fuji97/pokemon-xenoverse-tracker#508]
Ero arrivato al regno caramello, era appena uscita la patch 1.0.1 la installai, e battendo druggigon come prova del regno caramello usciva una finestra di errore e mi faceva chiudere il gioco, questo l ho risolto reinstallando la versione 1.0.0 del gioco, successivamente battuta la prova di druggigon reinstallai la patch 1.0.1,da qui tutto bene, se non fosse che adesso non mi fa più catturare pokemon, quando lancio una pokeball nel gioco dice"questo pokemon non può essere catturato" e son bloccato così, ieri ho installato la patch 1.0.2 ma niente. è risolvibile? giacchè che ci sono, potete aggiungere qualcosa per far evolvere gravaler in golem? Grazie.

**Comment by DARKRAYTA** [comment]
I pokemon come Diglett non possono essere catturati per via della loro abilità "trappoarena", neanche il Gengar dell'oasi per questioni di storia e non ho capito bene ma credo anche chi trovi con l'amo mentre esegui il minigioco o forse sto avendo anch'io lo stesso bug nell'ultimo caso.

**Comment by drz95** [comment]
Non mi fa catturare in nessun posto ho riprovato nel bosco filante adesso vado oltre il regno caramello e vedo questo "bug" é successo dopo il messaggio di errore detto sopra. Così sono bloccato

**Comment by drz95** [comment]
risolto
