### ISSUE TITLE
[1.0.2] Schermo nero se si vola alla Nave Abbandonata

### ISSUE THREAD

**Issue by AkeRoss** [fuji97/pokemon-xenoverse-tracker#518]
![immagine](https://user-images.githubusercontent.com/31889879/30522459-98f3807a-9bd0-11e7-843c-b3b582399c85.png)

**Comment by andrewrov** [comment]
Problema noto, ci sono alcuni posti in cui il volo è buggato, in teoria sistemano con la prossima patch
