### ISSUE TITLE
pokemon vintaige

### ISSUE THREAD

**Issue by Harry11111111** [fuji97/pokemon-xenoverse-tracker#52]
Scusate volevo sapere per trasferire il pokemon vintaige come si fà in più la mia demo non si apre  dice che è impossibile trovare RGSS102l.dll. come faccio? in più ci sono altri pokemon trasferibili  nella demo la forza di uno e dell' apha ( non possso abrire nemmeno la seconda demo e mi dice lo stesso messaggio) come faccio ad usarle per catturare e trasferire i pokemon dalle demo al gioco?

**Comment by fuji97** [comment]
Non si possono trasferire Pokémon dalla demo alla parte 1
