### ISSUE TITLE
Quali pokémon fanno droppare Perla dopo essere stati sconfitti?

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#525]

**Comment by KetsubanZero** [comment]
Di norma pokemon tipo shellder e clamperl dovrebbero dropparla, ma non so se ci sono (shellder credo di si)

**Comment by LeonidaXX1** [comment]
Shellder c'è ma come Pokémon così, in giro, non si trova da combattere. Comunque ho risolto, occasionalmente le droppi da Sandyghast. Passo e chiudo!
