### ISSUE TITLE
Cura automatica

### ISSUE THREAD

**Issue by LorasMastark** [fuji97/pokemon-xenoverse-tracker#54]
Mettendo piede nel centro Pokémon di Ludopoli dopo aver visitato Isla Bonita mi si è attivata la cura dei Pokémon, da sola, mentre ero ancora sulla soglia.

**Comment by fuji97** [comment]
Ha causato dei problemi successivamente?

**Comment by LorasMastark** [comment]
Mi è capitato una sola volta

**Comment by fuji97** [comment]
Va bene, grazie per la segnalazione
