### ISSUE TITLE
Quando uscirà la patch 1.0.3?

### ISSUE THREAD

**Issue by Eniws** [fuji97/pokemon-xenoverse-tracker#540]
Avrei due domande da chiedere:
1)quando uscirà la patch 1.0.3? Essendo 1 settimana che non riesco a giocare a pokemon xenoverse perchè bloccato all'evento di Gengar e questo non si risolve con le nuove patch anzi mi da pure un problema che non mi fa giocare.
![immagine](https://user-images.githubusercontent.com/31970394/30523169-e173f4d6-9bdc-11e7-9b1e-2bb679a62311.png)

2)qualcuno sa risolvere questo bug o lo ha risolto?

**Comment by Patrickso99** [comment]
Io lo ho risolto così:

1) Estrai i salvataggio, fanne una copia e mettii due/tre file sul desktop
2) disinstalla Xenoverse (COMPLETAMENTE)
3) Installa SOLO la versione 1.0.0 (quella base) [NON INSTALLARE ANCORA LE PATCH!!!]
4) Rimetti i salvataggi dentro la cartella "partite salvate"
5) avvia il gioco come amministratore (SEMPRE) e ti ritroverai nel gioco (probabilmente seguito dal tuo starter)
6) A questo punto, sostituisci il tuo primo pokemon con un'altro a caso della tua squadra (L'IMPORTANTE E' CHE IL TUO STARTER NON SIA MESSO PER PRIMO)
7) Nel caso in cui lo sprite del pokemon non sia sparito, entra nella borsa, poi esci...entra nel pokedex e poi esci...entra nelle opzioni e poi esci....e continua a fare così fino a che lo sprite del pokemon che ti segue non sparisce
8) Se lo sprite sparisce SALVA IMMEDIATAMENTE e chiudi il gioco
9) Successivamente installa le patch 1.0.1 e 1.0.2 (se vuoi, una dopo l'altra)
10) Quando riaprirai il gioco, funzionerà tutto :)

p.s. questa guida l'ho inventata io a caso xD anch'io avevo lo stesso problema, poi ho ragionato e mi sono inventato questo e ha pure funzionato...spero di essere stato utile :)

**Comment by Eniws** [comment]
Grazie mille ora il follow è rimasto però sono riuscito a avviare l'evento
di gengar!!


2017-09-17 20:07 GMT+02:00 IvanFGK <notifications@github.com>:

**Comment by Patrickso99** [comment]
Sono felice di esserti stato d'aiuto :D
