### ISSUE TITLE
Impossibilitato a catturare Pokémon

### ISSUE THREAD

**Issue by Durren-it** [fuji97/pokemon-xenoverse-tracker#56]
Dopo l'evento della terza palestra non mi è più possibile catturare pokémon selvatici, credo il motivo sia per l'evento presente in tale palestra, che però persiste anche dopo essere uscito dalla palestra.
![bug2](https://user-images.githubusercontent.com/31782838/30240761-85ba6a4c-9576-11e7-8469-e99f80a56bb3.png)

**Comment by fuji97** [comment]
Grazie per la segnalazione, abbiamo risolto per la prossima release
