### ISSUE TITLE
Bug squadra e lotte dopo Reset

### ISSUE THREAD

**Issue by Sang012** [fuji97/pokemon-xenoverse-tracker#57]
Ciao
Dopo aver iniziato una nuova partita, siccome la Natura del mio Shulong era pessima e non avevo salvato nella camera da letto prima dell'ottenimento dello starter, nel menù non appare l'opzione per vedere il team e non mi è possibile né trovare pokemon selvatici nell'erba alta, né lottare contro allenatori, che dopo avermi visto hanno il dialogo pre-lotta, ma questa non parte, e ripassando davanti a loro continua ad accadere la stessa cosa. È un mio problema o è un bug del gioco?

**Comment by Sang012** [comment]
Problema risolto reinstallando il gioco. A quanto pare non avevo ottenuto lo starter per qualche motivo. Chiudo

**Comment by fuji97** [comment]
Lascialo aperto che è comunque un problema, cercheremo di evitare che possa riaccadere ad altre persone
