### ISSUE TITLE
chigami e jalapucha non si evolvono :(

### ISSUE THREAD

**Issue by akiraco** [fuji97/pokemon-xenoverse-tracker#575]
arrivato al livelli 35 e oltre il piccolo chigami non si vuole ancora evolvere stessa cosa per jalapucha dopo al 40 è ancora lì

**Comment by q1w2e34** [comment]
chigami si evolve solo se impara ultimo canto, per jalapucha invece ci vuole una pietra

**Comment by akiraco** [comment]
ah. avevo seguito le info rilasciati sul canale, quindi può essere che siano cambiate anche altre evoluzioni a questo punto, bene a saperlo  almeno non porto jalapucha al 60 aspettando che si evolva ahahah
