### ISSUE TITLE
Patch 1.0.3 chiarimenti

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#577]
Mi sono accorto casualmente che c'è già la patch 1.0.3. Quali sono le novità di questa sistemata?

**Comment by q1w2e34** [comment]
dopo averla installata c'è un file con il changelog, te lo incollo:
Aggiunte:
- Aggiornati alcuni strumenti con artwork in HD.
- Nella macchina cura Pokémon ora verranno visualizzate solo Pokéball classiche.
- Sostituito Mr. Bug con una soluzione automatica.
- Aumentate probabilità di incontro di Houndoom e Trampille.

Fix:
- Corretti alcuni permessi nelle mappe.
- Corretto un problema che causava il crash del gioco quando il giocatore curava i Pokémon al Centro Pokémon.
- Corrette le posizioni di volo

**Comment by LeonidaXX1** [comment]
Grazie. Peccato per l'effetto grafico delle Poké ball, certo, va bene se un pokémon catturato con una Mega Ball, nella grafica di quando viene curato fa vedere una Poké ball classica, ma le Xeno Ball sono totalmente diverse per grafica e per funzionalità, anzi a mio avviso l'artwork è figo...

**Comment by Absol99** [comment]
Però il bug dello starter Xenoverse c'è ancora...
