### ISSUE TITLE
Nessun avviso quando installo una nuova patch

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#583]
Quando ho scaricato la patch 1.0.1 mi era comparso un messaggio a video non appena ho caricato il salvataggio che mi avvisava di salvare nuovamente per applicare i cambiamenti, però né alla patch 1.0.2 e né alla 1.0.3 ho avuto messaggi del genere. E' una cosa normale? Perché continuo ad avere gli stessi bug su Volo per Regno Caramello e Arcipelago Voodoo e continuo a vedere gli sprite delle Premier Ball e delle Rete Ball invertiti, ma soprattutto continuare a crashare quando apro il Pokédex. Anche rivolgendomi a Mr. Bug lui mi risponde semplicemente che se ho problemi devo rivolgermi a lui. Devo fare qualcos altro per attivarlo o basta parlargli?

**Comment by lamasfoker** [comment]
Il messaggio di riavvio per applicare i cambiamenti dovrebbe apparire ad ogni aggiornamento. Prova a rifarlo, magari funziona. O in alternativa scarica il gioco completo già patchato e migra i salvataggi.

**Comment by LeonidaXX1** [comment]
Infatti non vedevo nessuno dei vantaggi della patch, in sostanza non venivano applicati gli effetti. Ho disinstallato e reinstallato tutte e tre le patch di fila e ha funzionato tutto a meraviglia, grazie!
