### ISSUE TITLE
Status di confusione

### ISSUE THREAD

**Issue by Sonotroppobello** [fuji97/pokemon-xenoverse-tracker#60]
In primis una domanda: ma la confusione è ancora al 50% di possibilità di colpirsi da solo come su pokemon x e y?(anche se matematicamente parlando a me succede nel 100% dei casi xD). il problema più grave è che il colpirsi da solo comporta la perdita di un terzo degli HP

**Comment by fuji97** [comment]
Grazie per la segnalazione, ci buttiamo un occhio e ti facciamo sapere

**Comment by xZekro51** [comment]
Il danno non è un bug, è dovuto alle stat del tuo Pokémon. Chiudo.

**Comment by Sonotroppobello** [comment]
Grazie per l'attenzione c:

Il 11 set 2017 8:03 PM, "Paolo" <notifications@github.com> ha scritto:
