### ISSUE TITLE
Crash post lotta Campeggiatrice percorso 5

### ISSUE THREAD

**Issue by Sburanga** [fuji97/pokemon-xenoverse-tracker#61]
Durante la lotta contro l'allenatrice in questione, usando braciere di Electrabuzz X contro il suo Beedrill, la schermata ha "zoomato" sul pokèmon avversario, come dopo ogni attacco, ma non è tornata all'inquadratura di base. A lotta conclusa il gioco ha dato la schermata di errore che vi allego crashando.

![avventuriera](https://user-images.githubusercontent.com/31780069/30240883-1415ba2e-9579-11e7-8aff-37bea57c7089.PNG)
![bug avventuriera](https://user-images.githubusercontent.com/31780069/30240884-1418306a-9579-11e7-9cdc-b9cf8869951c.PNG)

**Comment by fuji97** [comment]
Grazie per la segnalazione, risolveremo il prima possiible

**Comment by cloud90** [comment]
Non so se sia lo stesso errore... ma a me(l'errore si è presentato in modo diverso) sempre con la stessa allenatrice Ermia dopo aver concluso la lotta con successo,ho provato a parlarle ed ho avuto subito un errore con relativo crash del gioco! fortuna avevo salvato! XD ormai non faccio un passo se prima non salvo!
![bugcattura](https://user-images.githubusercontent.com/9502612/30251745-4d5dd814-9666-11e7-8479-7e9756895430.PNG)
