### ISSUE TITLE
errore associazione pokemon e pokedex

### ISSUE THREAD

**Issue by Evyck** [fuji97/pokemon-xenoverse-tracker#62]
segnalo che, catturato bremand sul percorso 2, nella descrizione esce un altro pokemon di tipo volante e spettro (ancora non so quale sia)

**Comment by silvioiolli** [comment]
Confermo, e aggiungo che nel pokedèx non è presente Bremand, nè visto nè catturato nonostante io lo abbia in squadra.

**Comment by silvioiolli** [comment]
Confermo, e aggiungo che nel pokedèx non è presente Bremand, nè visto nè catturato nonostante io lo abbia in squadra.

**Comment by fuji97** [comment]
E' già stato segnalato
