### ISSUE TITLE
Gioco crasha durante il cambio pkmn contro trishout X

### ISSUE THREAD

**Issue by Uncle1113** [fuji97/pokemon-xenoverse-tracker#624]
Come da titolo, il gioco crasha durante il cambio dopo che il primo pokemon va ko contro trishout X, e nel frattempo quest'ultimo continua ad attaccare al nulla. Come se non bastasse lo scaleon che mi avrebbe dovuto prestare Oleandro non è nemmeno nella lista.
Qui aggiungo anche il messaggio dell'errore:
---------------------------
Xenoverse
---------------------------
Exception: RuntimeError

Message: filename is nil

SpriteWindow:218:in `initialize'

Pokemon_Sprites:113:in `new'

Pokemon_Sprites:113:in `pokemon='

Pokemon_Sprites:99:in `initialize'

PScreen_Party:388:in `new'

PScreen_Party:388:in `initialize'

PScreen_Party:753:in `new'

PScreen_Party:753:in `pbStartScene_ebs'

PScreen_Party:751:in `each'

PScreen_Party:751:in `pbStartScene_ebs'

This exception was logged in 

C:\Users\Francesco\Saved Games/Xenoverse/errorlog.txt.

**Comment by Saint781** [comment]
Se hai un Mylomute con scendineve in squadra mettilo primo e scorri un pochino sotto nelle domande poste, ne ho pubblicata una dove spiego come batterlo se hai quel bug

**Comment by Uncle1113** [comment]
purtroppo non ho un mylomute o pokemon con quel tipo di mossa....
