### ISSUE TITLE
Alice è diventata Trishout T

### ISSUE THREAD

**Issue by MuSt4TT** [fuji97/pokemon-xenoverse-tracker#625]
Nel tunnel roccioso,dopo aver lottato contro una recluta del team dimension, Alice che mi seguiva si è "trasformata" in Trishout T, ho provato a riavviare il gioco ma il "bug" persiste (come potete vedere dallo screenshot) il problema è solamente dal punto di vista grafico, non so se si era già mostrato un problema di questo tipo,

![cattura](https://user-images.githubusercontent.com/32074729/30557611-2b523e5a-9caf-11e7-9374-142bd035ca52.PNG)

**Comment by zYoshi** [comment]
Hey ciao, hai già installato la patch 1.0.3?
Se sì, verso l'Oasi Cocente, poco più avanti, il bug dovrebbe risolversi automaticamente.
Se no, installala da xenoteam.it

**Comment by MuSt4TT** [comment]
Appena installata, dovrebbe essersi risolto tutto allora

**Comment by zYoshi** [comment]
Ok quindi l'issue può considerarsi chiusa. Clicca su "Close Issue" così agli sviluppatori di Xenoverse sarà più semplice trovare bugs non risolti tra le varie issues ;)
