### ISSUE TITLE
Bug Percorso 5

### ISSUE THREAD

**Issue by Eeveeon** [fuji97/pokemon-xenoverse-tracker#63]
Nel percorso 5 andando con il Pokeboard su un albero si sarà in grado di attraversarlo e camminarci sopra.
Allego immagini
![cattura](https://user-images.githubusercontent.com/31800067/30240926-fff67e56-9579-11e7-874e-ab31dfeccd6c.PNG)
![cattura1](https://user-images.githubusercontent.com/31800067/30240928-039ac274-957a-11e7-8186-9cb9f89c8b46.PNG)

**Comment by fuji97** [comment]
Grazie per la segnalazione

**Comment by MattPendragon** [comment]
Succede anche in altre zone del percorso 5 usando il Pokeboard (es: Passaggio percorso 5 - Campus)
