### ISSUE TITLE
Major BUG - Problemi di Cattura

### ISSUE THREAD

**Issue by SiberyanZ** [fuji97/pokemon-xenoverse-tracker#64]
Non so di preciso cosa abbia causato questo bug ma adesso non riesco più a catturare nessun pokemon, al tentativo di lanciare la ball mi compare il messaggio "Il pokemon non può essere catturato".

**Comment by fuji97** [comment]
Grazie per la segnalazione, hai provato a salvare e riavviare?

**Comment by SiberyanZ** [comment]
Si, ho provato anche a mandare il gioco in esecuzione come amministratore ma ancora nulla.
Comunque il bug avviene dalla terza medaglia in poi.
Siete ragazzi in gamba so che riuscirete a risolvere il problema.

**Comment by JonnyCorax** [comment]
Buona sera, anche io confermo il bug che si verifica in realtà da poco prima della terza medaglia, a partire dal Bosco Filante.

Le pokeball si sprecano comunque e il pokemon non può essere catturato, spero possiate risolvere perché è abbastanza difficile andare avanti così.

**Comment by Metalcape** [comment]
Confermo, sta succedendo anche a me. Riavviare non risolve il problema.

**Comment by fuji97** [comment]
Abbiamo trovato il problema e verrà sistemato nella prossima release, grazie per le vostre segnalazioni
