### ISSUE TITLE
Bug muro seconda palestra

### ISSUE THREAD

**Issue by Emax220x** [fuji97/pokemon-xenoverse-tracker#65]
#Nella terza stanza della seconda palestra, dove c'è lo scienziato, ci sono diversi punti sul muro superiore accessibili, allego screen del bug.

![senza nome](https://user-images.githubusercontent.com/31655629/30240992-5694cf32-957b-11e7-9f52-ebf0cb5a10c1.png)

Edit : Trovati altri 2 bug della stessa natura nel passaggio alla destra del campus acero, un bug minore all'entrata, uno maggiore all'uscita.

![senza nome1](https://user-images.githubusercontent.com/31655629/30241402-f45524f4-9582-11e7-965f-f9304f7790f3.png)

**Comment by fuji97** [comment]
Grazie per la segnalazione
