### ISSUE TITLE
37 Screenshot di errori

### ISSUE THREAD

**Issue by WalkerGe** [fuji97/pokemon-xenoverse-tracker#658]
Ho trovato una lunghissima successione di errori dall'Inizio del gioco fino all'entrata del Corridoio Roccioso. Alcuni permessi di mappa ed errori vari.
![pokemon xenoverse errori 2](https://user-images.githubusercontent.com/32095521/30588979-1f1d9690-9d39-11e7-9019-88631e9a66e1.png)
![pokemon xenoverse errori 3](https://user-images.githubusercontent.com/32095521/30588994-2cd39186-9d39-11e7-98d6-090aab3be95d.png)
![pokemon xenoverse errori 4](https://user-images.githubusercontent.com/32095521/30588998-2fbd1052-9d39-11e7-82be-40ad9512fe41.png)
![pokemon xenoverse errori 5](https://user-images.githubusercontent.com/32095521/30589004-36d0aca0-9d39-11e7-8a30-76b6ce466b6b.png)
![pokemon xenoverse errori 6](https://user-images.githubusercontent.com/32095521/30589011-3a0a5790-9d39-11e7-8446-46d6e57b9d7d.png)
![pokemon xenoverse errori 7](https://user-images.githubusercontent.com/32095521/30589026-409043fe-9d39-11e7-92fc-79826d98fc4d.png)
![pokemon xenoverse errori 9](https://user-images.githubusercontent.com/32095521/30589038-47885fac-9d39-11e7-83c3-908059c055f8.png)
![pokemon xenoverse errori 10](https://user-images.githubusercontent.com/32095521/30589039-4791bf02-9d39-11e7-94bb-7595abff0abe.png)
![pokemon xenoverse errori 11](https://user-images.githubusercontent.com/32095521/30589042-479a9136-9d39-11e7-80a5-6433a0f4b69a.png)
![pokemon xenoverse errori 12](https://user-images.githubusercontent.com/32095521/30589043-479b4c34-9d39-11e7-96ec-93266adfebf4.png)
![pokemon xenoverse errori 13](https://user-images.githubusercontent.com/32095521/30589040-4798180c-9d39-11e7-9249-d2141a27b416.png)
![pokemon xenoverse errori 14](https://user-images.githubusercontent.com/32095521/30589041-4798795a-9d39-11e7-8df7-220b0ed99cee.png)
![pokemon xenoverse errori 15](https://user-images.githubusercontent.com/32095521/30589044-47a1f3d6-9d39-11e7-8612-d31e3e515c36.png)
![pokemon xenoverse errori 16](https://user-images.githubusercontent.com/32095521/30589046-47a8bbf8-9d39-11e7-96a8-a809af417f72.png)
![pokemon xenoverse errori 17](https://user-images.githubusercontent.com/32095521/30589047-47b0cffa-9d39-11e7-8779-60a9c59e709a.png)
![pokemon xenoverse errori 18](https://user-images.githubusercontent.com/32095521/30589048-47b0e8b4-9d39-11e7-97a1-14b895b17cd5.png)
![pokemon xenoverse errori 19](https://user-images.githubusercontent.com/32095521/30589049-47b413a4-9d39-11e7-9bc6-2c6c645047fc.png)
![pokemon xenoverse errori 20](https://user-images.githubusercontent.com/32095521/30589050-47b516d2-9d39-11e7-9d70-06dc50acf536.png)
![pokemon xenoverse errori 21](https://user-images.githubusercontent.com/32095521/30589051-47bac190-9d39-11e7-96cc-6030cbbc23ea.png)
![pokemon xenoverse errori 22](https://user-images.githubusercontent.com/32095521/30589052-47bfb43e-9d39-11e7-965a-c88453a3b0d8.png)
![pokemon xenoverse errori 23](https://user-images.githubusercontent.com/32095521/30589054-47c8b03e-9d39-11e7-9907-7cbc97e61f1f.png)
![pokemon xenoverse errori 24](https://user-images.githubusercontent.com/32095521/30589053-47c88b40-9d39-11e7-976a-55b950092165.png)
![pokemon xenoverse errori 25](https://user-images.githubusercontent.com/32095521/30589055-47ce6862-9d39-11e7-87bd-407e8e316fc1.png)
![pokemon xenoverse errori 26](https://user-images.githubusercontent.com/32095521/30589056-47cffe8e-9d39-11e7-9a5e-eb68739fbb76.png)
![pokemon xenoverse errori 27](https://user-images.githubusercontent.com/32095521/30589057-47d205da-9d39-11e7-8ced-d87a3b4aeecb.png)
![pokemon xenoverse errori 28](https://user-images.githubusercontent.com/32095521/30589058-47d7448c-9d39-11e7-8533-45dc5e057bdb.png)
![pokemon xenoverse errori 29](https://user-images.githubusercontent.com/32095521/30589059-47e2d144-9d39-11e7-9492-f3aa09a51426.png)
![pokemon xenoverse errori 30](https://user-images.githubusercontent.com/32095521/30589061-47e5eeb0-9d39-11e7-8d43-732f02cd06b0.png)
![pokemon xenoverse errori 31](https://user-images.githubusercontent.com/32095521/30589060-47e50b30-9d39-11e7-99ce-c3958835f6ea.png)
![pokemon xenoverse errori 32](https://user-images.githubusercontent.com/32095521/30589063-47ec09f8-9d39-11e7-9316-47588d60e84d.png)
![pokemon xenoverse errori 33](https://user-images.githubusercontent.com/32095521/30589062-47eb32e4-9d39-11e7-88a0-d39b1a65857b.png)
![pokemon xenoverse errori 34](https://user-images.githubusercontent.com/32095521/30589064-47ed2c70-9d39-11e7-9caf-617edb9cdb36.png)
![pokemon xenoverse errori 35](https://user-images.githubusercontent.com/32095521/30589065-47fd0956-9d39-11e7-8444-5855e1c065fa.png)
![pokemon xenoverse errori 36](https://user-images.githubusercontent.com/32095521/30589067-47ff860e-9d39-11e7-998e-1dbee783c1cf.png)
![pokemon xenoverse errori 37](https://user-images.githubusercontent.com/32095521/30589066-47ff5be8-9d39-11e7-9c00-5d29e8d817e3.png)
![pokemon xenoverse errori 38](https://user-images.githubusercontent.com/32095521/30589068-4804c5b0-9d39-11e7-8a5c-20a775075d59.png)
![pokemon xenoverse errori 39](https://user-images.githubusercontent.com/32095521/30589037-476fb844-9d39-11e7-91da-e133c39f2557.png)

**Comment by fabstarkey** [comment]
grazie, abbiamo corretto la maggior parte!
