### ISSUE TITLE
Crash del gioco anche avviandolo da amministratore.

### ISSUE THREAD

**Issue by MarcoCinque55** [fuji97/pokemon-xenoverse-tracker#66]
Salve,il gioco continua a crasharmi anche avviandolo da amministratore.
Ho provato a riscaricarlo dal sito e dalla zip fornita qui ma niente da fare,continua a crashare.
Grazie in anticipo per la risposta.

**Comment by fuji97** [comment]
Se non ci dai screen di errore o simili è un po' un problema capire cosa stia succedendo

**Comment by MarcoCinque55** [comment]
![21616683_1481875751888745_2003882880_o](https://user-images.githubusercontent.com/31800255/30241765-3a11374c-958a-11e7-813e-e1823cffcdfe.png)

**Comment by fuji97** [comment]
E' un duplicato del bug #25, segui lo la discussione
