### ISSUE TITLE
Bloccato nella Rocca Draconica

### ISSUE THREAD

**Issue by numberseven7** [fuji97/pokemon-xenoverse-tracker#662]
Dopo aver sconfitto la guardia, entro nel passaggio per andare verso il vulcano ma sono rimasto bloccato vicino la roccia e il personaggio non si muove più (si sente il rumore di quando il personaggio cammina e sbatte contro la roccia). Ho provato a salvare e riavviare il gioco, ma quando carico di nuovo i dati riparte sempre da lì con lo stesso problema.

**Comment by mattiaquila** [comment]
Succede anche a me

**Comment by erif22** [comment]
Stesso problema

**Comment by Luca000111** [comment]
Segnaliamo tutti questo problema

**Comment by reilok** [comment]
idem bloccato nella grotta

**Comment by mattiaquila** [comment]
scusate non c'entra nulla ma già che ci sono : qualcuno mi ricorda dove trovare il condividi esp per favore?
