### ISSUE TITLE
errore a Oasi cocente

### ISSUE THREAD

**Issue by Vectoryx** [fuji97/pokemon-xenoverse-tracker#664]
escepion: nameerror
Message: in 'pbExecuteScript'The item 'TOMATO' is not valid.
Please add the item 

crash dovuto all'interazione con un oggetto nascosto a sud-est dell' oasi cocente

**Comment by LeonidaXX1** [comment]
Aggiorna alla versione 1.0.3, anch'io avevo lo stesso problema, dopo la patch ho potuto droppare Baccamodoro, che spiega quel "Tomato"
