### ISSUE TITLE
Bloccato su una roccia! 

### ISSUE THREAD

**Issue by miro49** [fuji97/pokemon-xenoverse-tracker#665]
praticamente sono entrato in una caverna del percorso 8 dopo aver battuto un soldato della regina sono uscito per continuare a giocare e nulla mi sono bloccato su una roccia non riesco a sbloccarmi sono andato su giù a destra sinistra ma nulla usato anche la "bici" oppure la fune di fuga ma nulla sono impalato li... help plz  che ho salvato e sono rientrato per vedere se mi sbaggavo ma nulla.

vi allego la zona dove sono bloccato https://imgur.com/a/ubD1c

**Comment by numberseven7** [comment]
Identico problema

**Comment by Luca000111** [comment]
Stesso problema
