### ISSUE TITLE
sprites

### ISSUE THREAD

**Issue by Vectoryx** [fuji97/pokemon-xenoverse-tracker#666]
mancano  ifron sprites e backsprites di caterpie metapod butterfree
---------------------------
Pokemon Xenoverse
---------------------------
Exception: RuntimeError
Message: Woops, looks like you're missing the Front sprite for Butterfree! EliteBattle_BitmapWrappers:258:in `pbLoadPokemonBitmapSpecies'
EliteBattle_BitmapWrappers:234:in `pbLoadPokemonBitmap'
EliteBattle_Sprites:193:in `setPokemonBitmap'
EliteBattle_Scene:1142:in `pbTrainerSendOut'
EliteBattle_Scene:1112:in `each'
EliteBattle_Scene:1112:in `pbTrainerSendOut'
PokeBattle_Battle:1275:in `pbSendOut'
PokeBattle_Battle:1300:in `pbReplace_ebs'
EliteBattle_Battle:349:in `pbReplace'
PokeBattle_Battle:1313:in `pbRecallAndReplace_ebs'

**Comment by fabstarkey** [comment]
scarica la patch 1.0.3 e non avrai più questo problema
