### ISSUE TITLE
Musiche + Allenatore nel Percorso 2

### ISSUE THREAD

**Issue by MijumewAndCo** [fuji97/pokemon-xenoverse-tracker#668]
In Xenoverse, si sente un po' la mancanza di musiche per quando un Pokémon deve imparare una nuova mossa (è completamente silenzioso) e per quando si cattura un nuovo Pokémon (c'è ancora la musica della battaglia in sottofondo).
Aprendo il menù esattamente quando si entra in un'area, la musica dell'area precedente si ferma, ma la musica dell'area attuale non parte fino a quando non si chiude il menù.
Nel Percorso 2, il primo Allenatore che si sfida (di nome Luca, se la memoria non mi inganna è un Montanaro o un Avventuriero) una volta battuto commenta "Sei proprio fortissimo" indipendentemente dal sesso del giocatore.
Sono solo piccoli dettagli, non bug propriamente detti, ma pensavo fosse giusto parlarne.

**Comment by fabstarkey** [comment]
cercheremo di risolvere le musiche nella parte 2 (con nostra roba inedita)
