### ISSUE TITLE
Niente testi

### ISSUE THREAD

**Issue by FraBgn** [fuji97/pokemon-xenoverse-tracker#67]
All'avvio del gioco, dove ci dovrebbe essere la scelta Italiano/Inglese, nel menù principale e in svariati altri punti, come nelle schede dei pokèmon, non mi compaiono i testi. Ho visto quello che avete consigliato per la risoluzione (andare nella cartella dei fonts e installarli tutti manualmente) e l'ho fatto più volte, ho anche messo (non si sa mai) il gioco in modalità amministratore, ma nulla. Allego due screen delle schermate e la cartella dei font (in caso magari ne manchi qualcuno)! Se riuscite aiutatemi, per favore!
Se serve, ho un Windows 7 64 bit, in caso di maggiori info chiedete pure!
![cattura2](https://user-images.githubusercontent.com/22859713/30241169-3c05adbe-957e-11e7-8c4c-7e10f3ceba81.PNG)
![cattura3](https://user-images.githubusercontent.com/22859713/30241170-3c09a450-957e-11e7-8b94-beb13d279e0b.PNG)
![cattura1](https://user-images.githubusercontent.com/22859713/30241168-3c018ad6-957e-11e7-8584-db55eb1d501f.PNG)

**Comment by silvioiolli** [comment]
Non so se lo hai fatto o meno, ma prova a fare copia->incolla dei fonts dalla cartella Programmi (x86)/Pokemon Xenoverse/Fonts a quella di C:/Windows/Fonts.

**Comment by fuji97** [comment]
Sistemato per la prossima release, per ora puoi cambiare temporaneamente il font dalle opzioni.

**Comment by fuji97** [comment]
PS: Era già stato segnalato, per favore guardate le altre segnalazioni già fatte
