### ISSUE TITLE
Blocco rocca draconica

### ISSUE THREAD

**Issue by Jack71293** [fuji97/pokemon-xenoverse-tracker#670]
blocco del personaggio presso il percorso 8
![cattura](https://user-images.githubusercontent.com/32100202/30595214-d83458aa-9d50-11e7-992d-3692b5d01b06.PNG)

**Comment by Luca000111** [comment]
Stessa cosa a me

**Comment by NotMyUsuallyNick** [comment]
Sono bloccato anche io qui
