### ISSUE TITLE
Bug contro Shulong X

### ISSUE THREAD

**Issue by Maxy-3do** [fuji97/pokemon-xenoverse-tracker#673]
Succede che nella battaglia al vulcano contro Shulong X se il primo pokemon viene sconfitto non mi è più possibile sceglierne un'altro. questo perché nella schermata di cambio pokemon compare questo:
![cattura](https://user-images.githubusercontent.com/32100926/30596388-3b2d6872-9d54-11e7-8c94-24c8eb037866.PNG)

Se poi clicco ok  mi si apre un dialogo nella parte bassa dello scherma dove dice che Shulong attacca ma non c'è nessun pokémon, a questo punto mi chiede se voglio cambiare pokemon e, indipendentemente dalla risposta che do, ricompare la finestra dell'immagine qui sopra e non mi permette mai di cambiare pokemon.

**Comment by giovannicroce** [comment]
anche a me succede

**Comment by jimmermeister** [comment]
Idem

**Comment by bev95** [comment]
Anche a me

**Comment by LightManYT** [comment]
Non è colpa nostra, aspetteremo le prossima patch, ma solo per chiedere, dove hai trovato riolu ? ahahahah è uno dei miei Pokemon preferiti 👍 :)

**Comment by Maxy-3do** [comment]
Beh si ovvio che dobbiamo aspettare la patch. Intanto volevo rendere noto il problema. Comunque Riolu l'ho trovato nel percorso 8

**Comment by michelo92** [comment]
Succede anche a me contro mio Trishout X ed ho notato che non ho in squadra lo Scaleon di Oleandro, anche se dice "Prendi il mio Scalon, ti sarà molto utile" potrebbe essere anche quello il problema! Inoltre se provo ad usare uno strumento di cura sul pokemon in lotta (per aggirare questo problema) appare lo stesso errore!
