### ISSUE TITLE
Percorso 8 Impossibile muoversi nella grotta 

### ISSUE THREAD

**Issue by Piroll** [fuji97/pokemon-xenoverse-tracker#674]
Andando dalla rocca Dragonica nella grotta da cui si arriva alla rocca, il personaggio smette di muoversi come se urtasse in continuazione contro un ostacolo
![dwewr](https://user-images.githubusercontent.com/32095790/30597024-0e653534-9d56-11e7-8932-a724c00f7890.PNG)

**Comment by jimmermeister** [comment]
Successo anche a me

**Comment by Luca000111** [comment]
stessa cosa

**Comment by andreagaara** [comment]
a me pure.. ho 12 ore di salvataggio dietro, avete risolto in qualche modo?

**Comment by LightManYT** [comment]
io sono riuscito a sbaggarmi.
in pratica appena entrate nella rocca dragonica dovete subito premere il tasto "giù" per fare un passetto indietro, c'ho messo un pò per riuscirci ma ha funzionato, per fortuna io avevo salvato proprio 2 minuti prima di entrare nella rocca, per chi invece aveva salvataggi arretrati...non so cosa dirvi, aspetteremo le prossime patch ;).
Spero di essere stato d'aiuto

**Comment by tonynart** [comment]
confermo quanto detto da @LightManYT e ne approfitto per ringraziarlo di cuore per avermi permesso di continuare senza aspettare la patch 😍

**Comment by LightManYT** [comment]
Di niente @tonynart 💯 <3
