### ISSUE TITLE
Bloccato sulla nave

### ISSUE THREAD

**Issue by Alexguidi98** [fuji97/pokemon-xenoverse-tracker#68]
Sono bloccato sulla nave senza potermi muovere appena entrato anche muovendo le frecce non si muove il personaggio  e l’unico modo sarebbe iniziare di nuovo il gioco
![image](https://user-images.githubusercontent.com/31800848/30241242-cb0e4bbe-957f-11e7-9188-7701aba55992.jpg)

**Comment by fuji97** [comment]
Per favore, controllate se un bug è già stato segnalato o no
