### ISSUE TITLE
grotta percorso 8, impossibile muovere il personaggio

### ISSUE THREAD

**Issue by fattzeff** [fuji97/pokemon-xenoverse-tracker#680]
entrato nella grotta del percorso 8 che porta al vulcano (dopo esserci già passato la prima volta per arrivare alla città) il personaggio si è bloccato contro la roccia appena entrato. In teoria basterebbe premere il tasto indietro per poter cammianare normalmente ma questo mi viene impossibile, in quanto il gioco esegue ripetutamente il rumore del personaggio che sbatte contro qualcosa, sintomo che il gioco si sia bloccato con l'imput 'cammina avanti' (l'ultimo imput dato). ho provato ad usare il pokeboard, teletrasporto, e mi sono assicurato non fosse la tastiera difettosa. Ho windows 10 creators update e la versione 1.0.3 del gioco. ho provato a chiudere e riaprire ma non succede niente. 
![screenshot 66](https://user-images.githubusercontent.com/32104641/30602913-48a4ecc0-9d66-11e7-8dc7-4cf7e82aede8.png)

**Comment by morethenless** [comment]
anch'io ho lo stesso bug

**Comment by Luca000111** [comment]
anche io

**Comment by LeonidaXX1** [comment]
Se fino alla 1.0.2 andava tutto bene, la soluzione è semplice. Dal momento che tutte le patch condividono lo stesso salvataggio, fagli un backup, per sicurezza, poi disinstalla completamente il gioco e aggiornarlo fino alla 1.0.2, il problema non dovrebbe ripresentarsi, quindi procedi e fai tutto ciò di cui hai bisogno fino a quando quel passaggio non ti servirà più, poi aggiornarlo alla 1.0.3. Credo sia l'unica soluzione. Tanto quando termini il gioco ti viene data la Gemma N per volare, quindi il problema non ci sarà più.

**Comment by Luca000111** [comment]
Come si fa un backup?

**Comment by LeonidaXX1** [comment]
Vai in C/Utenti/Utente/Partite salvate, dove "Utente" è il nome dell'account con cui accedi al pc. Dentro questa cartella c'è una sottocartella Xenoverse, ti basta copiare la cartella in un altro punto del pc

**Comment by Bamby02** [comment]
Leonida, il problema non è relativo alla versione in questo caso, quindi anche provando ad eseguire il tuo metodo il pg rimarrà ugualmente fermo, ho provato ovviamente

**Comment by drz95** [comment]
stesso problema, qualcuno ha risolto? ho l npg camuffato dal mio starter che mi segue credo sia questo che causa l errore
