### ISSUE TITLE
Il soldato Joele dopo la battaglia con Gengar ha preso lo sprite del mio starter (trishout x)

### ISSUE THREAD

**Issue by Pugnator123** [fuji97/pokemon-xenoverse-tracker#685]
Come da titolo, dopo aver sconfitto Gengar al posto del soldato Joele che mi segue vedo lo sprite del mio starter, per il resto se provo a parlarci mi chiede se voglio allenarmi col suo lairon, quindi l'evento in se funziona bene.

**Comment by Pugnator123** [comment]
![image](https://user-images.githubusercontent.com/16070882/30619706-18e17234-9da1-11e7-8d29-59b887d73cdc.png)
Ecco un'immagine esempio per mostrare meglio il problema.

**Comment by fabstarkey** [comment]
E' un problema del follow, prova a scaricare la patch 1.0.3
