### ISSUE TITLE
Segnalazione errori

### ISSUE THREAD

**Issue by Essezeta98** [fuji97/pokemon-xenoverse-tracker#688]
Salve, premetto che il gioco mi sta piacendo davvero tanto e che vi meritate i più sinceri complimenti. Il gioco è fantastico e si vede l'impegno che c'è dietro da parte di tutto lo staff, un grande risultato!
Premetto inoltre che l'ultima cosa che ho fatto è la conquista della medaglia zucchero.

Elenco una serie di errori/bug che ho riscontrato sinora durante la mia esperienza di gioco (nulla di particolarmente fastidioso ma penso che queste segnalazioni possano aiutare a limare piccoli dettagli e migliorare il gioco già bello di suo). Ho cercato di non ripetere bug che ho già letto da altre parti.

-Durante la battaglia contro un allenatore nel Bosco Filante, ho usato Codadrago con il mio Scaleon, facendo sostituire il pokemon in campo con un Electabuzz, che già era entrato in campo prima. Appena entrato in campo l'Electabuzz si è attivata l'abilità Statico e il mio Scaleon è stato paralizzato, nonostante i due pokémon non fossero venuti a contatto.

-Dopo aver perso una battaglia con un allenatore nel Bosco Filante subito dopo aver catturato Galvantula X, sono stato rimandato nell'ultimo Self-Chansey utilizzato, proprio quello del Bosco Filante, ed è riapparsa la scritta successiva all'evento di Galvantula X, ovvero "Sembra che abbia smesso di nevicare". Stavolta però è rimasta fissa ed è rimasta anche durante le lotte sovrapponendosi al resto. (aggiungo anche qualche screen in allegato)

-Dopo aver terminato l'evento di Galvantula, è possibile camminare sopra gli alberi su cui erano legate le tre persone, oltrepassandoli come se non ci fossero (non so se sia voluto o se gli alberi in realtà dovrebbero sparire).

-A est del percorso 4 c'è una staccionata che è possibile saltare da entrambi i lati e non solo da sopra come accade di solito (la cosa è anche comoda ma non credo sia voluta).

-Un Kadabra selavatico ha utilizzato Cambiaposto e avendo fallito è apparsa la scritta "But it failed".

-Le descrizioni di Yungoos e Joltik nel pokédex sono in inglese.

-Quando il mio Chigami usa assorbibacio, non recupera energia. Lo stesso vale quando la usano i nemici (ad esempio lo Slurpuff della capopalestra Rochelle)

-Scaleon ha l'abilità Ipertaglio. Quando questa si attiva, prima vengono mostrati gli effetti (es. "Ipertaglio di Scaleon annulla la prepotenza di Snubbul"), poi appare la schermata con scritto "Scaleon's Ipertaglio" e successivamente viene ripetuto l'effetto già apparso in precedenza (la cosa quindi si rilegge due volte).

In conclusione, ancora complimenti! Continuate così!

![a](https://user-images.githubusercontent.com/32114773/30626184-7916b5fc-9dc8-11e7-86e0-3bf0a24db60f.JPG)
![b](https://user-images.githubusercontent.com/32114773/30626185-7918f682-9dc8-11e7-8007-38d93207b150.JPG)
![c](https://user-images.githubusercontent.com/32114773/30626186-7919e3e4-9dc8-11e7-8a03-ffad962f1d7c.JPG)

**Comment by fabstarkey** [comment]
grazie per la segnalazione.
