### ISSUE TITLE
Impossibile utilizzare la xenoball contro Gengar X

### ISSUE THREAD

**Issue by morethenless** [fuji97/pokemon-xenoverse-tracker#690]
Buongiorno a tutti, faccio i miei complimenti agli sviluppatori per questo bellissimo gioco.
Come da titolo, durante lo scontro contro Gengar X (mentre era a vita verde) mi impediva di lanciare le xenoball e quindi di catturarlo.

**Comment by yangus98** [comment]
Gengar x é molto importante per la storia,non lo puoi catturare adesso

**Comment by morethenless** [comment]
ah ok ti ringrazio!
