### ISSUE TITLE
Bug dopo lo scontro con elekid x

### ISSUE THREAD

**Issue by Maximiliano96** [fuji97/pokemon-xenoverse-tracker#691]
Guardando i gameplay altrui, dopo tale scontro viene dato il PokeWes e il pokedex.
a me questo non capita...appena vengo portato nel laboratorio di Ezio, mi vengono spiegate le xenoball e poi dice di dover scappare...

**Comment by fabstarkey** [comment]
devi sfidare la palestra, poi te lo darà!
