### ISSUE TITLE
Bloccato nel tunnel per uscire da Rocca Draconica

### ISSUE THREAD

**Issue by NotMyUsuallyNick** [fuji97/pokemon-xenoverse-tracker#694]
Devo uscire da Rocca Draconica passando per il tunnel. Appena entro dentro, non posso più muovermi e continuo a sentire il suo di come quando si va a sbattere contro un muro.
A titolo informativo, aggiungo che nonostante la terza patch, ho lo starter che continua a seguirmi. Se provo a parlargli, ottengo il dialogo che visualizzavo quando parlavo con la guardia nera, quella che mi chiede se voglio allenarmi con il suo Lairon.

**Comment by tonynart** [comment]
è un problema comune quello. siamo tutti bloccati in quel punto. ci tocca aspettare che weedle rilasci una patch per fixare questo bug.. per quanto riguarda lo starter che ti segue, io non ho riscontrato questo problema.. prova a disinstallare e reinstallare il tutto.

**Comment by tonynart** [comment]
Ho appena testato questo metodo, se proprio non ce fai ad aspettare il fix che la Weedle rilascerà a brevissimo: copiati la cartella Xenoverse con il tuo salvataggio, successivamente disinstalla il gioco completamente, rimuovendo ogni cartella denominata Pokémon Xenoverse. A questo punto installa il setup 1.02 del gioco, visto che non era ancora presente il bug in questione, superi il punto critico del bug, salvi la partita e successivamente reinstalli la patch 1.03. Io ho risolto così, è un po' macchinoso ma semplicissimo allo stesso tempo! ;)
