### ISSUE TITLE
Diglett bug cambio pokemon

### ISSUE THREAD

**Issue by Drehon** [fuji97/pokemon-xenoverse-tracker#695]
Combattendo contro un diglett nel territorio roccioso se si prova a cambiare pokemon si apre la finestra bianca che credo dovrebbe dire che non è possibile cambiare pokemon.

La finestra però è vuota e bisogna premere x per tornare indietro non potendola chiudere.

**Comment by tonynart** [comment]
è capitato anche a me, lo fixeranno sicuramente a breve
