### ISSUE TITLE
personaggio che continua a camminare addosso il muro di una grotta non posso piu muovermi

### ISSUE THREAD

**Issue by andreagaara** [fuji97/pokemon-xenoverse-tracker#696]
salve sono entrato nella grotta draconica e appena valcata la soglia della grotta il mio personaggio non fa altro che camminare dritto addosso al muro come se il pulsante avanti fosse schiacciato ma non lo è. Non so che fare non voglio perdere oltre 12 ore di salvataggio se potete far qualcosa ve ne sarei grat
![cattura](https://user-images.githubusercontent.com/32129932/30641832-c86ca2b6-9e08-11e7-8806-3f028b347d0c.PNG)

**Comment by tonynart** [comment]
è un problema comune quello. non hai letto le altre discussioni prima di scriverne una tua? siamo tutti bloccati in quel punto. ci tocca aspettare che weedle rilasci una patch per fixare questo bug..

**Comment by tonynart** [comment]
Ho appena testato questo metodo, se proprio non ce fai ad aspettare: copiati la cartella Xenoverse con il tuo salvataggio, successivamente disinstalla il gioco completamente, rimuovendo ogni cartella denominata Pokémon Xenoverse. A questo punto installa il setup 1.02 del gioco, visto che non era ancora presente il bug in questione, superi il punto critico del bug, salvi la partita e successivamente reinstalli la patch 1.03. Io ho risolto così, è un po' macchinoso ma semplicissimo allo stesso tempo! ;)
