### ISSUE TITLE
Problemi battaglia contro starter x

### ISSUE THREAD

**Issue by odinoo** [fuji97/pokemon-xenoverse-tracker#697]
Ciao, con tutte le patch installate nella battaglia contro lo starter x cercando di sostituire , o appena morto il pokemon, appena apre la squadra mi da questo errore. Non compare l'artwork dello Scaleon di Oleandro. Visti i problemi precedenti ho tolto anche il mio dalla squadra, ma non è cambiato
![screenshot_58](https://user-images.githubusercontent.com/31851097/30642586-bc4bf790-9e0b-11e7-933c-01d709ba1af5.png)

**Comment by LightManYT** [comment]
stai tranquillo che è un bag che succede a tutti, devono patcharlo loro.

**Comment by odinoo** [comment]
Ah ok grazie non sapevo
