### ISSUE TITLE
Bug vari e soluzioni temporanee

### ISSUE THREAD

**Issue by Loki86ita** [fuji97/pokemon-xenoverse-tracker#698]
Sperando di fare cosa gradita vi dico i bug che ho riscontrato e come li ho aggirati temporaneamente per completare la prima parte.
Io sono partito con la versione 1.0.0 aggiornata con le varie patch.
Ho riscontrato il bug della roccia vicino alla rocca dragonica che non mi fa avanzare, ieri sera misteriosamente non si è bloccato e sono riuscito a proseguire, ho letto che è successo anche ad altre persone che sono riuscite ad avanzare in serata e basta. Per curiosità oggi ho provato a controllare e il bug si è ripresentato, cambiando orario e simulando la sera non cambia, quindi non so a cosa possa essere dovuto.
L'altro bug importante che ho riscontrato è stato quello della lotta col boss x nel vulcano, per ovviare a questo appena prima di proseguire per andare allo scontro mi sono fermato al self-chansey per ritirare un altro pokemon a caso e avere la squadra al completo, così non ho avuto errori di sorta ed ho potuto completare la parte uno. Riprendo il gioco il salvataggio poi mi dava 7 pokemon in squadra, per risolvere ne ho depositato uno, salvato, chiuso e riaperto il gioco e ne avevo questa volta 6 come sempre.
Ultimo bug ecompariva quando andavo a depositare il mio scaleon (non avendo quello dato per lo scontro), ho copiato i salvataggi, disinstallato il gioco e installato quello finale già alla versione 1.0.3 così mi è comparso nel box anche l'altro scaleon al livello 50 e non restituisce più errore.
Allo stato attuale rimane il bug della roccia ma con volo per ora riesco ad aggirarlo.
Scusate il papiro ma ho pensato di fare cosa gradita.
Complimenti davvero per l'ottimo gioco e che dire, se questa è solo la prima parte nella seconda ci sarà da divertirsi!

**Comment by andreagaara** [comment]
io sono bloccato su quella roccia da 3 giorni, fune di fuga non funziona e volo non lo ho ancora... non so che fare

**Comment by tonynart** [comment]
non c'è niente da fare se non aspettare una patch...

**Comment by andreagaara** [comment]
allora aspetterò perchè non voglio perdere 12 ore di salvataggio :(
