### ISSUE TITLE
Lag su erba alta percorso uno

### ISSUE THREAD

**Issue by francescopkm** [fuji97/pokemon-xenoverse-tracker#70]
Il gioco era molto rallentato quando mi trovavo nel percorso uno, soprattutto quando mi trovavo sull'erba alta ed ancora di più prima che iniziasse lo scontro contro un pokemon selvaggio.

**Comment by fuji97** [comment]
Non è colpa nostra, ma della progettazione del pacchetto su cui ci siamo basati "Pokémon Essentials", se hai un PC lento può capitare, prova da F1 a disabilitare la Smooth Mode

**Comment by francescopkm** [comment]
Grazie mille fuji97, proverò a fare come hai detto
