### ISSUE TITLE
BUG DELLA GROTTA

### ISSUE THREAD

**Issue by D-Dav98** [fuji97/pokemon-xenoverse-tracker#700]
![bug](https://user-images.githubusercontent.com/32132314/30645079-e2cfdd9c-9e14-11e7-90a1-a6b37a1609c1.PNG)

Raga lo so che è stata già postata da altri utenti, ma la rimando perchè questo è un bug abbastanza grave, dato che arriva in un punto in cui non è permesso usare ancora volo. Vi prego di rilasciare una patch il prima possibile, io non riesco a stare senza questo gioco.

**Comment by tonynart** [comment]
nessuno ci sa stare, ma ci tocca aspettare ed evitare di intasare il sito con la stessa richiesta, non credi? Hanno detto che hanno fixato il bag e tra qualche giorno rilasceranno la patch aggiornata. Bisogna solo aspettare, non c'è altro da fare...

**Comment by tonynart** [comment]
Ho appena testato questo metodo, se proprio non ce fai ad aspettare il fix che la Weedle rilascerà a brevissimo: copiati la cartella Xenoverse con il tuo salvataggio, successivamente disinstalla il gioco completamente, rimuovendo ogni cartella denominata Pokémon Xenoverse. A questo punto installa il setup 1.02 del gioco, visto che non era ancora presente il bug in questione, superi il punto critico del bug, salvi la partita e successivamente reinstalli la patch 1.03. Io ho risolto così, è un po' macchinoso ma semplicissimo allo stesso tempo! ;)
