### ISSUE TITLE
Un bug da risolvere

### ISSUE THREAD

**Issue by Marco20202013** [fuji97/pokemon-xenoverse-tracker#701]
![catturafa](https://user-images.githubusercontent.com/32132743/30645648-a284626a-9e16-11e7-9cbc-a4ae2ccdc815.PNG)
 VI allego il file dell'errore questo parte dopo che lo starter x mi sconfigge il primo pokemon non mi fa più cambiare il pokemon e ho scaricato tutte le patch, ma non  è cambiato niente.
Grazie per l'attenzione

**Comment by tonynart** [comment]
come hai fatto ad arrivare in quel punto se praticamente si viene bloccati da un bug prima della grotta draconica? 😕
