### ISSUE TITLE
Bug anello terrestre

### ISSUE THREAD

**Issue by Sgucchio** [fuji97/pokemon-xenoverse-tracker#702]
Dopo avere terminato la 1 parte del gioco uccidendo qualsiasi pokemon il drop è di un anello terrestre ( non so se è un bug o fatto apposta ma io lo segnalo comunque).
![2017-09-20](https://user-images.githubusercontent.com/32134108/30647945-1815e426-9e1d-11e7-9e00-9054fd5ad964.png)

**Comment by LeonidaXX1** [comment]
Non può essere fatto apposta. L'Anello Xenoverse è uno solo e si genera da Alter quando viene sconfitto, mica si può droppare dal primo pokémon che capita. A me non lo droppa, quindi è un bug
