### ISSUE TITLE
come si continua?

### ISSUE THREAD

**Issue by sceglilotu** [fuji97/pokemon-xenoverse-tracker#703]
come si continua dopo la sfida col proprio pokemon?

**Comment by tonynart** [comment]
Puoi essere più preciso?

**Comment by sceglilotu** [comment]
come continua il gioco dopo aver battuto il proprio pokemon in forma xenoverse al lv 50 nel vulcano?
Ne la palestra dell oasi ne quella di rocca draconica sono ancora accessibili

**Comment by AkeRoss** [comment]
non hai letto il messaggio di fine parte uno?

**Comment by AkeRoss** [comment]
devi aspettare che esca la parte due

**Comment by tonynart** [comment]
Quoto @AkeRoss. Hai finito la prima parte, c'è ben poco da fare...
