### ISSUE TITLE
Bug Grafici Minori

### ISSUE THREAD

**Issue by David961** [fuji97/pokemon-xenoverse-tracker#705]
![ghgf](https://user-images.githubusercontent.com/32040511/30650280-77b90d3c-9e5d-11e7-8e76-b8d42842190f.PNG)
![sdc](https://user-images.githubusercontent.com/32040511/30650275-754592dc-9e5d-11e7-84e7-07a4c49db940.PNG)
![sdfdf](https://user-images.githubusercontent.com/32040511/30650276-754f40ac-9e5d-11e7-89ac-30aadf2500e3.PNG)
![xx](https://user-images.githubusercontent.com/32040511/30650277-755cb7aa-9e5d-11e7-93c8-93b93c151fc7.PNG)

Tutti all'interno del Regno Caramello. Nell'immagine dove c'è il Cuoco ci sono 2 spazi in cui il personaggio non può passare ed è un problema perché si tratta della strada quindi niente... ve li segnalo tutti.

**Comment by fabstarkey** [comment]
corretto, grazie :)
