### ISSUE TITLE
Bug Roccia Draconica

### ISSUE THREAD

**Issue by Gojira890** [fuji97/pokemon-xenoverse-tracker#706]
In una piccola grotta per andare verso roccia draconica,il mio personaggio si è bloccato davanti a una roccia.
ora i miei movimenti sono impossibilitati e non posso procedere a giocare.

**Comment by tonynart** [comment]
ma dico ma leggete prima di postare? 1000 topic aperti sullo stesso problema... è stata postata la soluzione da me medesimo, leggi gli altri topic per scoprirla

**Comment by tonynart** [comment]
se leggi più in basso troverai la soluzione che io stesso ho trascritto :)

**Comment by morethenless** [comment]
a me non funziona nulla lo stesso, ho provato con tutte le versioni precedenti.
