### ISSUE TITLE
utilizzo di controller

### ISSUE THREAD

**Issue by knight92pkm** [fuji97/pokemon-xenoverse-tracker#708]
possibile utilizzare un controller???
un piccolo problema se nelle impostazioni metti schermo grande lo fa in maniera sproporzionata al pc

**Comment by tonynart** [comment]
Non è possibile utilizzare un controller, si gioca con tastiera.

**Comment by knight92pkm** [comment]
CON TASTIERA é Scomodissimo

**Comment by fabstarkey** [comment]
Non è possibile per il momento!
