### ISSUE TITLE
 Achiements 

### ISSUE THREAD

**Issue by Franky992** [fuji97/pokemon-xenoverse-tracker#709]
Alcuni Achiements non si sbloccano:
-Far schiudere il primo uovo
-Cattura il tuo primo pokemon X
-Pesca una caramella rara

**Comment by tonynart** [comment]
Io li ho sbloccati tutti...

**Comment by Franky992** [comment]
magari è perchè avevo già finito prima del rilascio delle patch

**Comment by Franky992** [comment]
Ho riprovato la pesca ma non me l'ha sbloccata e ho trovato una caramella rara vabbè aspetterò

**Comment by fabstarkey** [comment]
stiamo risolvendo!
