### ISSUE TITLE
Bug riscontrati pt1

### ISSUE THREAD

**Issue by RhaegarX** [fuji97/pokemon-xenoverse-tracker#710]
Salve a tutti riporto alcuni dei bug che ho riscontrato fino adesso (ovvero dopo aver battuto la terza palestra). Ci tengo a precisare che non so se i seguenti bug sono stati già riportati.
Prima di tutto ringrazio i creatori e programmatori del gioco per il magnifico lavoro in atto.

1) Bug teletrasporto con Kadabra : utilizzando la mossa teletrasporto al di fuori di una battle invece di essere teletrasportati al centro pokemon più vicino , si viene catapultati in una zona completamente nera, il gioco, però , non va in crash.

![teleort](https://user-images.githubusercontent.com/32136009/30652061-aed4015e-9e27-11e7-9b04-b878a2e69985.png)

2) Bug mossa Assorbibacio : la mossa Assorbibacio non restituisce punti salute.

3) Bug grafico : nella parte sud-est del regno caramello c'è uno sdoppiamento dell'ombra del protagonista, il bug si risolve se si cambia zona , ma ritorna nel momento in cui si ritorna nella zona precedente.(Zona sud-est accanto al NPC della ragazza che si lamenta delle foto e dei like, credo si chiami Elena).

![immagine](https://user-images.githubusercontent.com/32136009/30653517-92d0275e-9e2b-11e7-8289-69e0811b8eda.png)

4) Bug pokedex : aprendo il pokedex e consultando la sezione Area di qualsiasi pokemon (catturato e non) e , successivamente, tornando indietro , premendo il tasto apposito, si arriva ad una schermata di colore nero.Il gioco non crasha , il problema è aggirabile ripremendo il tasto per tornare indietro tornando quindi alla schermata principale del pokedex.

![pokedex](https://user-images.githubusercontent.com/32136009/30652582-06b5604c-9e29-11e7-9f0e-ad828ab3fd4f.png)

5) Bug MT 34 : la MT 34 è nominata Sanguisuga, ma la descrizione fa riferimento a Fangonda, tra l'altro , la MT 34 , negli ultimi titoli pokemon è proprio Fangonda. Il problema potrebbe essere solo una denominazione errata ma provando ad insegnarla ad Arbok (che è capace di apprendere Fangonda) risulta NON capace. 

![mt](https://user-images.githubusercontent.com/32136009/30652996-28ea65c6-9e2a-11e7-87f4-163cfe7ade58.png)

![mt2](https://user-images.githubusercontent.com/32136009/30653141-96116ef6-9e2a-11e7-850d-edf20f71f2f6.png)

6) Bug Corridoio Roccioso : nel corridoio roccioso utilizzando il repellente o il super-repellente i pokemon appaiono lo stesso , non so se questo sia voluto o meno.

Questi sono i Bug che ho riscontrato nella mia esperienza di gioco fatta fino adesso, spero di non aver infranto nessun regolamento.
Il gioco è aggiornato all'ultima patch rilasciata.
Grazie ancora e continuate così !

**Comment by andreagaara** [comment]
Per quanto riguarda ai repellenti, ho riscontrato anche io questo bug, sono giunto alla conclusione è un bug abbastanza casuale, cioè che non capita sempre ma ha una buona probablità che accada. La prima volta che mi è apparsa questa cosa è stata nell' bosco mentre cercavo galvantula x e ho pensato bho magari per la missione anche se butto il repellente, escono lo stesso, poi alla corridorio mi è successa la stessa cosa e ho capito il perchè, spero che sia giusto, ma se tu spruzzi il repellente fuori dalla grotta e poi ci rientri l effetto non rimane solo quando quel repellente sarà finito e ne attiverai un altro all interno della grotta non avrai problemi di pokemon selvaggi. questa è la mia opinione spero sia corretta

**Comment by RhaegarX** [comment]
Ciao, anche io ho provato varie volte per verificarlo e trovare una soluzione momentanea, ed anche io ho capito che è un bug casuale poiché a me nel bosco i repellenti funzionavano. Ma per quanto riguarda il corridoio la prima volta che ho riscontrato tale bug é stato proprio quando ho utilizzato il repellente nella grotta, e quando uscivo e camminavo nell'erba alta i pokemon non comparivano, quindi penso sia casuale ma sempre riferito ad alcuni luoghi specifici.
