### ISSUE TITLE
Bug nella Rocca Dragonica

### ISSUE THREAD

**Issue by Ninjaaaaaa** [fuji97/pokemon-xenoverse-tracker#711]
Dopo aver battuto la guardia che sorvegliava il nonno della capopalestra Alexandra dovremmo andare al Vulcano Decibel soltanto che appena entra nella caverna da dove siamo arrivati nella Rocca Dragonica il mio personaggio si blocca in una roccia e pur potendo aprire il menù non ci si potrà muovere e quindi andare avanti nella storia. Potete risolvere questo bug? Grazie tante a voi di Weedle per lo stupendo gioco che avete creato

**Comment by tonynart** [comment]
è possibile aggirare questo bug. leggi le varie discussioni e troverai il modo ;)

**Comment by tonynart** [comment]
è possibile aggirare questo bug. leggi le varie discussioni e troverai il modo ;)

**Comment by tonynart** [comment]
è possibile aggirare questo bug. leggi le varie discussioni e troverai il modo ;)
