### ISSUE TITLE
Piccolo bug grafico

### ISSUE THREAD

**Issue by SuperSal02** [fuji97/pokemon-xenoverse-tracker#712]
Ho notato che in alcuni punti della mappa, l'ombra del personaggio si bugga e si muove separatamente da esso, spostandosi di qualche passo ritorna normale, insomma solo in certi punti c'è questo errore. Errore da poco, pochissimo, ovviamente, ma ci tenevo a segnalarlo. Del resto veramente un gioco perfetto! Buon lavoro per la risoluzione dei bug e per la programmazione della prossima parte!

**Comment by fabstarkey** [comment]
in realtà c'è un piccolo segreto riguardo quelle ombre, vedrai con la parte 2 ;)
