### ISSUE TITLE
Bug Grafico Mosse

### ISSUE THREAD

**Issue by Rexus752** [fuji97/pokemon-xenoverse-tracker#713]
Salve, ho trovato un bug grafico che riguarda la desrizione della mossa "Nebbia", che non permette di visualizzare l'intera descrizione. Ho allegato lo screenshot della descrizione
![boh](https://user-images.githubusercontent.com/32108270/30660512-560e0942-9e41-11e7-8eba-f959388656b2.PNG)

**Comment by fabstarkey** [comment]
basta utilizzare altri font come D/P per vedere tutto!
