### ISSUE TITLE
Piccolo bug grafico cure pokecenter

### ISSUE THREAD

**Issue by AlexisGrey1** [fuji97/pokemon-xenoverse-tracker#716]
ciao! Ho notato che dopo aver installato la patch 1.0.3 le ball in fase di cura al pokemon center risultano tutte solo poke ball!

**Comment by andrewrov** [comment]
Se avessi letto il changelog sapresti che non è un bug ma bensì una scelta degli sviluppatori (per evitare un bug che causava il crash del gioco se ho ben capito).
Capisco che vogliano tutti aiutare segnalando eventuali problemi ma se prima di scrivere non ci si informa un minimo se sia realmente un bug o se sia già stato scritto una o più volte si va solo a riempire gli sviluppatori di problemi inutili.

**Comment by AlexisGrey1** [comment]
ti ringrazio andrewrow, ma non sapevo dove si trovasse il changelog. Per fortuna ho visto che un'altra persona che aveva notato la stessa cosa, e ha scritto, ha ricevuto il link di riferimento nei commenti :)

**Comment by andrewrov** [comment]
Ah okay perfetto, giusto una cosa, il mio nick non è andrewRiga (row) ma andrewrov ahah

**Comment by AlexisGrey1** [comment]
k bye

**Comment by AlexisGrey1** [comment]
updato! :P
