### ISSUE TITLE
Sfida shulong x Bug

### ISSUE THREAD

**Issue by asSo2131** [fuji97/pokemon-xenoverse-tracker#718]
---------------------------
Xenoverse
---------------------------
Exception: RuntimeError

Message: filename is nil

SpriteWindow:218:in `initialize'

Pokemon_Sprites:113:in `new'

Pokemon_Sprites:113:in `pokemon='

Pokemon_Sprites:99:in `initialize'

PScreen_Party:388:in `new'

PScreen_Party:388:in `initialize'

PScreen_Party:753:in `new'

PScreen_Party:753:in `pbStartScene_ebs'

PScreen_Party:751:in `each'

PScreen_Party:751:in `pbStartScene_ebs'

This exception was logged in 

C:\Users\Utente\Saved Games/Xenoverse/errorlog.txt.

Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

**Comment by asSo2131** [comment]
Quando un mio pokemon va KO e devo sostituirlo mi chiede di scegliere se continuare o fuggire qualsiasi sia la risposta non posso fare niente la schermata si bugga sulla selezione dei miei pokemon in "panchina" la lotta apparentemente continua shulong attacca ma non colpisce nessuno e l' errore si ripete. Cmq il bug dello schermoluce è successo anche a me ma non ho salvato la schermata di errore..

**Comment by tonynart** [comment]
l'ultima sfida col proprio starter in forma X, l'ho fatta senza problemi giusto ieri. Gioco con la versione 1.0.3. Prova a disinstallare tutte e installare il gioco dalla versione 1.0.0 e provi a vedere se il bug si ripresenta. Man mano che provi, vai installando le varie patch, una alla volta, e testi se il problema si ripresenta. è strana questa cosa, avevano risolto tutto dalla 1.0.3. Fai questi tentativi o aspetta la patch 1.0.4 che uscirà a brevissimo
