### ISSUE TITLE
pokewes

### ISSUE THREAD

**Issue by Jimmopolis** [fuji97/pokemon-xenoverse-tracker#721]
ma il pokewes non lo da più dopo elekid x? non lo ricevo più e neanche le xenoball che da ezio. Per caso avete modificato il modo di ottenere il pokewes?. In quel momento manca tutto il dialogo del pokewes. Inizia subito con bene nome questo è il mio laboratorio. Spero che non sia un bug o un problema di salvataggio corrotto. Ho provato anche a rimuovere e installare da capo con le patch  rimettendo il mio salvataggio ma non c'è il dialogo. rispondetemi per favore

**Comment by Tetsu93** [comment]
non si riceve più dopo elekid x, lo riceverai comunque più avanti

**Comment by Jimmopolis** [comment]
ok grazie della risposta
