### ISSUE TITLE
[1.0.4] Joele continua a seguirmi

### ISSUE THREAD

**Issue by SkyAxel** [fuji97/pokemon-xenoverse-tracker#728]
Come da titolo, nonostante abbia installato la 1.0.4 la guardia dell'Oasi Cocente (Joele) continua a seguirmi con lo sprite dello starter. Posso comunque usare volo ma non le funi di fuga.

**Comment by tonynart** [comment]
è un tuo problema.. io giocando alla versione 1.0.3 non ho riscontrato questo problema... prova a disinstallare tutto e reinstallare nuovamente. ti rispeto io non ho avuto questo problema

**Comment by andrewrov** [comment]
Non hanno ancora trovato una soluzione per chi ha il follow attivo, chi ha la nuova patch non ha il rischio che si attivi (in teoria) ma non hanno ancora trovato il modo per disattivarla a chi ce l'ha già attiva

**Comment by Pugnator123** [comment]
Il bug a me è accaduto nella 1.0.3, con l'aggiornamento alla 1.0.4 mi si è risolto il tutto.

**Comment by andrewrov** [comment]
@Pugnator123 a me è successo nella 1.1.2 e nella 1.1.4 persiste
