### ISSUE TITLE
Ombra a Ludopoli

### ISSUE THREAD

**Issue by DartFeld92** [fuji97/pokemon-xenoverse-tracker#73]
A Ludopoli, dopo lo scontro col capopalestra, ho notato quest'ombra che si trova fissa a quell'altezza della mappa e si muove in orizzontale insieme al giocatore.
http://oi66.tinypic.com/14cvhom.jpg
http://oi66.tinypic.com/c5b43.jpg

**Comment by fuji97** [comment]
Grazie per la segnalazione, vedremo di risolvere. Non ha comportato particolari errori nel gioco vero?

**Comment by DartFeld92** [comment]
Non ha portato problemi. Entrando nel centro medico e poi uscendo è sparita. Sono rientrato nella palestra per allenarmi un poco ed al ritorno è comparsa di nuovo l'ombra.
