### ISSUE TITLE
Non so usare la Ikarium N

### ISSUE THREAD

**Issue by Nadttam** [fuji97/pokemon-xenoverse-tracker#730]
Ciao, scusate la domanda.. ma come si fa ad usare la ikarium N per volare?? provo a cliccare sopra ma mi apre solo il menu che dice dai o butta..

**Comment by LeonidaXX1** [comment]
Devi visualizzare e attivare le gemme dal PokéWES. Mentre per le gemme che attivano Forza o Spaccaroccia basta premere Invio sul masso da spostare o sulla roccia da frantumare per attivarle (probabilmente succederà anche per Taglio e Surf), Volo è una MN che va attivata manualmente. Vai sul PokéWES, fai Invio su Icarium N e vola!

**Comment by Nadttam** [comment]
E' possibile che io non ho il pokewes? dove lo si prendeva?

**Comment by LeonidaXX1** [comment]
Di norma te lo da Ezio dopo che hai sconfitto Elekid X, quando ti porta nel suo laboratorio, in quell'occasione ti ringrazia di averlo battuto dandoti il PokéWES, poi ti dà un'altra manciata di Xeno Ball e poi si defila

**Comment by Nadttam** [comment]
infatti mi ricordavo che me lo avesse dato.. ma non lo trovo negli oggetti della borsa.. mo ricerco.. però se sta nella tasca sturmenti chiave non lo ho O.O

**Comment by AkeRoss** [comment]
non sta nella borsa, quando apri il menu ci sta un icona apposita per il pokewes

**Comment by GiulioMe** [comment]
Premi   W   ,si apre il menu, et voila!

**Comment by Nadttam** [comment]
se è l'icona sopra al salvataggio.. io ce l'ho vuota xD e quindi non l'ho presa.. comunque se premo w non appare niente

**Comment by Nadttam** [comment]
mi sono fatto il viaggio a ritroso sono tornato al laboratorio e appena entrato mi è apparso il commento di ezio che mi dava il pokeweis... ahahah xD ho risolto grazie a tutti...

**Comment by sebypalma27** [comment]
Come hai fatto a tornare indietro? Io ho il tuo stesso problema (prima parte finita ma sto senza pokewes e vorrei usare "volo"). Ho provato anch'io a rifare tutta la strada indietro ma poi rimango bloccato in quel paese dove ti lascia Ezio con Alakazam

**Comment by Linkzelda005** [comment]
Scusate ragazzi qualcuno di voi mi sa dire dove si trova la mnsurf
