### ISSUE TITLE
Info: Scaleon evento

### ISSUE THREAD

**Issue by LeonidaXX1** [fuji97/pokemon-xenoverse-tracker#732]
Ciao a tutti, anch'io rientro tra gli sfortunati che hanno perso il loro Scaleon durante la battaglia contro lo starter X. Ho visto il video in cui Zio Cricco spiega che è stato rilasciato uno Scaleon evento. Ecco, di che evento si tratta? Come lo attivo?

**Comment by tonynart** [comment]
penso che debbano ancora rilasciarlo...
