### ISSUE TITLE
Eevee

### ISSUE THREAD

**Issue by tonynart** [fuji97/pokemon-xenoverse-tracker#734]
Oltre all' Eevee che si unisce al party durante l'avventura, è possibile catturane uno selvatico nella prima parte?

**Comment by andrewrov** [comment]
Non è un bug, avresti potuto chiederlo sul gruppo apposito su facebook.
Comunque non si può, se ne trova solo 1 e la pensione non è attiva nella prima parte (quindi non puoi farci neanche l'uovo)

**Comment by tonynart** [comment]
Si hai ragione, ma volevo comunque avere conferma! ;)
