### ISSUE TITLE
Personaggio non controllabile

### ISSUE THREAD

**Issue by AndreAnge** [fuji97/pokemon-xenoverse-tracker#737]
Nel percorso 8, quando si entra nella piccola grotta che porta da droccia draconica al vulcano decibel, il PG cammina automaticamente in avanti, incastrandosi contro una roccia, ed è impossibile farlgi eseguire qualsiasi movimento! E' un peccato perchè mi impedisce di proseguire nella storia :(
Inoltre se si prova a usare fossa il gioco crasha

**Comment by LeonidaXX1** [comment]
Aggiorna alla versione 1.0.4, a me il problema si è risolto così
