### ISSUE TITLE
Dov'è Nunvil?

### ISSUE THREAD

**Issue by DragonX93** [fuji97/pokemon-xenoverse-tracker#741]
Ho finito la parte 1 (gioco fantastico, complimenti ai creatori 😄 ) e sono tornato indietro per catturare qualche altro Pokèmon.

Sono tornato nell'isola Voodoo per cercare un Nunvil, ma ho girato e girato per un bel po' di tempo e non ne ho trovato nemmeno uno (solo Gastly, Puppillon e Trampille).
Nunvil si trova solo in un certo periodo della giornata (notte) oppure è raro da trovare e io sono stato sfortunato?

**Comment by q1w2e34** [comment]
si trova solo di notte :)

**Comment by DragonX93** [comment]
@q1w2e34 grazie :)
