### ISSUE TITLE
Valore di precisione delle mosse

### ISSUE THREAD

**Issue by NotMyUsuallyNick** [fuji97/pokemon-xenoverse-tracker#755]
È possibile che ci sia qualche problema con la precisione delle mosse?
Sono oltre la terza palestra e ho notato alcune cose strane:
uso fuocofatuo quasi in ogni battaglia e non ha mai fallito, un po' strano dato il 75% di precisione.
da quando ho Scaleon, uso spesso Turbosabbia: nonostante lo usi 2,3 volte sullo stesso pokemon, le mosse avversarie continuano a colpirmi 9 volte su 10.
Qualcun altro a notato questa cosa o sono solo stato fortunato/sfortunato?

**Comment by andreaalemanni** [comment]
bho turbosabbia su scaleon l'ho usato anche io per un po' e bho i nemici non mi attaccavano mai quindi mi sa che sei stato solo molto fortunato
