### ISSUE TITLE
Bug Gravissimo 1.0.4

### ISSUE THREAD

**Issue by lamasfoker** [fuji97/pokemon-xenoverse-tracker#759]
L'Immagine dice tutto!
![13263843_1062031023872010_3086519413215694049_n](https://user-images.githubusercontent.com/12940668/30725634-60fa1926-9f46-11e7-971e-ec036d3668c2.jpg)

**Comment by GameWarriorPlsE** [comment]
anch'io l'ho trovata negli audio
