### ISSUE TITLE
Scheda allenatore

### ISSUE THREAD

**Issue by Moraboss** [fuji97/pokemon-xenoverse-tracker#76]
Sulla scheda allenatore c'è la foto del personaggio maschile, quando io ho scelto il personaggio femminile!

**Comment by fuji97** [comment]
Abbiamo testato ma a noi non risulta, scegliendo il personaggio femminile appare la trainer card femminile

**Comment by Moraboss** [comment]
________________________________

**Comment by Thalema** [comment]
Scusatemi ma anche a me da lo stesso problema, se guardo la scheda allenatore (ho istallato entrambe le patch) trovo la foto del personaggio maschile nonostante io abbia la protagonista femminile
