### ISSUE TITLE
Love Ball

### ISSUE THREAD

**Issue by Yvaall** [fuji97/pokemon-xenoverse-tracker#764]
ho terminate la parte uno, ma non riesco più a trovare l'npc che vendeva le love ball. mi servono per fare le scuamacuore .-.

**Comment by LeonidaXX1** [comment]
Dopo la patch non serve più la Love Ball ma una bacca che vende il mercante a Oasi Cocente. Si trova a nord del centro pokémon, vende sia la Love Ball che questa bacca

**Comment by Yvaall** [comment]
oh grazie mille, non lo sapevo neanche che non servisse più
