### ISSUE TITLE
Tasti mancanti tv

### ISSUE THREAD

**Issue by MaKL98** [fuji97/pokemon-xenoverse-tracker#79]
Salve premetto che ho appena cominciato a giocare e non so se più avanti questo lieve bug persiste ma quando si vuole accendere la televisione in camera non vengono visualizzati le sritte si o no 
![tv](https://user-images.githubusercontent.com/31803897/30242361-564d4846-9595-11e7-8934-476a419f71ac.PNG)

**Comment by fuji97** [comment]
Già segnalato #8
