### ISSUE TITLE
patch

### ISSUE THREAD

**Issue by REYBAN23** [fuji97/pokemon-xenoverse-tracker#792]
mmm ho un piccolo o grande problema, ho il gioco installato in una cartella, quindi ogni patch uscita a quanto sembra non l'ho installata nel gioco, cosa posso fare? tipo fatto da poco ho ricevuto la terza medaglia e non posso catturare i pokemon e nemmeno c'è nel regno caramello il npc che risolve il bug.

ps: ho messo l'immagine per farvi capire.

![bug](https://user-images.githubusercontent.com/31818803/30781606-965bb8ee-a122-11e7-8dc3-5a374b459890.jpg)

**Comment by LeonidaXX1** [comment]
Sembra che tu abbia il gioco installato in Desktop/Xenoverse/Pokémon Xenoverse. Non capisco perché hai fatto un passaggio in più. La cartella del gioco è Pokémon Xenoverse, non serve metterla dentro un'altra cartella. In genere gli installer delle patch rilevano automaticamente la posizione dei file di gioco e li sovrascrivono con i nuovi file, ma forse questo può aver causato confusione. Ti conviene disinstallarlo completamente e re-installarlo, se vuoi già aggiornato alla 1.0.4 dal sito Xenoteam.it, scegliendo come destinazione una cartella più interna del pc, come C/Programmi, e lasciare la cartella Pokémon Xenoverse così com'è dentro a Programmi, senza metterla dentro un'ulteriore cartella. Al massimo sul Desktop ti fai il collegamento all'eseguibile che è il gioco vero e proprio, che sarebbe così locato come C/Programmi/Pokémon Xenoverse/Game.exe

**Comment by REYBAN23** [comment]
ma i dati del gioco verranno cancellati? nel senso dovrò ricominciare?

**Comment by LeonidaXX1** [comment]
I dati di gioco non stanno lì ma nella cartella Partite salvate situata in tutt'altra parte, quindi il salvataggio non verrà toccato

**Comment by REYBAN23** [comment]
si si, lo so, però pensato che venivano cancellati automaticamente anche quelli... ok,  grazir mille!
