### ISSUE TITLE
Font mancanti anche dopo averli installati

### ISSUE THREAD

**Issue by SkiFire13** [fuji97/pokemon-xenoverse-tracker#8]
Il gioco non visualizza correttamente alcuni font (non mostra proprio nessun carattere) in alcune schermate.
Queste schermate sono:
- quella che si presenta appena aperto il gioco
- quella che sembrerebbe essere la schermata principale
- quella in cui ci viene chiesto di scegliere il proprio nome (non mostra il nome che sto scrivendo)
-  quella dopo che nostra madre si riposa (mi sono fermato qui)

Le immagini con le relative descrizioni sono disponibili [qui](http://imgur.com/a/0qSQB)

Le altre schermate finora visualizzate funzionano come dovrebbero (penso, in caso contrario potete dare un'occhiata [qui](http://imgur.com/a/kDkh7)).

Altre informazioni:
- I font sono stati installati manualmente, sia selezionandoli tutti e facendo Installa sia installandoli uno ad uno (ogni volta sostituendo quelli già esistenti). Su Word (usato per testare) risultano tutti installati e nessuno presenta caratteri vuoti al posto dei normali caratteri. La dimensione dei caratteri è 14 per tutti.
 Immagine visibile [qui](https://i.imgur.com/EjmbUcb.jpg).
- Il gioco viene avviato come amministratore.
- Ho anche provato ad avviare il gioco con compatibilità con windows 7 (nessun successo).
- Non ho mai giocato la beta, quindi non so dire se gli stessi problemi li ho trovati lì oppure no.
- Lo SHA-256 del file zip è 4EC90E13DE4B2961A1D9A90DF5A14F0CC75AA18A666C3677275877F25078C67D per verificare che non fosse corrotto (avendolo copiato a mano potrebbe essermi sfuggita una lettera o due, quindi se non combaciasse tenetelo in considerazione)

Specifiche del pc:
- Windows 10 Pro, versione 1703, build 15063.540
- Processore: AMD FX-8350
- RAM: 8GB
- Scheda video: nvidia GTX 780 (driver 385.41, l'ultimo disponibile)
- SSD (su cui è installato il gioco) con 60GB di spazio libero
Librerie/Framework installati:
- .NET Framework 4.5.1, 4.5.2 e 4.6
- Microsoft Visual C++ 2005, 2008, 2010, 2012, 2013, 2015 e 2017
- Java 8 Update 144

**Comment by fuji97** [comment]
Grazie per la segnalazione e complimenti per tutti i dettagli che hai inserito, ci hanno risparmiato molte ricerche. Per quanto riguarda il bug è un errore alquanto strano in quanto sembra essere stato segnalato solo da te, ne teniamo conto e vediamo se è possibile impostare un font di fallback per quelle schermate

**Comment by fuji97** [comment]
Abbiamo trovato il problema, sarà sistemato nella prossima release
