### ISSUE TITLE
non mi fa catturare gengar x

### ISSUE THREAD

**Issue by andrix95** [fuji97/pokemon-xenoverse-tracker#808]
non mi fa catturare gengar x mi dice che le ball sono efficaci.. (parlo delle xeno ball e anche le ball normali)

**Comment by Espo27** [comment]
a quanto ho capito gengar x non si può catturare per ora, sicuramente nella seconda parte ci daranno un'altra opportunità

**Comment by andrix95** [comment]
grazie lo capito d asolo ora.. pero una specie x che mi piaceva...
