### ISSUE TITLE
Bug pokemon compagno/oggetto città ghiacciata

### ISSUE THREAD

**Issue by polinoto** [fuji97/pokemon-xenoverse-tracker#81]
A seguito della duplice morte contro il primo allenatore (avendo preso lo starter erba/folletto e trovandomi contro un weedle con velenospina) è apparso il Pokemon compagno, seguendomi per tutta l'avventura, parlando con questo tenendo per primo in squadra lui non ci sono problemi (tranne nella grotta prima del percorso 3, ma solo dopo aver salvato il bambino), altrimenti crasha. Allo stesso modo nel tentativo di prendere l'oggetto nella città ghiacciata il gioco crasha.

**Comment by fuji97** [comment]
Grazie per la segnalazione, cercheremo di risolvere per la prossima patch

**Comment by fuji97** [comment]
Teoricamente risolto
