### ISSUE TITLE
Gengar X problem still unsolved

### ISSUE THREAD

**Issue by kratosdu12** [fuji97/pokemon-xenoverse-tracker#82]
Sono bloccato nella ricerca dell'oasi con gengar mi viene chiesto di portarlo cibo ma non so come fare

**Comment by fabstarkey** [comment]
devi andare verso il ponte!

**Comment by kratosdu12** [comment]
Sono andato al ponte ma l'evento con le guardie che sono gengar prima è attivato e quindi non posso combattere il gengar

**Comment by kratosdu12** [comment]
la guardia è già con me ma l'evento con il gengar non si attiva

**Comment by kratosdu12** [comment]
quando mi avvicino alla piramide con la guardia dove c'è gengar non succede niente

**Comment by fuji97** [comment]
Ok, bug noto, stiamo cercando di capire come avviene, potresti condividere in questo post il tuo salvataggio per favore?

**Comment by kratosdu12** [comment]
Sì, lo condividerò, spero che il problema sarà risolto rapidamente e vi ringrazio per aver risposto a me

**Comment by fuji97** [comment]
Lo stiamo analizzando e visto che a noi non è mai capitato ci servirebbe un salvataggio incriminato per poterlo testare

**Comment by kratosdu12** [comment]
Ci vorrà un po' per farla camminare?

**Comment by Laky2082** [comment]
se posso unirmi alla "conversazione", io ho lo stesso problema, inoltre premendo il tasto di interazione sulla scala con le guardie mancanti vicino al self chansey mi compare la schermata di sconfitta che recita "per evitare ulteriori danni alla sua squadra.." .
inoltre dopo essere respawnato, il tipo che ti seguiva non c'era piu.
ho provato anche a parlarci pensando fosse tipo invisibile ma nulla.
spero di aver dato una mano

**Comment by Reachid** [comment]
Pure io mi unisco al problema di gengar. nonostante sia arrivato alla piramide con lui sopra l'evento non parte

**Comment by fuji97** [comment]
Risolto, verrà sistemato nella prossima release
