### ISSUE TITLE
Evoluzione mancata

### ISSUE THREAD

**Issue by WhY777** [fuji97/pokemon-xenoverse-tracker#846]
Ciao a tutti il problema è che ho un Jalapucha al livello 45 mentre invece al 40 avrebbe dovuto evolversi in Scoville. Grazie in anticipo

**Comment by Yvaall** [comment]
Non c'è un livello per farlo evolvere. Serve una pietrafocaia o pietrafoglia, non ricordo bene quale

**Comment by WhY777** [comment]
La pietrafocaia. Avevo visto su xenopedia però che si evolveva al 40. Comunque grazie e complimenti agli sviluppatori

**Comment by WhY777** [comment]
La pietrafocaia. Avevo visto su xenopedia però che si sarebbe evoluto al 40. Comunque grazie e complimenti agli sviluppatori
