### ISSUE TITLE
PROBLEMA CON I FONT

### ISSUE THREAD

**Issue by Fede96** [fuji97/pokemon-xenoverse-tracker#85]
Buona sera ragazzi, volevo segnalare un problema che non riesco a risolvere.. il gioco non legge nessun tipo di font, solo i dialoghi. Ho provato a installarli anche manualmente ma niente da fare, riuscite a darmi una mano? grazie in anticipo!

**Comment by fabstarkey** [comment]
prova a riscaricare Xenoverse. Nella cartella fonts riscaricali tutti!

**Comment by fuji97** [comment]
Duplicato di #8. Chiudo
