### ISSUE TITLE
Crash istantaneo

### ISSUE THREAD

**Issue by Revangel93** [fuji97/pokemon-xenoverse-tracker#86]
Sono entrato nel centro Pokémon e ho salvato. Appena concluso il salvataggio, questo avviso di errore 
[http://i.imgur.com/EXCdOAq.png](url)

Ho provato a riavviare il gioco diverse volte, ma il risultato rimane invariato. 
Il file di salvataggio sembra essere perduto.

Spero riusciate a risolvere.

Ne approfitto per avvertirvi che ci sono alcuni errori nei testi e che la mossa Vocalizzo non ha descrizione.

**Comment by fabstarkey** [comment]
ciao revangel! devi avviare il gioco come amministratore. vai su proprietà>Compatibilità e in basso checkare la spunta esegui questo programma come amministratore.

**Comment by Revangel93** [comment]
Grazie mille per la risposta, ma purtroppo il problema persiste.

Leggevo nelle FAQ che lo starter che segue l'allenatore potrebbe significare un salvataggio corrotto, è possibile che sia questo il problema?

**Comment by fuji97** [comment]
@Revangel93 Si, ti confermo che è quello, stiamo lavorando per risolverlo definitivamente. Appena carichi il salvataggio ti appare quell'errore o se fai certe operazioni?
