### ISSUE TITLE
bug (?) pokedex, pokemon mancanti

### ISSUE THREAD

**Issue by Evyck** [fuji97/pokemon-xenoverse-tracker#87]
stavo cercando alcuni pkmn visti e sconfitti di allenatori ma non li trovo nel pokedex
come ad esempio il pkmn tipo lotta con un pezzo di legno (?) sotto al braccio o magnemite o aron
sconfitti ma nel pokedex mancano

**Comment by Evyck** [comment]
scrivo che mancano molti altri pkmn come quello di A&B, porigon ed altri ancora nel pokedex dopo averli sconfitti

**Comment by fuji97** [comment]
Grazie per la segnalazione
