### ISSUE TITLE
Bug abilità Sopportazione

### ISSUE THREAD

**Issue by Metalcape** [fuji97/pokemon-xenoverse-tracker#88]
L'abilità sembra non funzionare. Non appare il tipico messaggio di attivazione dell'abilità, e la difesa non sembra aumentare quando il pokémon viene colpito.

**Comment by fuji97** [comment]
Grazie per la segnalazione, controlleremo il prima possibile

**Comment by xZekro51** [comment]
Risolto, il bug verrà sistemato con la prossima patch.
