### ISSUE TITLE
Trishout 

### ISSUE THREAD

**Issue by CADORE90** [fuji97/pokemon-xenoverse-tracker#89]
Per curiosità come si fa ad evolvere al secondo stadio e a che livello?

**Comment by Evyck** [comment]
non so, io sono al lvl 29...
comunque scrivilo che è una curiosità nel titolo ^^

**Comment by CADORE90** [comment]
Ok si buon consiglio. Io sono al livello 40 e non si evolve, e sono alla palestra zucchero che non si può sconfiggere. Troppo difficile

**Comment by DarkFire1110** [comment]
Gli starter non si evolvono per livello ma hanno le evoluzione terrestri e xenoverse. Per ottenerle bisogna dare l'anello terrestre o xenoverse al pokemon

**Comment by Evyck** [comment]
non sono delle evoluzioni ma delle trasformazioni
magari si evolveranno nella seconda parte

**Comment by CADORE90** [comment]
Darkfire e quello xenoverse dove lo trovo?

**Comment by fabstarkey** [comment]
giocate e troverete tutte le vostre risposte. Questo sito serve per trovare i bug, sicuramente non vi nascondiamo le evoluzioni. Chiudo!
