### ISSUE TITLE
bug grave mimikyu

### ISSUE THREAD

**Issue by frangnosquest** [fuji97/pokemon-xenoverse-tracker#899]
mimikyu trishout crasha appena si tenta di usarlo in battaglia, non so se è così anche con gli altri 2

**Comment by Absol99** [comment]
Io ho notato che quando si è socnfitti da lui la battaglia non parte più

**Comment by frangnosquest** [comment]
Mi è venuta un idea, la causa potrebbe essere simile a quella dell' ex bug del centro pokemon, qualcuno può provare ad aprire il gioco in modalità amministratore, qualcuno può confermarmi dato che ho chiuso il pc?

**Comment by grouchality** [comment]
crash in entrambi i casi

**Comment by frangnosquest** [comment]
Ok hanno risolto chiudo
