### ISSUE TITLE
Bug Mimikyu in lotta (messaggio di errore allegato)

### ISSUE THREAD

**Issue by AkeRoss** [fuji97/pokemon-xenoverse-tracker#906]
mettendo mimikyu come primo pokemon in squadra ed avviando una lotta appare questo messaggio

![immagine](https://user-images.githubusercontent.com/31889879/32253592-02c42584-be9c-11e7-9a18-14e8168a7112.png)

e credo che Fantasmanto non funzioni dato che durante la lotta con lui non si è attivato

**Comment by nintendostar** [comment]
Fortuna che ogni volta salvo prima di vedere se anche a me faccia così 😂

**Comment by frangnosquest** [comment]
Risolto nella patch nuova,puoi anche chiudere
