### ISSUE TITLE
Pacchetto completo

### ISSUE THREAD

**Issue by Alderaan9** [fuji97/pokemon-xenoverse-tracker#909]
Visto che non partiva l'evento di Halloween ho installato il pacchetto completo ma ora il gioco non parte

**Comment by frangnosquest** [comment]
Hai un backup dei salvataggi?in tal caso ridisintalla e rereinstalla e facci sapere se è cambiato qualcosa

**Comment by Alderaan9** [comment]
Risolto installando nuovamente la versione 1.04 e aggiungendo le patch singolarmente
