### ISSUE TITLE
Problema pesca

### ISSUE THREAD

**Issue by AkeRoss** [fuji97/pokemon-xenoverse-tracker#916]
ho notato che avete modificato l' azione della pesca, ora non parte più il minigioco ma fa dei puntini il problema oltre al fatto che adoravo quel giochino è che non mi fa pescare da nessuna parte ogni volta mi dice, dopo aver fatto un poi di puntini, "Neanche una vecchia ciabatta"

**Comment by Angeloz95** [comment]
nooooo sei una cattiva persona, c'erano 420 post aperti e mi stavo godendo il numero che poi è cambiato :'(

**Comment by Tetsu93** [comment]
Hai assegnato l'amo a f5 o fai usa? Se l'hai assegnato anche prima diceva sempre "neanche una vecchia ciabatta" mentre se fai usa inizia il minigioco
