### ISSUE TITLE
Descrizione mossa

### ISSUE THREAD

**Issue by Pizdav** [fuji97/pokemon-xenoverse-tracker#92]
Nella mossa "Vocalizzo" non c'è la descrizione

**Comment by Pizdav** [comment]
![image](https://user-images.githubusercontent.com/31807023/30243759-dfb319ba-95b0-11e7-83cf-5a88ae7d652e.png)

**Comment by Evyck** [comment]
è già stato segnalato questo bug, tranquillo
prima di postare un bug, prova a cercare se è già stato inserito ^^

**Comment by Pizdav** [comment]
ok
