### ISSUE TITLE
teletrasporto

### ISSUE THREAD

**Issue by Evyck** [fuji97/pokemon-xenoverse-tracker#93]
quando si usa il teletrasporto compare il messaggio di errore ed il gioco si chiude

**Comment by fabstarkey** [comment]
ciao evyck puoi dirci esattamente dove ti da errore?

**Comment by Evyck** [comment]
Ho raggiunto il centro Pkmn in dolce mela e poi sono tornato indietro
Prima di entrare nel Bosco ho usato macabra al lvl 29 per teletrasportarmi a dolce mela e li mi ha dato una piccola Schermata di errore per poi chiudere il
Gioco 
Ho fatto imparare un'altra mossa dopo il problema per non avere noie quindi, se devo far comparire la schermata di errore per voi, vado a catturare un nuovo abra, se me lo fa fare
(Ho il bug della terza palestra con l'impossibilità di catturare i Pkmn)

Quando uscirà la nuova patch?

P.S.: questo gioco mi sta piacendo molto di più degli ultimi Pkmn usciti

**Comment by fuji97** [comment]
Grazie per i complimenti, se riesci a procurarci la schermata di errore ci faresti un gran piacere!

**Comment by Evyck** [comment]
mi spiace ma dopo aver affrontato la terza palestra, non posso catturare più pokemon, neanche nei percorsi precedenti

**Comment by Fenooo** [comment]
![cattura](https://user-images.githubusercontent.com/31832405/30253993-3ebb6404-9691-11e7-8d7b-267ec5afdd5d.PNG)
Eccola

**Comment by fuji97** [comment]
![image](https://user-images.githubusercontent.com/9747718/30299872-0e12b25a-9752-11e7-8a18-206a722366c7.png)

**Comment by fuji97** [comment]
Sistemato
