### ISSUE TITLE
Richiesta e problemi

### ISSUE THREAD

**Issue by AkeRoss** [fuji97/pokemon-xenoverse-tracker#942]
Avrei una richiesta da fare, mi piacerebbe da morire se poteste fare un' evoluzione del pokemon Puppillon sarebbe una meraviglia ^.^
Il problema riguarda l' abilità Sopportazione che non si attiva con nessun tipo di danno subito nonostante le varie patch

**Comment by Bulzeeb88** [comment]
l'evoluzione di puppillon è già prevista

**Comment by AkeRoss** [comment]
nel senso che è già stata implementata o lo sarà nel' episodio 2?

**Comment by Bulzeeb88** [comment]
dovrebbe esserci nella parte 2 del gioco
