### ISSUE TITLE
Bug del PokéWes

### ISSUE THREAD

**Issue by JeckX** [fuji97/pokemon-xenoverse-tracker#96]
Ho superato il laboratorio nella città di Ludopoli senza che mi fosse lasciato il Pokéwes da Ezio. Come si vede dallo screen, sono davanti la palestra e il PokéWes non c'è.

PS: so che avrei dovuto riceverlo da Ezio perché sto giocando in contemporanea con la mia ragazza e lei l'ha ottenuto così.
![cattura](https://user-images.githubusercontent.com/31808466/30244394-64db0146-95bd-11e7-8d44-ac5b9758cb3f.JPG)

**Comment by fuji97** [comment]
Grazie per la segnalazione

**Comment by fuji97** [comment]
EDIT: Si ottiene dopo la palestra, quindi continua tranquillamente

**Comment by JeckX** [comment]
Grazie per la risposta e per aver risolto il problema :+1: Continuate così, avete fatto un lavoro titanico!
