### ISSUE TITLE
Palestra zucchero 

### ISSUE THREAD

**Issue by CADORE90** [fuji97/pokemon-xenoverse-tracker#97]
Ogni volta che si perde il gioco resta con lo schermo tutto nero. Abbassate la difficoltà di sta palestra sono al livello 41 e perdo sempre

**Comment by xLele11** [comment]
non è troppo difficile la palestra zucchero io l'ho sconfitta con 4 pokemon al 28/30 senza mai perdere  e senza usare pozioni e non avevo neanche mosse super efficaci contro il tipo folletto. PS alla fine di ogni prova puoi uscire dalla palestra per andare a curarti i pokemon al centro pokemon alla fine della prima ti vai a curare i pokemon e fai cosi anche alla fine della terza prova prima di sfidare la capopalestra al massimo se non riesci usi le superpozioni. Se hai il pokemon elettro/volante con tuononda e trespolo riesci a vincere facile.

**Comment by CADORE90** [comment]
C'è l'ho fatta dopo svariati tentativi
