### ISSUE TITLE
Come spostare il salvataggio

### ISSUE THREAD

**Issue by andrewrov** [fuji97/pokemon-xenoverse-tracker#98]
Esiste un modo per spostare il salvataggio del gioco? Per esempio per spostarsi su un'altro pc

**Comment by fabstarkey** [comment]
vai su C:-> utenti -> partite salvate -> xenoverse. Li trovi il tuo salvataggio. Sposta tutta la cartella Xenoverse se no perderai i dati ;)

**Comment by fuji97** [comment]
Puoi cercare anche direttamente "Partite Salvate" dal menù Star di Windows

**Comment by andrewrov** [comment]
Grazie mille
