### ISSUE TITLE
Bosco filante 

### ISSUE THREAD

**Issue by CADORE90** [fuji97/pokemon-xenoverse-tracker#99]
I tre alberi alla fine dove c'erano i ragazzini ci si può passare attraverso e ci sono punti in cui si può attraversare gli alberi e poi si arriva a fine mappa con sfondo nero

**Comment by fabstarkey** [comment]
se non ci indichi i punti dove trovi lo sfondo nero e trapassi sugli alberi, non li troveremo mai. Mandaci una foto!

**Comment by CADORE90** [comment]
Ho provato a Cercare i punti ma non mi ricordo più perché ci ero impattato a caso. Se mi capita altre cose simili ora che lo so faccio foto. Grazie
